### ISSUE TITLE
Driver not found during setup of configuration

### ISSUE THREAD

**Issue by jasonmuzzy** [jeffpiazza/derbynet#1]
After initial installation, created local folder and granted writer permission.  Created gprm 32-bit ODBC connection.  Clicked Configure button, chose ODBC, entered gprm as DSN and clicked submit but received the following error.  Note, this same setup with the older 0.5 release of gprm-web worked fine.
![image](https://cloud.githubusercontent.com/assets/15488120/10860603/cbdd18e2-7f27-11e5-939e-29c0e5439697.png)

**Comment by jeffpiazza** [comment]
Could you send me the output from the …/about.php page (“About” button from front menu)?

Also, what version of Windows are you running?

Thanks!
/JEP

**Comment by jasonmuzzy** [comment]
I can't get to the about page.  I'm stuck on the setup page, and even manually entering the address for .../about.php forces me back to setup.php.  Can you think of another way I can get that info for you?

I'm running Windows 10 with IIS 10.

Thank for making this project publicly available.  It's so cool!!

**Comment by jeffpiazza** [comment]
Hmm, I kind of painted myself into a corner with the redirection on the About page, didn’t I?

If you drop this file in with the others, visiting it from a browser should report most of the particulars about your PHP installation.


Even without that, though, I’m pretty confident in guessing that you’re most likely missing the driver called php_pdo_odbc.dll.  Depending on where you got PHP from, you’d find this in the “ext” directory next to the PHP.EXE executable.

It’s also possible that you have the driver, but it’s not enabled.  (Actually, this might even be the more likely thing.)  To check that, you’d look in the configuration file called PHP.INI, where you should see (among lots of other things) two lines like this:

[PHP_PDO_ODBC]
extension=php_pdo_odbc.dll

If they’re not there, are they’re commented out, the fix would be to add or uncomment.  Be sure to restart your web server (IIS or Apache) after you do this.

/JEP

**Comment by jasonmuzzy** [comment]
That worked!  The php.ini file had this comment in it:
; Windows Extensions
; Note that ODBC support is built in, so no dll is needed for it.
; Note that many DLL files are located in the extensions/ (PHP 4) ext/ (PHP 5)
; extension folders as well as the separate PECL DLL download (PHP 5).
; Be sure to appropriately set the extension_dir directive.

But I went ahead and added the following 2 lines right after it like you sugested:
[PHP_PDO_ODBC]
extension=php_pdo_odbc.dll
