### ISSUE TITLE
Replay kiosk missing hostname

### ISSUE THREAD

**Issue by chunter2** [jeffpiazza/derbynet#101]
When I choose a replay kiosk the URL is missing the hostname / IP address.  It's just an underscore.  My server is a Raspberry Pi and I'm connecting to it from a laptop.  

![replay kiosk](https://user-images.githubusercontent.com/531129/72272894-5f487600-35f7-11ea-81ca-b56d5dd5d8b6.jpg)

**Comment by heatvent** [comment]
I noticed the same thing.  It also happens when you choose Full Screen Kiosk. I have seen this on a deskptop and on my iPhone.

**Comment by Blackbird714** [comment]
I had the same problem; this is apparently an issue with how the SERVER_NAME variable gets resolved in certain configurations.  This thread for WordPress discusses and debates it at length.  For my local install, I hacked two files:

/var/www/html/derbynet/fullscreen.php
/var/www/html/derbynet/replay.php

Here is what I changed:

```
if (isset($_SERVER['SERVER_NAME'])) {
  $server = $_SERVER['SERVER_NAME'];
} else if (isset($_SERVER['SERVER_ADDR'])) {
  $server = $_SERVER['SERVER_ADDR'];
} else if (isset($_SERVER['LOCAL_ADDR'])) {
  $server = $_SERVER['LOCAL_ADDR'];
} else if (isset($_SERVER['HTTP_HOST'])) {
  $server = $_SERVER['HTTP_HOST'];
```

Updated the above to:

```
if (isset($_SERVER['HTTP_HOST'])) {
  $server = $_SERVER['HTTP_HOST'];
} else if (isset($_SERVER['SERVER_ADDR'])) {
  $server = $_SERVER['SERVER_ADDR'];
} else if (isset($_SERVER['LOCAL_ADDR'])) {
  $server = $_SERVER['LOCAL_ADDR'];
} else if (isset($_SERVER['SERVER_NAME'])) {
  $server = $_SERVER['SERVER_NAME'];
```

**Comment by chunter2** [comment]
@Blackbird714 Just tried out your suggestion and it works on my Raspberry Pi install for both an IP and a hostname.

**Comment by jeffpiazza** [comment]
@Blackbird714 Thank you for your sleuthing!  That the "_" name comes from the nginx config makes perfect sense.
http://nginx.org/en/docs/http/server_names.html
