### ISSUE TITLE
Bug: Pack Standings view blank

### ISSUE THREAD

**Issue by joncamp** [jeffpiazza/derbynet#109]
All the den standings views propagated properly, albeit with the "In Pack" column blank. The Pack standings page is blank other than the headings. For our aggregate "grand finals" (top 3 from each category) there is nothing in the den or pack column.

![15793115819526833849402155169892](https://user-images.githubusercontent.com/11506084/72656489-61d90180-3950-11ea-8401-fcff7d2c4a45.jpg)

**Comment by jeffpiazza** [comment]
I'd appreciate getting a database snapshot (from the "About" page) if you're willing.

In multi-round, it's not really meaningful to talk about "pack standings;" you may be seeing something like that.  (It shouldn't be offered as a choice in that case, but a bug there wouldn't surprise me a lot.)

**Comment by joncamp** [comment]
I emailed a scrubbed copy of the database with PII removed.

**Comment by jeffpiazza** [comment]
Upon investigation, I think this affected only Grand Final situations.

**Comment by joncamp** [comment]
I tried the updated version, and the above change did make the pack standings display data. However, it now seems to display the same results as what was produced in the grand finals section. That seems rather surprising. I would expect it to be the pre-aggregate results. The problem is that our grand final included 21 racers out of the total ~45 that ran. 

One reason for the desire for overall pack standings (especially if pulled from the pre-aggregate) is to do things like find the "most fuel efficient" car (ie: slowest) out of the whole pack.
