### ISSUE TITLE
Feature Request: Pull Final Round from Subgroups

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#110]
OK, not sure what is going on in the background but we have a couple of small dens with 2 or 3 scouts so we can't really race by den and kind of need to use subgroups.  I have tested using the Pack as the racing group and then subgroups for each Den.  This works as expected and when creating a grand finals round I can selected the top 2 from each Den (subgroup).  However, I tried creating 3 race groups (Lions/Tigers, Wolves/Bears, and Webelos).  I can then race these as broader age groups and have a decent number of racers for each group.  However, when I try to create a grand finals round it gives me the option of selected the top racers Overall or by Racing Group rather than by Den (Subgroup).  Not sure why this is the case since results are tracked at the subgroup level.  It's not dire as I will probably just commingle the pack again this year as this adds some suspense to who is doing well / in line for a trophy in their den and lets us pit the various racers against each other.  Although, I was seriously considering trying to pair up the dens as an option.  Just wondering if this should be working or perhaps I did something incorrect along the way.

**Comment by joncamp** [comment]
I didn't use sub-groups, but we had a similar issue. Two dens had only one entry, and I had one parent submit a car. Based on that, I made a new "Open Class" den and moved the three of them into that "den". As such...I guess I'm not sure that sub-groups is the right way to solve the issue you are seeing. Maybe i did it wrong as well, and should have done some sort of aggregate. However, by making them a "den" it allowed me to pull the top 3 from each den.

**Comment by heatvent** [comment]
So I think that's the odd part.  When I had one "Group" (i.e. the default Den) which I labeled pack and then made Den subgroups, I was able to pull the winners from the subgroups.  Conversely, when I had 3 Groups (the 3 pairs of dens) but then put the appropriate dens under each Group, I was no longer able to pull from the subgroups and had to pull winners from the Group.  It's kind of like if you use multiple Groups, Subgroups get overridden.  This doesn't make sense to me because the whole idea of subgroups is to track standings at that level and the Group is just supposed to define who races against each other from a scheduling perspective.  At least that is my understanding, which very well could be flawed.

**Comment by jeffpiazza** [comment]
Thanks for this, this use case makes perfect sense.

**Comment by TheGlobalMind** [comment]
We also used subgroups in our derby setup due partially to the same issue, small dens with only a couple of scouts. Although our pack has, I believe, always run all dens as one big group.

We had 36 scouts registered to run, I set up subgroups as the "den" and I use groups as the two racing groups we actually have, a scout and an open division.

We don't generally pull a finals from any group. We just run the allotted heats and use the average time. We have a 5 lane track, and each car runs each lane once. I set up "dummy" cars to fill the spots we need to make sure it all rounds out. So we had 40 cars run, 40 heats. One round for scout division, and 20 cars including dummies for open.

What we had yesterday though was odd for us. A tie for 2nd. I attempted to create a new round to help decide this and I was going to run the top 5 but it seemed like creating a new round wanted me to still have them all run another 5 races. I didn't have an option for them to just run ONE race as the runoff.  Maybe the abbreviated option would help there - wasn't really sure at the time. but what we ended up doing is run

**Comment by heatvent** [comment]
Hi Jeff, just wondering if this is still in the works this year (still even possible).  I can get there semi-manually using sub-groups, but creating a "Grand Finals" round and only allowing one trophy only seem to work if I don't use subgroups (i.e. each Den is a Group vs. the Group being the Pack and each Den being a Sub-Group).

**Comment by jeffpiazza** [comment]
I'm hoping to get to this in the next month or so.  The UI is probably the bigger problem than the roster generation.

**Comment by jeffpiazza** [comment]
31dfc3a4c4077d18b84336c926981b0e534e714f now handles this.

(Playlist editing allows creating aggregate rounds by group, but doesn't (yet) support creating by subgroup -- probably have to address that discrepancy next.)
