### ISSUE TITLE
Server Becomes Unresponsive When We Open the replay.php page

### ISSUE THREAD

**Issue by jedidiahpedersen** [jeffpiazza/derbynet#116]
I installed a fresh system and when I went to the derbynet/replay.php page the server became unresponsive. From another computer the web pages load slowly or not at all.  When I leave the derbynet/replay.php page the issue stops and the system responds properly. 
[About DerbyNet.zip](https://github.com/jeffpiazza/derbynet/files/4092365/About.DerbyNet.zip)

**Comment by jeffpiazza** [comment]
The About page says you're running the server under Ubuntu on an x86_64 architecture.  I'm guessing you were running replay.php from the same browser as you took the About page from, a Mac separate from the server, is that right?

What does 'top' (on the server) say when this is going on?

Does the server recover if you leave replay.php, or is a reboot required?

**Comment by jedidiahpedersen** [comment]
I did run the about page from the same browser (Firefox) on a different
computer than I opened the replay.php page(both machines LUbuntu 19.04). I
also had the same issue occur when running the replay.php on a Chrome
browser.

Top:
top - 10:29:30 up  1:52,  2 users,  load average: 0.80, 0.21, 0.12
Tasks: 143 total,   1 running, 103 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.7 sy,  0.0 ni, 55.7 id, 43.5 wa,  0.0 hi,  0.0 si,
 0.0 st
KiB Mem :  8152684 total,  6769852 free,   454332 used,   928500 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used.  7452784 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND

 1054 root      20   0       0      0      0 I   1.3  0.0   0:17.85
kworker/0:0-eve
 1596 www-data  20   0  424184  18168  13092 S   0.7  0.2   0:00.69
php-fpm7.2
 1653 www-data  20   0  424036  16752  11832 S   0.3  0.2   0:00.71
php-fpm7.2
 2644 root      20   0   51196   4040   3424 R   0.3  0.0   0:00.20 top

    1 root      20   0  159520   8676   6588 S   0.0  0.1   0:01.93 systemd


The server does recover as soon as I leave the replay.php page.

**Comment by jeffpiazza** [comment]
43.5% wait state is very high.  How's your server's disk drive?

Anything unusual or interesting about your network environment?

Just to be sure there wasn't some new nginx/linux problem I missed, I just tried running a new project in a cloud VM, running Debian with a 4.9 kernel, and aiming my browser at it -- that seems to work fine.  So it's not a universal problem, at least, and there's presumably something about your particular environment that's leading to this.

**Comment by chunter2** [comment]
I also notice this with my Raspberry Pi 1 as the server.  I just tried connecting to the server remotely and went to the replay.php page.  My remote computer doesn't have a camera attached to it but the wa in top on the server goes from 0 to about 40.  I installed iotop on the server and here's the output.  Any idea what that page is writing to disk?  

`Total DISK READ :       0.00 B/s | Total DISK WRITE :     354.70 K/s`
`Actual DISK READ:       0.00 B/s | Actual DISK WRITE:    1000.33 K/s`
`  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND`
`16885 be/4 www-data    0.00 B/s  143.47 K/s  0.00 % 13.98 % php-fpm: pool www`
`   48 be/3 root        0.00 B/s    0.00 B/s  0.00 %  9.06 % [jbd2/mmcblk0p2-]`
`16794 be/4 www-data    0.00 B/s  115.58 K/s  0.00 %  3.74 % php-fpm: pool www`
`16886 be/4 www-data    0.00 B/s   95.65 K/s  0.00 %  3.30 % php-fpm: pool www`
`    1 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % init`
`    2 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [kthreadd]`

**Comment by jedidiahpedersen** [comment]
I used a brand new disk and I didn't think it should have troubles. I am
running tests on the disk now.

I had an old Seagate 7200.8 I was testing yesterday and it was causing some
slowdown when accessing the replay.php.  Given the age of the disk I
thought a new disk would have better throughput so I tried a new one I had.

**Comment by jedidiahpedersen** [comment]
I ran a full test with smartctl and the disk passes without errors. Using
dd I get a write speed of 2.1GB/s and a write speed of 6.3GB/s. To make
sure that it wasn't a computer issue I changed it over to newer hardware.
The wait state drops to 23% when I bring up the replay.php page but the
system is still unusable.

My kernel version is 5.3 Ubuntu 18.04.  What version of Debian are you
using. I may try that to see if it resolves the issue.

Thanks
Jed Pedersen

**Comment by chunter2** [comment]
Not sure if this helps but I see the following about 4 times a second in /var/log/nginx/access.log when I go to the replay.php page.  This is before I click the Proceed button.  

`xx.xx.xx.xx - - [22/Jan/2020:11:20:59 -0500] "POST /derbynet/action.php HTTP/1.1" 200 153 "https://xx.xx.xx.xx/derbynet/replay.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"`

I can't seem to figure out what else is being written to disk.

**Comment by jeffpiazza** [comment]
replay.php incorporates a 4-times-a-second polling loop, reporting its status and querying for a recently-ended heat. https://github.com/jeffpiazza/derbynet/blob/8cad2b4994ece980147dc92ce3a57f25d336f39c/website/replay.php#L84  For each message, the server records the time of last contact in the database;  normally the disk caching layer buffers the reads and writes so it's not necessary to wait for the actual disk latencies.

The polling could probably wait until clicking through "Proceed," but I wouldn't think it was worth the trouble.

Once the kiosk page loads, it also polls (occasionally to see if there's a new page to show), and the page itself (e.g. now-racing) likely polls for its own purposes.  I wouldn't expect any of this to put excessive load on the server.

I know I'm the one who brought up the wait state value in the first place, but I'm wondering if looking at disk performance isn't just a red herring.  Maybe running a simple benchmark on the sqlite database, e.g., from https://openbenchmarking.org/test/pts/sqlite, would help identify whether this is or isn't an issue.

**Comment by chunter2** [comment]
I think I may have found something else.  When on the replay.php page I notice a derbynet.sqlite3-journal file in my /var/lib/derbynet/2019/Test folder that shows up and then disappears over and over again.  I googled a bit and found this page.  

https://www.sqlite.org/pragma.html

The section below sounds interesting.  

PRAGMA schema.journal_mode;
PRAGMA schema.journal_mode = DELETE | TRUNCATE | PERSIST | MEMORY | WAL | OFF

The MEMORY journaling mode stores the rollback journal in volatile RAM. This saves disk I/O but at the expense of database safety and integrity. If the application using SQLite crashes in the middle of a transaction when the MEMORY journaling mode is set, then the database file will very likely go corrupt.

I'm not quite sure how to try this.

**Comment by jedidiahpedersen** [comment]
I ran the pts/sqlite and the results should be https://openbenchmarking.org/result/2001223-KH-DERBYNETT52

I tried using the same set of hardware I opened this bug concerning and installed a fresh copy of Debian 9.11 with lxde desktop and when I pull up the replay.php page from another computer the performance drops but not to an unusable state as was happening under Ubuntu 18.04. It still seams to have a lot of hard drive activity which is reducing the performance just noticably but I should be able to run a race.

**Comment by chunter2** [comment]
I was able to figure out how to set the sqlite journal to memory.  I added
`\$db->exec('PRAGMA journal_mode = memory;');` after the setAttribute line of the write-config-files.inc file like this.  

`<?php`
`\$db_connection_string = $exported_connection;`
`\$db = new PDO(\$db_connection_string, $exported_dbuser, $exported_dbpass,
               $exported_options);`

`\$db->setAttribute(PDO::ATTR_CASE, PDO::CASE_LOWER);`
`\$db->exec('PRAGMA journal_mode = memory;');`
`?>`

Now my iotop output looks much better.  

`Total DISK READ :       0.00 B/s | Total DISK WRITE :     117.03 K/s`
`Actual DISK READ:       0.00 B/s | Actual DISK WRITE:     131.65 K/s`
`  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND`
`20650 be/4 www-data    0.00 B/s   46.81 K/s  0.00 % 28.64 % php-fpm: pool www`
`20694 be/4 www-data    0.00 B/s   46.81 K/s  0.00 %  2.39 % php-fpm: pool www`
`20652 be/4 www-data    0.00 B/s   23.41 K/s  0.00 %  1.18 % php-fpm: pool www`

And the wa in top is about 5%.  

Not sure if setting the journal_mode to memory is the right solution though.

**Comment by chunter2** [comment]
With the help of this link
https://stackoverflow.com/questions/1711631/improve-insert-per-second-performance-of-sqlite
and adding
`\$db->exec('PRAGMA synchronous = off;');`
to the write-config-files.inc along with
`\$db->exec('PRAGMA journal_mode = memory;');`
from my previous post my wa is now down to zero when accessing the replay.php page.  I'll let someone else decide whether this is a valid solution.

**Comment by jeffpiazza** [comment]
Is this still an issue for anyone?  I think the polling rate is lower in v6.0, and I think the evidence still suggests something about the OP's particular environment is involved.

A web socket mechanism is clearly overdue; my main challenge there is keeping the deployment as close to one-click-easy as possible.

**Comment by jeffpiazza** [comment]
Closing this for now, having not heard anything further.
