### ISSUE TITLE
Presenting Awards buggy

### ISSUE THREAD

**Issue by mwaldropdatastax** [jeffpiazza/derbynet#117]
I'm doing some testing in prep for the race this weekend.  When I try to run the awards presentation I see very odd behavior.  For my server I am running build 982 on Raspian.  When I run the Present Awards screen in either Chrome or Safari on a Mac and I select an award from the list to display and see the following:  1) I briefly see the award I selected 2) automatically without me clicking I see a previous award displayed in the Present Awards screen on the right.  

My setup is Super-Group is "Pack", group label is "race class" (e.g. scouts, siblings, adults), and my subgroups is "Den".  This allows me to have the top 4 from each race class, and then the top 4 per den for the scouts.

So on the Present Awards screen, the first 4 entries are the top speeds for the Scouts.  So the Speed awards are "Fastest in Scout", "2and Fastest in Scout", etc.  Then below that is "Fastest in 4", "2and Fastest in 4", etc.  When I select "2and Fastest in 4", the the right side of the screen first shows "2and Fastest in 4", and then immediately updates to show "2and Fastest in Scout".

Not sure exactly what is going on here.

**Comment by jeffpiazza** [comment]
Any chance you have a second Present Awards page running at the same time?  Are you able to make changes in the database (say, to rename a den)?

Could you send along a (cleaned) database (from the About page), please?

**Comment by mwaldropdatastax** [comment]
I am able to modify dens and categories just fine.  I don't think there was any other present awards page running unless it's a zombie process or something.
[derbynet-20200119-051244.xml.zip](https://github.com/jeffpiazza/derbynet/files/4094426/derbynet-20200119-051244.xml.zip)

**Comment by mwaldropdatastax** [comment]
FYI, I created additional speed awards to work around the problem of removing overall winners from the den speed awards.  Not sure if that is confusing things at some level possibly.

**Comment by mwaldropdatastax** [comment]
i may have accidentally closed this - sorry

**Comment by jeffpiazza** [comment]
I'm able to reproduce this, and should get a fix in place later tonight.

**Comment by mwaldropdatastax** [comment]
So I did an apt-get update and restarted the server.  The behavior I now see is that when I select a den level award, at first I see the award, and then the right side of the screen updates and all I see is the "hidden" switch.  Do I need to do more than apt-get update to apply your fix ?  Do I need to re-install the entire package ?

**Comment by jeffpiazza** [comment]
Did you reload the browser page after installing?  That's the only thing I can think of.

**Comment by mwaldropdatastax** [comment]
I did reload the browser, cleared the cache, and tried both safari and chrome and got the same behavior.  So basically I'm trying to simply run derbynet in one browser (e.g. chrome) and have the other browser (e.g. safari) be the kiosk on the same laptop as a test.  Is that causing the weirdness maybe.  I will try later with another device to see if it acts differently.

**Comment by jeffpiazza** [comment]
Send a new cleaned database?

**Comment by mwaldropdatastax** [comment]
[derbynet-20200122-161112.xml.zip](https://github.com/jeffpiazza/derbynet/files/4098338/derbynet-20200122-161112.xml.zip)

I re-initialized the DB, re-imported racers and awards, ran simulated races for results, and now any award that is not the top 34 in the list exhibit the behavior on the Present Awards screen

**Comment by jeffpiazza** [comment]
Oh!  It looks like those are awards without recipients.  

I guess it should still be possible to present an award without recording the recipient in the database, but I hadn't really considered that case.  The treatment of these is admittedly not very consistent -- either they should work fully, or probably not be on the list of awards from which to choose.

If you visit the "Judging" page a pick a recipient for an award, it all works as expected.

**Comment by mwaldropdatastax** [comment]
Ah, user error.  Thanks for the quick help, I really appreciate it.

**Comment by mwaldropdatastax** [comment]
ok,  i went back and assigned the awards and still see the behavior.  It's very odd.  I even started with a fresh new database and re-imported everything from scratch.  I still see the same behavior after assigning all the awards to people.  It works fine for the first 4 awards (best in race class), but all the other awards either refresh to be a different award or a blank award.

**Comment by mwaldropdatastax** [comment]
Ah, just figured out it only happens on the automatically generated speed awards.  If I avoid those - it works fine.

**Comment by jeffpiazza** [comment]
Have you run heats that would determine speed award winners?  If so, could I see another database, please?
