### ISSUE TITLE
Unable to change replay settings

### ISSUE THREAD

**Issue by rpufky** [jeffpiazza/derbynet#118]
I installed on a clean debian system. We do not have a timer on our track, so all finishes will be manual entry. I'd like to have a replay shown on the projector that we'll have at the real race.

I'm currently working with dummy data and manually entering places while someone tips the camera, just so we can see the replay view change.

The default settings are duration 4s and times shown 2. I'm attempting to change these to duration 6s in order to have a better chance of capturing data about the actual finish line position of the cars in the race. In both test and the replay shown after manual position entry, I only receive a 4s replay.

To see if the settings were actually doing anything, I attempted to change the times shown to both 1 and 3. In both cases, it shows 2 replays.

I do not believe it is database settings, since other settings changes have been made successfully.

**Comment by jeffpiazza** [comment]
Apologies about this -- I meant to mention this in the release notes.

For web replay, the clip length and playback speeds are non-functional.
https://github.com/jeffpiazza/derbynet/blob/8cad2b4994ece980147dc92ce3a57f25d336f39c/website/replay.php#L74

That the number of replays doesn't work is an easily-fixed bug.
