### ISSUE TITLE
Inconsistent handling of DNF racers

### ISSUE THREAD

**Issue by mwaldropdatastax** [jeffpiazza/derbynet#120]
First of all, we ran our derby this weekend for the first time on DerbyNet.  Wow.  Race was much more efficient, everything was smooth, and the folks that have been doing this for a while were blown away with how much better things were.  Awesome day !

One small glitch.  We had one racer that we registered and checked in (we do it the night before the race) - but he didn't arrive to participate.  I had already made the schedule when I realized this, so we essentially had one racer that was in the schedule but did not race so we would just race an empty lane on the track for those heats.

Whenever I looked at the standings output, the empty lane heats showed as last place and there was an arbitrary high value in the fields for times, so that was perfect.  However, after the first round when we auto generated a finals round of the top 4 finishers, the racer that had all the DNF was included in the list for the final round.  So something is just a little inconsistent somewhere.

So, for one thing, I think I should have probably just done a manual adjustment to all the heats with the DNF lane and would have probably gotten better results.  But I suspect there might be something in the logic of picking the top finishers for the new round that could avoid this situation.

**Comment by jeffpiazza** [comment]
Could you share a (cleaned) database, to help reproduce?
Thanks!

**Comment by mwaldropdatastax** [comment]
Samuel Haublin is the racer.

On Sun, Jan 26, 2020 at 12:01 PM Jeff Piazza <notifications@github.com>
wrote:

> Could you share a (cleaned) database, to help reproduce?
> Thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jeffpiazza_derbynet_issues_120-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAIDOKFE5HFVB5AEI2BRHF5TQ7W6VHA5CNFSM4KLX6LMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJ5YTCY-23issuecomment-2D578521483&d=DwMCaQ&c=adz96Xi0w1RHqtPMowiL2g&r=kWPfbJxvmLcK5r-7fCNz3KQsWekISkP_1KrrCQlejEc&m=buO061s1gBj9Z3pQi4n_9PIIruwiawPuAWw05wXJ8pg&s=y9heu7-1-9Zn6FJwFudivPIVxEAh28kNHh2x3JQ07H0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIDOKFEIUGB7LB7KROO7OVDQ7W6VHANCNFSM4KLX6LMA&d=DwMCaQ&c=adz96Xi0w1RHqtPMowiL2g&r=kWPfbJxvmLcK5r-7fCNz3KQsWekISkP_1KrrCQlejEc&m=buO061s1gBj9Z3pQi4n_9PIIruwiawPuAWw05wXJ8pg&s=rjKJRgQDjMNLTGRoJJEfC4xkhteEH1TRyQtZRXEt5w0&e=>
> .
>


-- 

Michael Waldrop  |  Vanguard

mobile +1. 678.439.9179

michael.waldrop@datastax.com  |  datastax.com
<https://www.linkedin.com/company/datastax>
<https://www.facebook.com/datastax> <https://twitter.com/datastax>
[image: www.datastax.com] <http://www.datastax.com>

**Comment by mwaldropdatastax** [comment]
[derbynet-20200126-000657.xml.zip](https://github.com/jeffpiazza/derbynet/files/4114154/derbynet-20200126-000657.xml.zip)

**Comment by jeffpiazza** [comment]
I've debugged this down to being an issue with (I think) just NewBold timers, as the timer protocol doesn't specify which lanes had DNFs.

The fix probably belongs higher up, though, in the code that writes heat results -- any missing lane results should be inferred to be DNFs.

**Comment by mwaldropdatastax** [comment]
What was odd to me was that if you looked at any of the "standings" reports, the racers were properly at the bottom of the pack.  But when creating a new race round of the top 4 racers, these racers were selected.  So in my head - it seemed whatever queries were used for these two purposes where somehow differrent.

**Comment by jeffpiazza** [comment]
Yes, you're quite right, the query for building a new round didn't include a clause to filter out missing DNF results.
