### ISSUE TITLE
Aggregate Round and Speed Trophies

### ISSUE THREAD

**Issue by Blackbird714** [jeffpiazza/derbynet#125]
I ran a simulation of our upcoming race, and I noticed a problem/limitation in the options available for Awards Presentation.  Our Pack runs a big main round, then a Grand Finals round.  At the end, we present trophies for the fastest 3 racers in each Rank, then the top 3 racers for the Pack overall.  The twist for us perhaps, we don't award the same scout two trophies -- e.g. the Pack top racers are dropped from the top 3 of the Ranks for the awards.

During my simulation, the top 3 racers appear as expected, but those same 3 individuals appear as the top racers within their Ranks too.

Am I overlooking a setting or feature to prevent this?  Or is this a new feature request?

Do other Packs handle speed trophies differently?

**Comment by joncamp** [comment]
So we do trophies for pack 1st-3rd, then medals for den level 1st-3rd. The medals are cheap, so it makes sense that everyone in our grand final got a 1st, 2nd or 3rd medal.

**Comment by Blackbird714** [comment]
Makes sense; we're buying the same number of trophies in any case, I think the rationale here was to spread the awards around so that more Scouts can get a trophy.

I guess my option is to expand the awards field from 3 to 5, and manually adjust what is displayed/announced according to the Grand Finals results.  That is probably what we were doing with GPRM as well, now that I've thought about it more.

So I think this is more of an enhancement request.  The requested behavior is to have a toggle to allow only a single "Speed Trophy" per Scout across any defined rounds/ranks.

**Comment by jeffpiazza** [comment]
This basically duplicates #27.
