### ISSUE TITLE
Scrollbars showing in fullscreen kiosks

### ISSUE THREAD

**Issue by chunter2** [jeffpiazza/derbynet#127]
Horizontal and vertical scrollbars still show in fullscreen kiosk mode.  It's like the calculated screen size is a few pixels too big.  I initially thought the scroll bars were visible but disabled but scrolling actually moves the screen a little bit up and down and left and right.  If I change the following in fullscreen.php to 99% the scrollbars go away but there's a small boarder instead.  
`.full-window {`
`  position: absolute;`
`  top: 0;`
`  height: 100%;`
`  left: 0;`
`  width: 100%;`
`}`

There seems to be an overflow-x and overflow-y that can be set to hidden but I haven't figured out where to put that code.  

![scrollbar](https://user-images.githubusercontent.com/531129/73743710-31011680-471d-11ea-96f4-91ff40eadac5.jpg)

**Comment by jeffpiazza** [comment]
What browser/version/OS are you observing this in?

**Comment by chunter2** [comment]
This was with the latest version of Chrome and Firefox on the latest version of Windows 10 (1909).

**Comment by heatvent** [comment]
I had seen the same thing using full screen kiosk on the latest Chrome
version.  This was a few weeks back.

**Comment by jeffpiazza** [comment]
I'm not able to reproduce this with Chrome 79.0.3945.130 on a Win10 VM.

Any chance you have more than one screen going on, or something else that's unusual about the graphics environment?  Do you know what the actual dimensions of your screen are?

**Comment by jeffpiazza** [comment]
I assume this is fullscreen behavior you're describing?  Are there scroll bars present if using a normal window?

**Comment by chunter2** [comment]
I initially thought it was a multiple screen issue but I tested this morning on a single monitor system with the same results.  I think my laptop is 1366x768 or something like that.  

I just noticed something else.  When I click on "Be a Kiosk" instead of "Fullscreen Kiosk" I don't get scrollbars.  I can then hit F11 to go to full screen.  This is in Firefox.  If I click "Fullscreen Kiosk" I get what I think is part of the "Replay Kiosk" setup screen first.  I get the URL bar with the Proceed button.  When I click Proceed I get the scrollbars.  Hitting F11 to get out of fullscreen mode still leaves the scrollbars.  This may be why testing the replay kiosk always had scrollbars.

**Comment by jeffpiazza** [comment]
I'm able to reproduce this after all.  It looks like an issue with borders on the iframe.

**Comment by chunter2** [comment]
This is working great now.  Thanks for the fix.  

One question though.  Is there a reason the full screen kiosk brings up the URL box and a Proceed button but the Be a Kiosk doesn't?  

Thanks

**Comment by jeffpiazza** [comment]
Fullscreen mode from the browser requires a user gesture, like a click.  (I can't find where the standard says this, so it may just be that all browsers happen to require this.)  Showing the kiosk page itself has no such restriction.

**Comment by chunter2** [comment]
Makes sense.  Thanks for the info.
