### ISSUE TITLE
Awards Presentation Kiosk Confetti issue

### ISSUE THREAD

**Issue by chunter2** [jeffpiazza/derbynet#128]
Looks like the confetti check box is checked when initially choosing the awards presentation kiosk but the confetti animation doesn't work.  If I uncheck and then recheck the check box it starts to work.  My guess is the check box should be unchecked initially or something is not updating when the awards presentation kiosk is initially selected.  

I originally thought this was an issue with permissions on the confetti.webm file on my server but I think it was just a coincidence.  I've changed the permissions back to 644 and can reproduce the issue.

**Comment by jeffpiazza** [comment]
Thank you!  I'd noticed that hosted web sites didn't seem to have the confetti working, but had been thinking it was some kind of hosting/egress issue.  And as you noticed, if you flip the option off and then on, the symptom goes away!
