### ISSUE TITLE
Some races only include one car's finish timing when using FastTrack Model K3

### ISSUE THREAD

**Issue by timmattison** [jeffpiazza/derbynet#131]
I have a FastTrack Model K3. I'd say about 10% of the time when I run a test race I get only one timing value in the results window (image below). Many races run fine but this comes up sporadically. Have you seen it before?

Can I provide any logs to help debug it? I'm also a Java developer so I could work on a fix but didn't want to dig in if it is something that can be fixed without touching the code.

![2020-02-22_15-59-06](https://user-images.githubusercontent.com/300258/75099172-9150de80-558c-11ea-9ab9-992bf26e197a.png)

**Comment by jeffpiazza** [comment]
Do please post logs here.  (https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests)  I'm most curious about what was actually exchanged between the java program and the timer.

**Comment by timmattison** [comment]
OK, logs will be attached below. Here are some excerpts.

First, the log from the screenshot:

```
+15:55:10.731S          INT DRAINED: LR
+15:55:10.731S          INT DRAINED: *
+15:55:10.731S          --> RG
+15:55:10.738S          <-- RG0
+15:55:10.836S          --> LR
+15:55:10.843S          <-- A=1.6412! B=2.0090" C=2.160LR
+15:55:10.847S          <-- *
+15:55:10.882S          <-- 1# D=2.3088$ E=0.0000  F=0.0000
+15:55:10.882S          INT Unexpected transition: MARK >--RESULTS_RECEIVED--> IDLE
+15:55:10.882S          INT MARK >--RESULTS_RECEIVED--> IDLE
+15:55:10.883H                  --> message=FINISHED&roundid=1&heat=2&lane4=2.3088&place4=4&lane5=9.9999&lane6=9.9999
```

And a log that worked:

```
+15:55:21.088S          INT DRAINED: MG
+15:55:21.088S          INT DRAINED: ACME
+15:55:21.088S          INT DRAINED: *
+15:55:21.088S          --> MF
+15:55:21.094S          <-- MF
+15:55:21.097S          <-- *
+15:55:21.140S          INT DRAINED: MF
+15:55:21.140S          INT DRAINED: *
+15:55:21.607S          --> RG
+15:55:21.613S          <-- RG0
+15:55:22.137S          --> RG
+15:55:22.144S          <-- RG0
+15:55:22.663S          --> RG
+15:55:22.670S          <-- RG0
+15:55:23.202S          --> RG
+15:55:23.209S          <-- RG0
+15:55:23.737S          --> RG
+15:55:23.743S          <-- RG0
+15:55:24.262S          --> RG
+15:55:24.269S          <-- RG0
+15:55:24.787S          --> RG
+15:55:24.794S          <-- RG0
+15:55:25.315S          --> RG
+15:55:25.325S          <-- RG0
+15:55:25.849S          --> RG
+15:55:25.857S          <-- RG0
+15:55:26.380S          --> RG
+15:55:26.387S          <-- RG0
+15:55:26.912S          --> RG
+15:55:26.919S          <-- RG0
+15:55:27.446S          --> RG
+15:55:27.454S          <-- RG0
+15:55:27.979S          --> RG
+15:55:27.985S          <-- RG0
+15:55:28.516S          --> RG
+15:55:28.523S          <-- RG0
+15:55:29.045S          --> RG
+15:55:29.053S          <-- RG0
+15:55:29.579S          --> RG
+15:55:29.586S          <-- RG0
+15:55:29.774S          <-- A=0.5639! B=0.9308" C=1.1018# D=1.2702$ E=0.0000  F=0.0000
+15:55:29.775S          INT Unexpected transition: IDLE >--RESULTS_RECEIVED--> IDLE
+15:55:29.775H                  --> message=FINISHED&roundid=0&heat=0&lane1=0.5639&place1=1&lane2=0.9308&place2=2&lane3=1.1018&place3=3&lane4=1.2702&place4=4&lane5=9.9999&lane6=9.9999
+15:55:29.787S          INT IDLE >--PREPARE_HEAT_RECEIVED--> MARK
```

[timer-20200222-1548.log](https://github.com/jeffpiazza/derbynet/files/4241389/timer-20200222-1548.log)

**Comment by jeffpiazza** [comment]
Thanks for the logs, that helps a lot.

As you can see, there's occasionally some contention on the wire -- the timer jar sends a query or command, and the response comes back somewhere in the middle of the timer's report on lane times.  This screws up the timer jar's pattern matcher, with the result that it misses some of the lane times.

Normally, the timer jar keeps polling the timer waiting for the gate to be closed, and then to re-open to start the race.  The timer jar would then stop polling and wait for the heat result.  The polling is stopped specifically to avoid this contention issue with the Fast Track timers

In your case, the timer is reporting "gate open" (RG0) almost continuously, which leads to the timer jar continuing to poll indefinitely.  Are you using the laser start gate with your timer?  I'm guessing that might explain the difference in behavior.

An interim workaround would be to specify OlderFastTrackDevice, which doesn't poll the start gate but does recognize the same result messages.

**Comment by timmattison** [comment]
Ah yes, I see that when the laser start gate isn't aligned this happens much more often. With the gate aligned it appears to work as expected.

I see that the gate's LED display is immediately reset after each race so I can't see the winners if the laser is aligned. Is that something that's configurable?

**Comment by jeffpiazza** [comment]
Can you confirm that this is just an issue with your test set-up, as opposed to being something that happens when racing is underway?  In other words, would it be OK to close this, or do you think there's still something to be done here?

To your second question, I think you're describing issue #124.

**Comment by timmattison** [comment]
You can close this. It was my setup from what I can tell. Thanks!
