### ISSUE TITLE
ondeck.php reroutes Kiosk to login.php

### ISSUE THREAD

**Issue by Prindle19** [jeffpiazza/derbynet#137]
Just did a fresh install of Raspbian Buster (February 2020 2020-02-13) with all updates applied on both a Raspberry PI Zero W and a Raspberry Pi 3B. 

Installed derbynet-extras from the ppa (after update)

In both Chromium and Midori, everything seems to be working except sending the Kiosk to the On Deck screen. When I try this, the Kiosk goes to login.php. I can sometimes open up another browser window and manually go to ondeck.php but not consistently, most of the time it redirects to login.php and then I can't control the Kiosk from the Kiosk Dashboard. 

I see some errors in the nginx log: 

2020/03/04 10:40:42 [error] 667#667: *537826 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: permissions in /var/www/html/derbynet/kiosk.php on line 9" while reading response header from upstream, client: 192.168.0.6, server: _, request: "GET /derbynet/kiosk.php?address=Scout_Law HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "192.168.0.3"
2020/03/04 10:42:50 [error] 667#667: *537927 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: permissions in /var/www/html/derbynet/kiosk.php on line 9" while reading response header from upstream, client: 192.168.0.6, server: _, request: "GET /derbynet/kiosk.php?address=Scout_Law HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "192.168.0.3"
2020/03/04 10:52:18 [error] 667#667: *538333 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: permissions in /var/www/html/derbynet/kiosk.php on line 9" while reading response header from upstream, client: 192.168.0.6, server: _, request: "GET /derbynet/kiosk.php?address=Scout_Law HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "192.168.0.3"
2020/03/04 10:52:42 [error] 667#667: *538364 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: permissions in /var/www/html/derbynet/kiosk.php on line 9" while reading response header from upstream, client: 192.168.0.6, server: _, request: "GET /derbynet/kiosk.php?address=Scout_Law HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "192.168.0.3"
2020/03/04 10:54:01 [error] 667#667: *538448 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: permissions in /var/www/html/derbynet/kiosk.php on line 9" while reading response header from upstream, client: 192.168.0.6, server: _, request: "GET /derbynet/kiosk.php?address=Scout_Law HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "192.168.0.3"
2020/03/04 10:55:49 [error] 667#667: *538448 FastCGI sent in stderr: "PHP message: PHP Notice:  Only variables should be passed by reference in /var/www/html/derbynet/kiosks/standings.kiosk on line 32" while reading response header from upstream, client: 192.168.0.6, server: _, request: "GET /derbynet/kiosk.php?address=Scout_Law HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "192.168.0.3", referrer: "http://192.168.0.3/derbynet/kiosk.php?address=Scout_Law"

Here's what I see in access.log: 

92.168.0.6 - - [04/Mar/2020:11:06:27 -0500] "GET /derbynet/action.php?query=poll.kiosk&address=192.168.0.6%2B48440&_=1583337962644 HTTP/1.1" 200 146 "http://192.168.0.3/derbynet/kiosk.php" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Raspbian Chromium/78.0.3904.108 Chrome/78.0.3904.108 Safari/537.36"
192.168.0.6 - - [04/Mar/2020:11:06:28 -0500] "GET /derbynet/kiosk.php HTTP/1.1" 302 5 "http://192.168.0.3/derbynet/kiosk.php" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Raspbian Chromium/78.0.3904.108 Chrome/78.0.3904.108 Safari/537.36"
192.168.0.6 - - [04/Mar/2020:11:06:28 -0500] "GET /derbynet/login.php HTTP/1.1" 200 916 "http://192.168.0.3/derbynet/kiosk.php" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Raspbian Chromium/78.0.3904.108 Chrome/78.0.3904.108 Safari/537.36"
192.168.0.155 - - [04/Mar/2020:11:06:28 -0500] "GET /derbynet/action.php?query=poll.ondeck&since=2020-02-29+17%3A43%3A11&high_water_resultid=12&merge_rounds=1&_=1583337024119 HTTP/1.1" 200 506 "http://192.168.0.3/derbynet/ondeck.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"
192.168.0.197 - - [04/Mar/2020:11:06:29 -0500] "GET /derbynet/action.php?query=poll.kiosk.all&_=1583337958260 HTTP/1.1" 200 1031 "http://192.168.0.3/derbynet/kiosk-dashboard.php" "Mozilla/5.0 (Linux; Android 10; Pixel 3 XL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Mobile Safari/537.36"
192.168.0.155 - - [04/Mar/2020:11:06:31 -0500] "GET /derbynet/action.php?query=poll.ondeck&since=2020-02-29+17%3A43%3A11&high_water_resultid=12&merge_rounds=1&_=1583337024120 HTTP/1.1" 200 506 "http://192.168.0.3/derbynet/ondeck.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"

**Comment by jeffpiazza** [comment]
Yikes, I wonder how long that's been the case.

I'm not sure exactly what the proximate cause of this was, but it should be fixed now (build 1039).

**Comment by Prindle19** [comment]
Yep, that was it - just changed ondeck.php locally to confirm - thanks Jeff, this is amazing software, btw!! Pack 63 in Brielle, NJ will be using it from now on :)
