### ISSUE TITLE
Feature Request - Delay replay playback n seconds

### ISSUE THREAD

**Issue by chunter2** [jeffpiazza/derbynet#139]
I'd be nice to have the option to delay the replay playback some adjustable amount of time.  In my setup I had a projector running the replay kiosk set to now racing.  I had a second projector showing the racers on deck kiosk.  We had an announcer who would talk about the results and he ended up looking at the results from the racers on deck kiosk because the now racing was showing the replay.  The idea of this feature would be that the times and finishing places would show up on the now racing screen for a bit so the announcer could see and talk about them and then the replay would play.  This would just be a nice to have by the way.

**Comment by themarquee** [comment]
I second this, would be a nice option.

**Comment by N3RDAL3RT** [comment]
Jeff, just bumping this old Enhancement request. It would be really nice. As of now, it's a deal breaker for our Pack to not show the results on the big screen for at least a few seconds before the replay starts. Would be awesome to delay the replay for a few seconds, even better if that number of seconds is user configurable or within a range. Wish I knew how to code and add it. Thanks for all you do!!

**Comment by jeffpiazza** [comment]
Finally got around to implementing this.  Sorry it had slid off the radar.
