### ISSUE TITLE
Derby Timer support

### ISSUE THREAD

**Issue by jrowen** [jeffpiazza/derbynet#14]
Would it be possible to add support for Derby Timer?  The setting can be found [here](http://derbytimer.com/pages/grandprix-race-manager).  I've tried Grand Prix but am running into a problem with the software and was hoping Derby Net might be another option.

**Comment by jrowen** [comment]
Here's some log output from Grand Prix, showing the race commands and responses in action.

[derbytimer.txt](https://github.com/jeffpiazza/derbynet/files/769044/derbytimer.txt)

**Comment by wzjy47** [comment]
Hi, I have been unable to open any of the support documentation (.fodt extensions).  Any chance someone could point me in the right direction?  Thanks!

**Comment by jeffpiazza** [comment]
Use LibreOffice or OpenOffice to open .fodt documents.

Alternatively, pdf versions are available at https://jeffpiazza.org/derbynet/builds/docs/ <https://jeffpiazza.org/derbynet/builds/docs/>

/JEP

**Comment by wzjy47** [comment]
Thanks for the quick response!  The pdf link worked great...FYI, had tried OpenOffice previously and all of the documents were blank...Could just be user error...Thanks again!

**Comment by jeffpiazza** [comment]
Support for the Derby Timer device first appeared in v2.0, with at least Jonathan having had success with it.
