### ISSUE TITLE
printables use the wrong file path for imported database

### ISSUE THREAD

**Issue by kiowadriver** [jeffpiazza/derbynet#140]
For testing I was using the database, car photos, and racer photos I had from earlier this year. I can see racer and car photos fine on all of the pages.  The issue pops up when I attempt to print an artifact.  The path to the photos seem to be wrong.  I suspect this is related to the import of the database.  The process allows you to map the path to the photos during importing of the database but I suspect those new paths are not updated in the database.  I beleive the printables attempt to use the path in the database to the files instead of the path that was specified during the database import.  

I created a folder and it contains the following files:
/var/lib/derbynet/2020/test3/derbynet.sqlite3
/var/lib/derbynet/2020/test3/cars
/var/lib/derbynet/2020/test3/racers
/var/lib/derbynet/2020/test3/videos

I used the "advanced" button to map the cars, racers, and video folders.  All images show up on the web pages correctly after doing this.

When I attempt to create a drivers licnese for one of the kids I get an error and the log shows the code trying to go to the wrong path for the image file.
wrong path: /var/lib/derbynet/RacerPhotos//0-cropped/Some-Kid.jpg
correct path: /var/lib/derbynet/2020/test3/racers/0-cropped/Some-Kid.jpg

`Stack trace:
#0 /var/www/html/derbynet/fpdf/fpdf.php(1242): FPDF->Error()

#1 /var/www/html/derbynet/fpdf/fpdf.php(885): FPDF->_parsejpg()
#2 /var/www/html/derbynet/print/docs/racer/Awana-license/document.inc(44): FPDF->Image()
#3 /var/www/html/derbynet/print/inc/printable_racer_document.inc(50): AwanaDriversLicenseDocument->DrawOneAt()
#4 /var/www/html/derbynet/print/render/racer.inc(84): PrintableRacerDocument->DrawOne()
#5 /var/www/html/derbynet/print/render/racer.inc(93): draw_one_racer()
#6 /var/www/html/derbynet/render-document.php(76): require_once('/var/www/html/d...')

}
thrown in /var/www/html/derbynet/fpdf/fpdf.php on line 271" while reading response header from upstream, client: 192.168.1.164, server: _, request: "GET /render-document.php/racer/AwanaDriversLicenseDocument?options=%7B%22photo_size%22%3Atrue%2C%22use_photo%22%3Atrue%2C%22use_barcode%22%3Afalse%7D&ids=17 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "192.168.1.217:8050", referrer: "http://192.168.1.217:8050/print.php"
2020/04/25 08:46:44 [error] 12#12: *694 FastCGI sent in stderr: "PHP message: PHP Warning: getimagesize(**/var/lib/derbynet/RacerPhotos//0-cropped/Some-Kid.jpg)**: failed to open stream: No such file or directory in /var/www/html/derbynet/fpdf/fpdf.php on line 1240PHP message: PHP Fatal error: Uncaught Exception: FPDF error: Missing or incorrect image file: /var/lib/derbynet/RacerPhotos//0-cropped/Some-Kid.jpg in /var/www/html/derbynet/fpdf/fpdf.php:271
`

**Comment by jeffpiazza** [comment]
If I’m understanding this correctly, you exported a database snapshot from the About page, then imported that snapshot into a new database (in a Docker container).  If that’s the case, could you please export the new database, and attach both that export and the original export to the bug report.

Could you also confirm that you’re able to see a photo for at least one racer (say, on the Results by Racer page), but that generating a printable of just that racer gives an error?

**Comment by kiowadriver** [comment]
Jeff,

I think u may be mixing two separate issues:

Issue 1: the about page publishes phpinfo() which gives all sorts of
information about the server.  Specifically environment variables.  I out
in a pull to change about permission to logged in users only to protect the
data. This one is pretty straight forward.

Issue 2:. I copied a database and media folders to a new instance of the
server. I used the advanced feature to point to the location of the cars,
racers, and video folder.
The server works fine except for when u attempt to print anything. Instead
of use the new path to the images that the pages are using it looks to be
using old path data stored on the DB so it errors out.

**Comment by kiowadriver** [comment]
Yes, I can see the images of all the users as well as the cars without
issue. The paths seem to be wrong when printing.

**Comment by kiowadriver** [comment]
These captures are from my cell.  The desktop looks better but u will get
the idea.

**Comment by jeffpiazza** [comment]
Could you generate a database snapshot from the About page and attach it?
<img width="472" alt="image" src="https://user-images.githubusercontent.com/13140826/80293917-e1395680-8731-11ea-8261-ce9a2068a708.png">

**Comment by kiowadriver** [comment]
Ah, I got you now. I didn't even know that option was there.

**Comment by jeffpiazza** [comment]
Any update on this?  I'm probably going to have to close this if there's not more information about reproducing.

**Comment by kiowadriver** [comment]
Jeff,

The scouting has wound down a bit this year so I haven't been messing with
it. You can close it.

Curious, have you installed and played with this as a docker? I was able to
publish a docker version on dockerhub.
