### ISSUE TITLE
JS Error on Slideshow, Award Presentation and Standings Kiosks

### ISSUE THREAD

**Issue by zippy-man** [jeffpiazza/derbynet#143]
Slideshow, Awards and Standings kiosks are showing a `kiosk-poller.js:22 Uncaught ReferenceError: cancel_ajax_failure is not defined at Object.success (kiosk-poller.js:22)`

Eventually most of the kiosks with errors are reported as not responding and are removed from the kiosk dashboard or become unresponsive and cannot be changed to something else without manually refreshing the kiosk page

The cancel_ajax_failure appears to be related to commit [cbd5cba ](https://github.com/jeffpiazza/derbynet/commit/cbd5cbaaa535ae4cdb72fcba0f1b934bd0c24791)

Adding back `require_once('inc/ajax-failure.inc');` to kiosk-poller.inc seems to resolve the error

**Comment by jeffpiazza** [comment]
Thanks for the bug reports!

Several pages appear to be missing the inc/ajax-failure.inc include.  They should be symptomatic only when there's a server error (which you seem to be seeing a lot of).

I'm not sure what your reasoning is about cbd5cba, unless that's somehow the cause of the server errors.

**Comment by zippy-man** [comment]
Hmm not sure what happened to the links. The commit number was correct but the links were going somewhere else. I have updated the post with proper links.
