### ISSUE TITLE
Photos do not show after uploading

### ISSUE THREAD

**Issue by zippy-man** [jeffpiazza/derbynet#144]
After uploading racer or car photos they do not automatically show. If you press refresh they all will appear. It does seem after you have pressed refresh and upload photos a second time they will appear right away without pressing refresh.

**Comment by jeffpiazza** [comment]
Can you say a little more about what you did and what you observed?  Assuming you're talking about the "Drop files here to upload" field on the Racer Photos or Car Photos pages, a successful upload *should* show the uploaded photos, without having to refresh.
