### ISSUE TITLE
Standings kiosk does not display results

### ISSUE THREAD

**Issue by zippy-man** [jeffpiazza/derbynet#145]
The standings kiosk is blank and throws a 500 error. 

It appears to be related to the standings rework under commit [ae1a2ce](https://github.com/jeffpiazza/derbynet/commit/ae1a2ce6b9b9e8f7219a3398ac765c3e4918c0cc)

it seems `write_standings_table_headers()` and `write_standings_table_rows($result_summary)` were majorly changed in standings.inc but standings.kiosk was not updated.

**Comment by jeffpiazza** [comment]
Could you look in the error_log or php_errors logs for some details about the 500?

Also, could you please attach (or email) the About page, which will give a ton of details about your set-up?

**Comment by zippy-man** [comment]
It seems to affect the Windows and Linux versions. I have quickly downloaded the windows version again and ran a fresh setup. Same 500 error

`PHP Fatal error:  Uncaught Error: Call to undefined function write_standings_table_headers() in UniServerZ\\www\\kiosks\\standings.kiosk:31\nStack trace:\n#0 UniServerZ\\www\\kiosk.php(23): require()\n#1 {main}\n  thrown in UniServerZ\\www\\kiosks\\standings.kiosk on line 31, referer: http://localhost:81/kiosk.php`

[About DerbyNet.pdf](https://github.com/jeffpiazza/derbynet/files/5466479/About.DerbyNet.pdf)

**Comment by zippy-man** [comment]
While these commits seemed to have resolved the 500 errors the standings kiosks still do not function properly. The header row is created but the buttons on the kiosk dashboard no longer function to reveal results and the formatting seems to be wrong with the results table being mostly to the left side of the screen. Also the first column shows "Place" and shows both `inround` and `insuper` 

If I manually inspect the page in chrome and uncheck `.hidden { visibility: hidden; display: none; }` results will show. 

`handle_reveal_all() ` and `handle_reveal1()` in kiosk-dashboard.js seem to have no effect on the standings kiosk.

**Comment by jeffpiazza** [comment]
How embarrassing.  There were a lot of changes to the code for handling standings, and I completely forgot that the standings kiosk page included a good bit of code that wasn't used in the non-kiosk standings page.  (There also aren't any automated tests for the kiosk page.)  Net result is that this went out completely untested.  Apologies!

**Comment by zippy-man** [comment]
No need to apologize the project you have created here is amazing and I suspect has improved derbies for many packs across the country. That is an accomplishment to be very proud of in my book. I know our scouts love the new system and the now racing kiosk. I am excited to try out the new instant replay since we have to stream everything now. I just wanted to help bring up the bug and make you aware. Thanks for taking a look and thank you again for creating this open source project.
