### ISSUE TITLE
Lane masking for older K1 MicroWizard timer not working

### ISSUE THREAD

**Issue by frewenta** [jeffpiazza/derbynet#149]
Using an older K1 MicroWizard 4-lane timer (version 1.09D) on a 2-lane track - so need to mask 2 lanes out. 
I have selected 2 (out of 4) lanes for scheduling in settings (through localhost) for lane masking but find that does not achieve desired masking i.e.  although scheduling works, a heat will only complete if I manually activate the lane sensors for the masked out lanes.

I note in MicroWizard.java that reference is made to precisely this timer.  Further investigation with MicroWizard revealed that older timers needed a password to be inputted to load the lane masking feature. This works if I manually send the password through the serial port using MicroWizard's terminal app. I assume I would need to update code and rebuild from source here to effect the desired lane masking from within DerbyNet

**Comment by jeffpiazza** [comment]
I think the password is just needed once (ever), and not every time the feature's used.  Did MicroWizard tell you something different?

**Comment by frewenta** [comment]
> I think the password is just needed once (ever), and not every time the feature's used. Did MicroWizard tell you something different?

Sorry - I got it wrong - you are right the password is only needed once to enable the feature. My quick test after powering down the timer (with FUNterm.exe) only showed that the lane maskings don't persist (using FUNterm.exe) but a subsequent check reveals the password is not subsequently needed to mask lanes.

I just rechecked using DerbyNet and everything works flawlessly (via lane scheduling) - thanks for your help and the DerbyNet development itself !
