### ISSUE TITLE
Error message with webcam

### ISSUE THREAD

**Issue by jrowen** [jeffpiazza/derbynet#15]
I'm running into an error message when clicking on the check-in photo icon.  I think the error is due to the hosted site not being https.

![error](https://cloud.githubusercontent.com/assets/1530030/23142595/680338cc-f782-11e6-8ea7-afe3411346e4.png)

![console](https://cloud.githubusercontent.com/assets/1530030/23142653/b13f11a0-f782-11e6-9b67-2dd2076dd532.png)

**Comment by jrowen** [comment]
I think we could create a free SSL certificate from https://letsencrypt.org/.

**Comment by jeffpiazza** [comment]
The same URL should work with https — the just82.justhost.com <http://just82.justhost.com/> host already has a certificate.

Alternatively, you could try with a  less progressive browser, maybe — Chrome/Chromium might a little bit on the avant-garde side of things.

/JEP

**Comment by jrowen** [comment]
That worked just fine in Chrome.  Thanks!

**Comment by jeffpiazza** [comment]
https://jeffpiazza.org/derbynet/builds/docs/Webcams%20and%20Secure%20Contexts.pdf covers options for working around this problem.
