### ISSUE TITLE
Unplugging/Replugging the timer causes Web Server to stop recording results

### ISSUE THREAD

**Issue by themarquee** [jeffpiazza/derbynet#153]
I noticed with our Fast Track gate with DerbyNet version 6 that if we unplug the gate USB and reinsert it after starting the web server, the timer.jar still seems to be operating normally and receiving input from the gate, but the web app stops recording the results of the heat (in Racing mode and Test Simulation mode). If I plug in the gate to my USB, restart the timer.jar, the UniServer, and Apache, then it will work fine again.

**Comment by jeffpiazza** [comment]
I just tried reproducing here (also with a FastTrack timer, as it happens).

I think what you're observing is that, upon receipt of the malfunction message from derby-timer.jar, the server exits "Racing" mode (the switch on the race dashboard flips to "Not Racing").  On the "Now Racing" screen, you'd see a yellow "paused" symbol overlay, but if you're just looking at the dashboard, it's easy not to notice the change.  Flipping the "Racing" switch back on restores racing, no need to restart the server, etc.

Canceling racing mode is probably inappropriate upon a timer malfunction -- when the timer reconnects, it receives a heat-ready message again without the operator needing to intervene.
