### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by scottatchley** [jeffpiazza/derbynet#16]
Hi,

I am working on adding support for Microwizrd's Derbywizard K3 device. I usually write C code and I am more familiar with the GNU autotools and cmake. How do I build a working application that includes my K3Device.java?

Thanks,

Scott

**Comment by jeffpiazza** [comment]
The build.xml file(s) are for use with Apache ant: http://ant.apache.org.  Follow the instructions for installing ant, and then just:

ant

to build a full distribution.

(Sorry this has languished so long - I somehow didn't notice it back in April.)
