### ISSUE TITLE
Can't edit or make dens (partitions)

### ISSUE THREAD

**Issue by jaeaton** [jeffpiazza/derbynet#164]
Can't edit or make dens. When there are no defined partitions, on the check-in page when adding a racer, selecting (Edit partitions) does nothing. When a partition is defined (IE Fake Roster) is used it can be selected and used.

Browsers: Edge and Vivaldi

DerbyNet-v7.0-1393-20211203.win

**Comment by jeffpiazza** [comment]
Thanks for reporting this!

Looking more closely, there are several bugs here relating to creating the first partition, creating the first racer via the check-in page, and editing or adding racers via the check-in page generally.  Clearly I need better testing for javascript code.
