### ISSUE TITLE
Feature Request: allow informational slides in the slide shows

### ISSUE THREAD

**Issue by tfrazee** [jeffpiazza/derbynet#167]
Before derbynet we used PowerPoint to create the slideshow to play in between races or before/after. In amongst the photos of cars we would have informational slides with funny scout-related memes, the menu for the concession stand, the next 2 months of activities, etc.

I'm not sure if it would be possible to have a photo of a car be the informational slide (screenshot of a past PowerPoint slide?) or if the car is not checked in, does it appear in the slideshow?

Perhaps a directory full of the pictures of the information you want to display that the slideshow system randomly insert every X amount of car slides. This informational slide would not have any overlays that the car photo slideshow mode would.

**Comment by jeffpiazza** [comment]
This has been supported for a while, but I somehow never got around to closing the issue.
