### ISSUE TITLE
Feature request: support for remote start gate release

### ISSUE THREAD

**Issue by thale13** [jeffpiazza/derbynet#17]
I just wanted to comment that this stuff is really cool.  I have an older FastTrack timer and the java app works great with it.  I added some code to the Race Coordinators dashboard to send a signal to a RaspPi wired to a solenoid start gate to programmatically release it when you push the button.  It's a REALLY bad hack that, so far at least, works.  

I used websockets and wrote a Perl server to connect to on the RaspPi.  I think a better way would be to incorporate it more along the lines of the Timer or MacReplay where there is a status so you can see the connection and the release actually comes from the server rather than the web browser, I just don't (haven't found yet) know where or how to add that yet.

Again, just saying that this is really cool software.

**Comment by jeffpiazza** [comment]
Rephrased the issue title.

I'd love to hear from others with a similar need.  What sort of remote gate release are you using?  Do you have an automated a "launch sequence" of some kind, or do you just want to open the gate from across the room?

**Comment by thale13** [comment]
I am building a custom remote gate release using a car door lock actuator to pull the start gate lever.  Mainly I am doing because its cool and I can, but also because it can dovetail into a 'christmas tree' light set and add a little more race feeling.  Also, it prevents arguments by the kids on who pulls the gate.

**Comment by Ronald-Diemicke** [comment]
@thale13 - do you have the code you wrote stored somewhere that I might be able to get access to? We've got an event next weekend and I'm trying to see what we'll need to do to fully use DebyNet and get away from Grand Prix.

**Comment by thale13** [comment]
I will e-mail it to you this evening.  It is an additional .js file, a
button added to the Race Coordinator page, and a Python script for a
Raspberry Pi.  You also need the solenoid connected to the Pi.  I don't
know of a way to drive it otherwise.

I did have it connect to GPRM at one time for testing before I found
Derbynet but the solenoid wasn't that good and it didn't work.

Tom

**Comment by Ronald-Diemicke** [comment]
@thale13 - Awesome. Thank you. You should be able to find my email address in my profile.

**Comment by jeffpiazza** [comment]
The DerbyMagic (derbymagic.com) solenoid start integrates with their timer; the timer supports a command to start the race.  Something like that would be relatively easy to support, because the communication path between the timer and web server is already established.

For other systems, I can imagine handling similar to the timer and replay interfaces, especially if the starter is controlled by a Pi or something similar that can interact directly with the web server.

I'd be interested in seeing the javascript you mentioned in the comment above.

**Comment by jeffpiazza** [comment]
The PDT timer (née MiscJunk, now at https://www.dfgtec.com/pdt) also accepts a command to trigger a solenoid start gate.

**Comment by mashcraft** [comment]
@jeffpiazza I was just looking at issues and was going to mention that PDT timer supports a starting gate solenoid but you beat me to it.   

It would be great if I could trigger the start gate from the racing screen.   

For timers that don't support a starting gate, you could support a "Starter" device that logs into DerbyNet over HTTP similar to timer.js or a kiosk.  A Raspberry Pi setup like @thale13 mentions above could easily login to the web interface and accept commands.

**Comment by TheGlobalMind** [comment]
Late to the party here but we have an older FastTrack P series timer as well, works well with derby-timer, and the way we release the start is a set of two buttons which are manually pushed (think Jeopardy signaling buttons).   We have a scout at the start line (usually from the troop) who helps stage the cars on the line. They push the button on their controller, which is the "ready" button. We then have a second controller at the finish line which one of the racing scouts pushes - gives them some interaction in the process. 

Once a race is finished, the gate is reset and that also resets the timer.  All of this was done ages ago so I am now just working on it with this package to make sure it all functions as we expect. The old system was DerbyMaster.

I can definitely see where some might want to remote trigger via the web app.

**Comment by jeffpiazza** [comment]
Here's my thinking on the way forward on this; I'd be interested in any opinions:

Some timers (DerbyMagic and PDT, at least) provide for a remote start gate release from the timer itself.  

There are potentially other start gates that can be remotely operated, but by some communication channel not related to the timer.  I'm thinking here especially about home-grown microcontrollers driving an electric solenoid on the start gate.  For these cases, I want to be sure it's possible for a second client to communicate with the server using the timer message protocol, while making clear that that second client doesn't interact with the timer, but rather only implements the start gate release part of the protocol.  (See e.g. https://jeffpiazza.github.io/lighttree/, which has a Pi Zero controlling a starting light sequence before activating the start gate solenoid; that same Pi Zero could run a gate-only client.)

The timer message protocol would be updated as follows (https://jeffpiazza.org/derbynet/builds/docs/Developers-%20Timer%20Messages.pdf):

message=HEARTBEAT & release=NO:
(or no release parameter): As now, just a timer, without support for remote release.

message=HEARTBEAT & release=YES:
Combination timer and start-gate poll.

message=HEARTBEAT & release=ONLY:
Heartbeat message sent from a client that ONLY controls the start gate.

The server needs to keep track of two separate client heartbeat streams, possibly from the same client, to track whether the timer is connected, and to keep track of whether there's a remote release available.

**Comment by jeffpiazza** [comment]
I have an initial implementation ready for anyone who'd like to volunteer to test with DerbyMagic and MiscJunk/dfgtec PDT timers.

(1) Download the derby-timer.jar from here:
https://jeffpiazza.org/derbynet/private/issue17/derby-timer.jar

(2) Visit:
https://xhosting.jeffpiazza.org/derbynet/2020/xx/remote-start
(default passwords) and look at the race dashboard to confirm that there isn't another time connected.

(3) Launch the timer jar and point it to the same server: https://xhosting.jeffpiazza.org/derbynet/2020/xx/remote-start

(4) Visit the race coordinator page, and see the new green "Start Race" button.  Click same, and your start gate should trigger.

I'll commit the code changes as soon as someone can tell me it works for them (and what kind of timer they're using).

**Comment by jeffpiazza** [comment]
I guess no real harm if I commit this untested, but I'm still hopeful that someone here will confirm that this works for at least one case.

**Comment by mashcraft** [comment]
Jeff,

Had a lot of company this weekend. I’ll try to test early this week.
Don’t let me hold you up though.

Thanks,

Mike
