### ISSUE TITLE
derby-timer.jar

### ISSUE THREAD

**Issue by jaeaton** [jeffpiazza/derbynet#170]
With server configured to use SSL and a self-signed certificate the following errors ares encountered:
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException" unable to find valid certification path to requested target
java.security.cert.CertificateException: No subject alternative names present

**Comment by jeffpiazza** [comment]
How was the self-signed certificate generated?  (From the UniServerZ controller on Windows?)

If the server will (also) accept plain http requests, then just dropping the "https://" prefix from the server's address in derby-timer.jar should get you connected.  (You probably know this.)

If you want or need to use the secure connection, then the server's certificate (or perhaps its self-signed certificate authority certificate) needs to be imported into the Java keystore.  I've not personally had occasion to do that before, but the process is presumably something like what's described in https://malalanayake.wordpress.com/2017/01/14/how-to-make-the-java-runtime-to-trust-the-certificate-present-by-the-host/.

**Comment by jeffpiazza** [comment]
I'm going to close this, as it's not so much a bug as a challenge in using SSL and self-signed certs.

**Comment by jaeaton** [comment]
The Certificate was generated by UniServerZ.

I may change my setup so I can access both https and http.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
