### ISSUE TITLE
Racing with fake timer resets lane count to 6

### ISSUE THREAD

**Issue by nsxfreddy** [jeffpiazza/derbynet#171]
Our track has 4 lanes, so I'm trying to simulate the race without the hardware since it is in storage. Whenever I use the fake timer it resets the lane count to 6.

Using derbynet-server revision 1428 on Raspbian via Chrome on Windows 11.

**Comment by jeffpiazza** [comment]
I'm not sure if there's a trick to reproducing this, but just trying naively, I'm not able to reproduce the behavior you describe.

The fake timer page should be populating the "number of lanes on the track" control from the currently-recorded value.

Could you try opening the Set-Up > Settings page, confirming you have 4 lanes set, and then seeing if it still behaves as you describe?

**Comment by nsxfreddy** [comment]
Okay I just reproduced this again. Here are the steps I followed:

1) Re-initialize database.
2) From Settings, set track lanes to 4.
3) From Settings, create fake roster with default settings.
4) From Settings, verify track lanes is still 4.
5) From Race Dashboard, choose "Lion" den, and "Schedule + Race". The Race Dashboard shows 4 lanes.
6) From Race Dashboard, click Timer Status -> Test. The Timer Testing page shows 4 lanes.
7) From Timer Testing page, click "Fake Timer". The Fake Timer popup shows 4 lanes.
8) From Timer Testing page, click "Back". The Race Dashboard page shows 6 lanes.
9) Settings now shows 6 lanes.

I also verified this by opening a separate tab to settings and refreshing after each above step. The lanes changes to 6 specifically when I open the Fake Timer page.

Hope that helps!

**Comment by jeffpiazza** [comment]
Sure enough, exactly as you said.  Easily found with reproduction.  Thanks!
