### ISSUE TITLE
Docker image ODBC driver

### ISSUE THREAD

**Issue by cjr222** [jeffpiazza/derbynet#174]
Your software is incredible! I am running from the docker image and am trying to share a database with GPRM but in advanced database setup it says ODBC driver not loaded. Did I miss a step or does the driver  need to be added to the docker image?

**Comment by jeffpiazza** [comment]
Hmm, seems to work if php-odbc is included as a separate apt install.

Tentatively marking closed, let me know if you still see issues.

**Comment by cjr222** [comment]
No more driver missing error. We'll test the ODBC connection. Thank you!
