### ISSUE TITLE
Starker differentiation between race group colors

### ISSUE THREAD

**Issue by nirvdrum** [jeffpiazza/derbynet#177]
This may be a limitation of my laptop screen or related to my power settings, but I'm finding it very difficult to tell the difference between the colors for "den", "group", and "subgroup" on the racing groups page:

<img src="https://user-images.githubusercontent.com/12584/150907279-d6d484f7-2857-46e4-ac5b-a8064a40b42f.png" width="50%" height="50%" />

I think there may be an accessibility issue there as well. Choosing three colors that are dissimilar would be very helpful. I can try to pull together a PR for that, but I didn't want to mess with the color scheme without opening an issue to discuss first.

**Comment by jeffpiazza** [comment]
I don't really need a PR, but perhaps you could post some swatches?

Color (and taste) are subjective, of course, but I don't disagree these are a little too subtle.

**Comment by nirvdrum** [comment]
Thanks for the fix on this. I started trying to evaluate different color options, but I'm not a graphic designer. I was trying to find something that would provide good contrast while fitting in with the rest of the app theme. Your new colors are much easier differentiate. Thanks for taking care of that.
