### ISSUE TITLE
Group names are truncated on initial creation

### ISSUE THREAD

**Issue by nirvdrum** [jeffpiazza/derbynet#178]
It looks like new group creation truncates the group name to 15 characters. I added a new group called "Parents / Siblings" and this is what it looks like:

<img src="https://user-images.githubusercontent.com/12584/150907544-5eab0462-0373-4190-bff3-1757ca57f3c3.png" width="50%" height="50%" />

It's not a display issue. When I go to edit the group name, the value is the truncated value. However, from the edit screen, I can put the full name in and that won't be truncated:

<img src="https://user-images.githubusercontent.com/12584/150907750-c965adae-ded0-4e9c-91ba-111e81405e08.png" width="50%" height="50%" />

Editing the group name after the fact is not much of a problem, but I'd imagine the intention is for both the new and edit forms to apply the same naming rules.

**Comment by jeffpiazza** [comment]
DerbyNet's origins trace back to piggybacking on ODBC databases defined by a commercial product, and the strict name limits were for compatibility with those databases.  I think I agree it's time to move past that.  (Attaching to an external ODBC database will still work, but defining class and rank names through DerbyNet might give unexpected results.  I don't think that's a use case to worry about, though.)
