### ISSUE TITLE
Utilize subgroups for awards, standings, and grand finale

### ISSUE THREAD

**Issue by thale13** [jeffpiazza/derbynet#18]
How hard would it be to do the speed awards (default awards) and standing displays by subgroup?  We raced today with all the Scouts in one group with subgroups and really liked the way the race went.  The few issues revolve around awards.  Being able to display the awards for each Den individually would be awesome.  As would the Grand Finale taking subgroups into account.

We worked around it were very pleased with the software overall.  I'm just wondering if this is easy or not.  I tried figuring it out tonight but since I don't program and don't know JavaScript or PHP, its a little difficult.

**Comment by jeffpiazza** [comment]
v3.0, released yesterday, includes support for:
 - Showing standings by subgroup
 - Awarding speed trophies by subgroup
 - Presenting awards by subgroup

If you have only one group (which seems to be the case for you, and I suspect is most of the use case for subgroups), you can form a run-off round by setting a second round for the single group, and choosing to take the top N from each subgroup.  That feature was already present in v2.0.

Still missing from v3.0 is the ability to edit the list of subgroups.  That means that, for now, you can create subgroups only by importing a roster, and the subgroups will be ordered according to their appearance in the imported roster.

I'm going to close this issue, but if there are aspects to this that I've missed, please let me know.

Also, if anyone has a use case involving subgroups with more than one group, I'd love to hear about it!
