### ISSUE TITLE
QR code for voting link

### ISSUE THREAD

**Issue by jaeaton** [jeffpiazza/derbynet#184]
Generate a QR code to direct users to voting. Display on kiosk page.

**Comment by jeffpiazza** [comment]
What a great idea.  Coming soon to a derby near you!

**Comment by jaeaton** [comment]
Works in 1473

**Comment by jeffpiazza** [comment]
I'm not entirely happy with the result -- there's no real provision for configuring a kiosk page before displaying it, and this page really highlights that as a deficiency.

**Comment by jpetrykanyn** [comment]
The title and QR look perfect, thanks for setting this up.
