### ISSUE TITLE
Aggregate groups all share the same trophy settings

### ISSUE THREAD

**Issue by nirvdrum** [jeffpiazza/derbynet#189]
The aggregate group settings allow specifying the number of speed trophies for the group. Based on the UI, I would have expected each group to be individually configurable.

<img src="https://user-images.githubusercontent.com/12584/153677816-836d20a2-1ef5-40ff-97a0-cd3586224eed.png" width="30%" height="30%" />

However, updating the setting for one group updates the setting for all aggregate groups. I can't tell if this is intentional or a bug. If the latter, I can try debugging it and see what's going on.

**Comment by jeffpiazza** [comment]
This was a UI issue, although admittedly confusing.
