### ISSUE TITLE
Documentation on the replay stuff

### ISSUE THREAD

**Issue by thale13** [jeffpiazza/derbynet#19]
I think the macreplay is great.  Everyone loved it today.  I'd be willing to play with a Raspberry PI camera interface or a Linux version, but would need to understand the architecture and the IPC that occurs.  Any docs you can provide?

**Comment by jeffpiazza** [comment]
I don't have anything written at the moment, but will take up the issue in a few weeks.

In the meantime, the broad strokes are:

- Replay polls the server by sending HTTP POSTs with action=replay-message and status=2 (ok) or 3 (trouble/malfunction).  This normally happens several times per second.  (If the server doesn't get a poll message for two seconds, it will report to the user that the replay connection has been lost.)

- The server's response carries an XML document with zero or more <replay-message> elements.
Each replay-message element contains a simple text command with arguments.
E.g.,

testing/action.sh localhost/derbynet "action=replay-message&state=2"

      post action.php action=replay-message&state=2
<?xml version="1.0" encoding="UTF-8"?>
<action-response action="replay-message" state="2">
  <replay-message>HELLO</replay-message>
  <success/>
</action-response>

The possible <replay-message> elements are:

- "HELLO" is the server's response to a first connection.
- "TEST <skipback_seconds> <repeat> <rate>" runs the replay test 
- "START video_name_root" starts a recording video (video_name_root is a suggested file name stem)
- "REPLAY skipback showings rate"  stops recording if recording and plays back
- "CANCEL" cancels (abandons) the current recording

**Comment by alwilson** [comment]
What exactly does the macreplay program do? I saw a blurb in the documentation and it sounded like it might send the recordings back to the server, but this sounds more like the server indicating when to start/stop recording on another device. Maybe I'll whip something up with python and ffmpeg to talk to the server and play the recordings.

I'm excited about running DerbyNet soon, thanks for all the hard work you've put into this project!

**Comment by barbequesauce** [comment]
Also interested in seeing this - in tinkering with a Champ timer and BestTrack / GPRM setup, trying to add in instant replay with my RPi. This sound like it may be the ticket if the replay option is hackable...

**Comment by jeffpiazza** [comment]
A first draft of the description of the Replay protocol is now up at http://jeffpiazza.org/derbynet/builds/docs.php.

**Comment by barbequesauce** [comment]
@alwilson, have you made any progress on your python version?
