### ISSUE TITLE
FastTrack K with unsupported gate check command

### ISSUE THREAD

**Issue by kmspade** [jeffpiazza/derbynet#193]
Hello, 
I am having issues with my derby timer recording times in the DerbyNet software. I am trying to determine if it is a hardware or software issue. I am attaching a log file for someone to review. In this log file, the software recorded the first heat correctly, but did not record the second heat. 

I am using a microwizard K-2 timer. I have replaced the start switch, phone cord that runs to the finish gate, the serial cable, serial to usb adapter, and AC adapter. So I am down to a problem with either the finish gate or this timer.

[timer-20220215-0026-48.log](https://github.com/jeffpiazza/derbynet/files/8064815/timer-20220215-0026-48.log)

I am using the derby-timer.jar option since that is what worked for me last year. I have tried the timer option in the Derby Net software, but have had issues getting the timer recognized. Also last year I was using version 5 or 6 I think, but am using version 7 now. I'm using Edge for the browser. 

When the software stops recording times it seems the only solution to get up and running again is to unplug the timer, close derby-timer.jar, restart it and plug the timer back in. 

I downloaded the FUNterm program from the microwizard website and recorded several "heats" without issues.

[FUNterm log](https://github.com/jeffpiazza/derbynet/files/8064891/FUNterm.log)

I noticed that the FUNterm log is much shorter than the DerbyNet log. The DerbyNet log seems to be recording random characters every few milliseconds, and the FUNterm log does not. The tech at microwizard says their timers do not send "heartbeat" messages out. 
The conclusions I have drawn so far are that it may be a software issue due to the difference in the log files, or it may be a hardware issue with the finish gate, since inplugging it and restarting the java timer will get it working again, if only briefly.

I'd like someone to look at the log files and try to confirm it is either a hardware or software issue. 

Thanks in advance for any help!

**Comment by jeffpiazza** [comment]
From the log it looks like it's a FastTrack timer that's configured without support for the "RG" command, which is the command to interrogate the start switch state.  I'm not sure how this would have worked any differently for you in the past.

You could probably treat this as a P-series timer, despite it being a K2.  You have to click the entry for P-series by hand.

If you'd like to investigate a little further, could you please send a client-side log file (which would normally be more complete than that received by the server)?  derby-timer.jar's "File" menu can show you where they're found.

Normally for K-series timers, DerbyNet polls for the start-gate state except when a heat is actually running.  This provides a little more information back to the server, but doing without is not a huge sacrifice.  P-series timers aren't capable of reporting the starting gate state, so there wouldn't be any polling for it.

**Comment by jeffpiazza** [comment]
For a fee, the option to report starting gate state enabled in the field.  Check with the MicroWizard folks if you're interested.

**Comment by jeffpiazza** [comment]
ae9e30f0d89febb2637ba8829f93f369f140d56c incorporated a change to recognize the response for an unsupported "RG" option and stop trying to poll the gate.  I think that is likely to fix this issue, but I don't have a way to test or reproduce.
