### ISSUE TITLE
Simulated Racing not obvious

### ISSUE THREAD

**Issue by nirvdrum** [jeffpiazza/derbynet#194]
We just ran our derby over the weekend and I needed to run the DerbyNet Timer server to connect to the track timer. That worked fine and DerbyNet showed that the track was connected, but the test option didn't show any lane data after a test run. We tried it four or five times before we decided to just run the first heat and see how things went. Results from the heat were properly recorded. We did need to reverse lanes so I went back to the test screen, clicked the checkbox there to reverse lanes and that option worked fine. All in all, not a big deal.

Unfortunately, the track is no longer set up, so I can't easily test anything. But, if you do have something you'd like for me to try, please let me know and I can try to meet up with the guy storing the track.

**Comment by jeffpiazza** [comment]
Did you turn on "Simulated Racing?"  If not, the Timer Test page probably wouldn't appear to respond to any test runs.  

That part of the UI probably needs some work to avoid inviting confusion.

**Comment by nirvdrum** [comment]
Ahh, no I don't believe I had.

**Comment by jeffpiazza** [comment]
v8.0 includes some big red banners pointing out when neither racing nor simulated racing is in effect.

**Comment by rpyne** [comment]
It is not obvious how to turn on simulated racing. I've been hunting for it for two days.
