### ISSUE TITLE
Submit button unreachable on Configure dialog

### ISSUE THREAD

**Issue by jasonmuzzy** [jeffpiazza/derbynet#2]
On a widescreen resolution the dialog for the configure box extends past the bottom of the screen but there are no scroll bars to scroll down to it.  Used F11 fullscreen to reach Submit button as work-around but unable to reach Cancel button.
![image](https://cloud.githubusercontent.com/assets/15488120/10860634/573da596-7f28-11e5-8a5c-74fb2cf0ccac.png)

**Comment by jeffpiazza** [comment]
Thanks so very much for these great bug reports!

I’ll try to have an update for you soon.

/JEP

**Comment by jeffpiazza** [comment]
Tightened up vertical spacing for the database set-up dialog.  Revised format in revision 359 and later.
