### ISSUE TITLE
Can't install on Raspbian Jessie or Stretch

### ISSUE THREAD

**Issue by thale13** [jeffpiazza/derbynet#20]
So I downloaded the new .deb and have been trying to install it for 2 days.  Even completely reloaded stretch on the sd card.  Whenever I try to install it I get:

pi@derbynet:~ $ sudo dpkg -i ./derbynet_v3.0-664-20171231.deb
dpkg-deb: error: archive is format version 3.0; get a newer dpkg-deb
dpkg: error processing archive ./derbynet_v3.0-664-20171231.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 ./derbynet_v3.0-664-20171231.deb

Any ideas?  I can't find anything like this googling at all.

**Comment by jeffpiazza** [comment]
Ack!  In my haste to release v3.0, I didn't confirm that the deb file actually installs, and didn't notice that I'd updated one too many version numbers.

Build 665, now available, fixes this.
