### ISSUE TITLE
BestTrack Champ won't display results until timeout

### ISSUE THREAD

**Issue by dagentooboy** [jeffpiazza/derbynet#200]
The timer works great if I use the web interface timer but if I use the .jar on the server or a remote machine it never gets the results. It just waits for the timeout and then sometimes it gets the results. If I use the web interface it gets the results as soon as the last racer passes through the timer. Is there some option I am missing on the .jar timer utility?

**Comment by jeffpiazza** [comment]
derby-timer.jar produces a client-side log that's quite detailed.  The "File" menu in the derby-timer.jar GUI can show you the directory the timer log is written to.  You can attach it here and I'm happy to have a look.

**Comment by dagentooboy** [comment]
[timer-20220305-1518.log](https://github.com/jeffpiazza/derbynet/files/8191496/timer-20220305-1518.log)

**Comment by dagentooboy** [comment]
[timer-20220305-1529-36.log](https://github.com/jeffpiazza/derbynet/files/8191507/timer-20220305-1529-36.log)
And here is the log of it working on the web version of the timer

**Comment by jeffpiazza** [comment]
Thank you for these, they're very helpful.  The logs seem to show equivalent commands being sent to the timer, but the timer behaving differently.  I'm guessing this implies either some kind of timing issue, or possibly something relating to the carriage return that the Champ timer needs in order to recognize a command.

If you're inclined, running derby-timer.jar with the -legacy command line argument might or might not give a different result.

**Comment by dagentooboy** [comment]
[timer-20220305-2116.log](https://github.com/jeffpiazza/derbynet/files/8191891/timer-20220305-2116.log)
I swear I tried that from the timer settings page put it seems to fix everything if I put it in the startup command.

**Comment by jeffpiazza** [comment]
The -legacy flag activates a completely different code path, one that I'm hoping to retire.

I'm now trying to borrow a Champ timer here locally and try to do some more testing and debugging.

**Comment by jeffpiazza** [comment]
After some experimenting with a borrowed Champ timer, the issue seems mostly to be that a 'rs' (request to read the gate state) apparently cancels any outstanding 'rg' (request for the timer to send results when a heat ends), resolvable with some tighter control over timing of gate polling.

**Comment by dagentooboy** [comment]
How do I go about updating the install on my raspberry pi?

**Comment by jeffpiazza** [comment]
If you're not changing raspbian versions, it should suffice to do:

apt update
apt install derbynet-timer

Recent versions of raspbian (apt, specifically) have new security restrictions, so you may need to follow the steps at [ ](https://jeffpiazza.org/derbynet/builds/Installation-%20Debian.pdf) to update the repository configuration.

**Comment by dagentooboy** [comment]
looks like it messed up the timer connecting.
[timer-20220310-1725.log](https://github.com/jeffpiazza/derbynet/files/8227780/timer-20220310-1725.log)

**Comment by jeffpiazza** [comment]
Oh, the "org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]" error means that you're connecting to a v6.0 (or earlier) server.

apt install derbynet-server 

to update to the v7.0 server and it should connect to the server without issue.

**Comment by dagentooboy** [comment]
It says server version is 1500

**Comment by dagentooboy** [comment]
after the update the server needs re-connected to the database. It all seems to be working now. Thanks for the help.

**Comment by nayyerz** [comment]
We ran a derby yesterday and had similar or same issue. We were running both the derby server and the timer  .jar  on a raspberry pi 3b plus. After some time, some heats were not getting recorded on the kiosk or the race dashboard website. 

The champ timer was recording the times correctly and we were debating whether to manually record times or not. 

After few reboots of everything. It started to work again. 

Is there a way to check what version of server and timer I have installed?

**Comment by jeffpiazza** [comment]
@nayyerz, could you say a bit more about what problems you experienced?  

The About page identifies the server version, and 

`java -jar derby-timer.jar -v`

should give the version of the jar file.

As mentioned earlier, the log file produced by derby-timer.jar is hugely helpful in diagnosing issues.  If you can find the log from yesterday, it'd help a lot.
