### ISSUE TITLE
Non Issue : Request for guidance on supporting an open class

### ISSUE THREAD

**Issue by zdannar** [jeffpiazza/derbynet#205]
Jeff,

Thank you so much for the software.  We got it working and are testing it before this weekend.  One of the things that we do is support an open class which races between the scout heats and scout finals.  What do you recommend to support this? 

Thanks again.  

P.S.  I may have a PR to send back to you regarding the docker container.  I had worked on it previously and you pointed out that there was a better method.  In the near future, I will send it to you for review.

**Comment by jeffpiazza** [comment]
I think in most cases you'd put your "open class" racers into their own partition, akin to a scout den or rank.  The only real difference from a scout den is that the aggregate "scout finals" round would only draw from the scout dens and not the open class.

I have a slightly out of date video that discusses some of the possibilities, at https://www.youtube.com/watch?v=i_2q8DH_qpU.
