### ISSUE TITLE
Feature Request: Add sub groups from UI

### ISSUE THREAD

**Issue by Ronald-Diemicke** [jeffpiazza/derbynet#21]
Maybe I missed this but it doesn't seem to be possible to add sub groups from the GUI. I'm using Group to represent 'Rank' and subgroup to represent 'Den' - but it seems like the only way to create/assign subgroups is through an import of CSV... or did I miss something?

**Comment by jeffpiazza** [comment]
No, you didn't miss anything, this is just something that didn't get implemented in time for v3.0.

The work-around, obviously, is to import at least one racer from every subgroup, even if you change all the details later.

**Comment by Ronald-Diemicke** [comment]
No worries. Just wanted to help record things incase anyone else sets it up and so there's documentation for folks who might come along. DebyNet is an impressive piece of software already!

**Comment by jeffpiazza** [comment]
Fixed by 5f8362c62ce71ed17c978888d4fc8d9661bdbebc.
