### ISSUE TITLE
Switch to ARM for docker?

### ISSUE THREAD

**Issue by cjr222** [jeffpiazza/derbynet#216]
I used your fantastic software last year as a docker container. I tried to update to the latest image and get an error starting the container that I believe is because I'm on x86 and the image has switched to arm? Can you confirm the change and if you still have the old image available somewhere?

**Comment by jeffpiazza** [comment]
Oops!  I updated the underlying Linux (to Alpine from Ubuntu), which makes for a much smaller docker image, but in the process, somehow the default platform also got changed, apparently.

**Comment by jeffpiazza** [comment]
The current (a few minutes ago) docker image has linux/amd64 as its platform.  I found that on my Apple silicon Mac, I needed to add an explicit  --platform linux/amd64  to the  docker run  command.  You might or might not have a similar experience.

I'll aim to update to a "multi-platform" build in the next few days, so users can just get the right image for their native platform.

**Comment by cjr222** [comment]
Thanks for the quick reply Jeff! The latest image you put out there works for me. I'll look into the platform command as part of my compose as well, I have never used that before.
