### ISSUE TITLE
AJAX error

### ISSUE THREAD

**Issue by jkaproth** [jeffpiazza/derbynet#218]
I am getting an AJAX error when I attempt to start the race.  using the internal JAR timer.  This is my first attempt at Derbynet, so I am sure I am just not familiar enough with the system!

**Comment by jeffpiazza** [comment]
Could you say a little more about your set-up?  

Do you have any log files from the server or the timer jar?

**Comment by jkaproth** [comment]
I have The Champ from besttrack , connected to a Intel Core i3 laptop running derbynet software.

my logs on the timer show clean, and only RS and data as I send it.

I cannot find the server logs, sorry.

**Comment by jeffpiazza** [comment]
I'm guessing you're running on Windows?  There should be an "Apache Logs" menu item on the "Apache" menu.

Since The Champ doesn't have a remote gate release, I assume that you're opening the gate by hand?

Where/how do you observe an AJAX error?  Displayed on the race dashboard page?

**Comment by jkaproth** [comment]
correct.  it pops up on the race coordinator page.
![Screenshot 2023-01-04 112340](https://user-images.githubusercontent.com/121962640/210613469-927f68cb-533f-4676-be87-69c4e977ee1d.jpg)

gate release will be done manually.  

[error.log](https://github.com/jeffpiazza/derbynet/files/10346173/error.log)

**Comment by jkaproth** [comment]
and yes, its windows.

**Comment by jeffpiazza** [comment]
The server logs indicate there's at least one race result recorded with an empty string as the finish time, which then causes a server error.  I'm not sure what would cause the bad finish time to be recorded.

(1) From the About page, could you please export the database and attach to the bug?  (Or email it if it's not attachable.)

(2) From the Set-Up page, try purging all race results, which should stop the server error, and then see if the problem is reproducible.

**Comment by jkaproth** [comment]
well, that solved that.

Now, to solve my next issue.

It seems to keep resetting the timer.  so fast, no chance to even get data back.  If i run the linesetup4.exe that comes with the timer, it works fine.  INT Unexpected transition:  Mark >--PREPARE_HEAT_RECEIVED--> Mark
--> oM0
--> RS
<--0
-->RS

**Comment by jeffpiazza** [comment]
I'm not sure what "reseting the timer" means here, exactly.  What steps are you actually following, and what do you observe (and how is it different from what you expect)?

The om0 command clears the lane mask, and the rs's are to read the start gate's state.  In isolation, nothing anomalous about that.

Normally, upon completion of a heat, the results are left on the display for a few seconds (like 10) before the lane mask gets cleared and the timer prepared for the next heat.

**Comment by jkaproth** [comment]
I have gone into timer testing, and timer status keeps going back to staging.

**Comment by jeffpiazza** [comment]
You mentioned earlier using the "internal JAR timer".  If that means you're using the derby-timer.jar interface to the timer, there should be a log file produced by that interface that'd be extremely useful.  Find it with the "Show Log File" menu item on the "File" menu.

I assume you're holding the start gate open and observing that the timer won't keep timing for more than a moment or so?  Is there any communication from the timer when the gate opens (especially a heat "result" of 0.00 times)?

I can't really tell from your video whether the timer is mounted to the track; it can be tricky to get the beams aligned when the timer isn't on the track.

**Comment by jeffpiazza** [comment]
Any chance you have another timer interface open somewhere, like maybe the Fake Timer in another browser window?  For some reason, the server keeps re-announcing the current heat, which really shouldn't happen unless the timer interface declares itself to be in a different state somehow.

Earlier you sent the server error log, but I wonder if you could send the server's most recent access.log now?  That might be informative.

Also, could you take a quick look at the "Retrospective" page, just to see if anything jumps out there?

**Comment by jkaproth** [comment]
[retrospective.txt](https://github.com/jeffpiazza/derbynet/files/10348253/retrospective.txt)
[access.log](https://github.com/jeffpiazza/derbynet/files/10348265/access.log)
had to delete the old stuff, to get it under 25mb.

**Comment by jkaproth** [comment]
Also, I have rebooted to verify there was no other timer. Will try again thoughOn Jan 4, 2023 5:39 PM, Jeff Piazza ***@***.***> wrote:
Any chance you have another timer interface open somewhere, like maybe the Fake Timer in another browser window?  For some reason, the server keeps re-announcing the current heat, which really shouldn't happen unless the timer interface declares itself to be in a different state somehow.
Earlier you sent the server error log, but I wonder if you could send the server's most recent access.log now?  That might be informative.
Also, could you take a quick look at the "Retrospective" page, just to see if anything jumps out there?

**Comment by jkaproth** [comment]
so, I did another reboot, and tested it a bit differently.

Upon reboot, I opened uniserver, and started apache.
then I opened derby timer.jar
it all works fine, until I connect derby timer.jar to the server.  then the restarts on the track timer start.

**Comment by jeffpiazza** [comment]
OK, let's try this: Run the jar file, but now specifying this server:

https://hosting.derbynet.org/2023/xx/bug218/

(The logging is more detailed here than what's available in the normal deployment.)

I've set up simulated racing for four lanes, so as soon as the timer is recognized, you could try "running" some heats.

**Comment by jkaproth** [comment]
connected now.

**Comment by jkaproth** [comment]
appreciate your time.  sorry I am needy.

**Comment by jeffpiazza** [comment]
OK, I think I found it.  Would you try connecting again to the bug218 server and see if it works now?  If so, I'll have a bug fix up shortly.

**Comment by jkaproth** [comment]
well, that seems to work much better!

**Comment by jeffpiazza** [comment]
New build is available with the bug fix incorporated.

**Comment by jeffpiazza** [comment]
Updated the issue title to reflect the eventual issue reported at https://github.com/jeffpiazza/derbynet/issues/218#issuecomment-1371420326

**Comment by jkaproth** [comment]
219 fixed my issue.

 

I am so grateful for you and your help!!
