### ISSUE TITLE
Feature Request: Remove individual racers

### ISSUE THREAD

**Issue by Ronald-Diemicke** [jeffpiazza/derbynet#22]
Is there currently a way to remove individual racers? I haven't seen a way but maybe I missed it.

**Comment by jeffpiazza** [comment]
No, you haven't missed it, it's just something I haven't gotten around to.  

It's more or less harmless to have extra racers on the roster, of course - you can just elect never to check in the extra racers.  But it's still an obvious deficiency.

**Comment by Ronald-Diemicke** [comment]
No worries. Also - is there a coding standards guide or anything that I should be aware of if I wanted to submit a PR?
