### ISSUE TITLE
Unable to select image set on setting page in v8

### ISSUE THREAD

**Issue by youngdavidj** [jeffpiazza/derbynet#220]
When trying to print DL get this error

An exception occurred in processing for Fabian Garcia (1):
  FPDF error: Image file has no extension and no type was specified: /home/cubscout/public_html/pinewood23/Images/Generic/emblem

**Comment by jeffpiazza** [comment]
What build are you using ("About" page), and what OS?  Are you running a docker image?

**Comment by youngdavidj** [comment]
DerbyNet Revision
This is revision 1564, built on December 6 2022.
(fe70c646b4ce0b6a295d4d0d25766ab4563f6390)

Running DerbyNet on pack's web hosting. Attaching about page
[About DerbyNet.pdf](https://github.com/jeffpiazza/derbynet/files/10369850/About.DerbyNet.pdf)

**Comment by jeffpiazza** [comment]
Oh, right, we had an email exchange about deploying in this environment back in October of 2021.

Can you check what files are in the /home/cubscout/public_html/pinewood23/Images/Generic/ directory?  There should be an emblem.png file (and not an "emblem" file without an extension).

**Comment by youngdavidj** [comment]
<img width="1207" alt="Screenshot 2023-01-08 at 7 04 21 PM" src="https://user-images.githubusercontent.com/122236878/211227864-d32908a2-9849-4ae4-9593-cd579d2391b0.png">

I see the emblem.png file

**Comment by jeffpiazza** [comment]
I'm guessing we're facing some kind of permissions issue that's causing the second glob() call to fail in image_file_path, in inc/path-info.inc:

```
function image_file_path($filename) {
  global $homedir;
  if (isset($homedir)) {
    $dir = $homedir.DIRECTORY_SEPARATOR.'imagery'.DIRECTORY_SEPARATOR;
    $g = glob($dir.$filename.".*");
    if ($g !== false && count($g) > 0) {
      return $g[0];
    }
  }
  $dir = image_base_dir().DIRECTORY_SEPARATOR
       .read_raceinfo("images-dir", 'Generic').DIRECTORY_SEPARATOR;
  $g = glob($dir.$filename.".*");
  if ($g !== false && count($g) > 0) {
    return $g[0];
  }
  // Shouldn't get here
  return $dir.$filename;
}
```

The server's error log may offer a clue.

As a partial work-around, you could try changing the very last line of that function (marked with "Shouldn't get here" comment) to ` return $dir.$filename.".png"; `.  There'd be a few other things that probably still wouldn't work:

- The title slide for the slideshow page or kiosk.
- The flag kiosk
- Car tags with car-number-based emblems

**Comment by youngdavidj** [comment]
In the older version there was an option to select a image set on the setting page via a drop down that still does not show in v8, but the setting page for v7 I still have on the same server has the drop down and does not get this printing error.
<img width="905" alt="Screenshot 2023-01-08 at 7 51 03 PM" src="https://user-images.githubusercontent.com/122236878/211230161-47d5204a-c691-4443-99ca-fd5b62c465ba.png">

**Comment by jeffpiazza** [comment]
The image handling is different in v8, to support using customized images.  The `<select>` by which the user selects the image set is generated by scanning the Images directory, which is presumably failing in the same way that the `image_file_path` function does.

I'd definitely check that the "execute" permission bit is set on at least the Images and Images/Generic directories (755 rather than 644, I think).

**Comment by youngdavidj** [comment]
Doubled checked the permissions on the Images and Images/Generic folders and they are 755 already and still unable to select an image set to allow printing.

**Comment by jeffpiazza** [comment]
OK, permissions was just a (reasonably educated) guess.  For whatever reason, it appears the server/php installation you're using doesn't support the glob() or scandir() functions in PHP.  So I think you're left with the partial work-around mentioned above, or some variation thereon.  (Unless you can persuade your hosting provider to help with the PHP issue.)

In the long run, you might want to consider other options, like using hosted derbynet instances (sacrificing the use of your custom domain name, unfortunately) or maybe running a docker image with your existing hosting provider (assuming that's something your hosting provider supports).

**Comment by youngdavidj** [comment]
Updated the last function of  inc/path-info.inc with the workaround you suggested still receiving an error.

  FPDF error: Image file has no extension and no type was specified: /home/cubscout/public_html/pinewood23/Images/Generic/emblem

**Comment by jeffpiazza** [comment]
The last function in inc/path-info.inc is slide_file_path, which affects retrieval of slideshow slides.  (That function will have similar problems, but you may well not care.)  For the drivers' license printables, you need to modify the function image_file_path, the penultimate function in inc/path-info.inc.

**Comment by jeffpiazza** [comment]
I'm going to close this issue.  As I mentioned earlier, I think this is specific to your unique installation and the PHP installation over which you don't have control.  I'm happy to continue working with you privately if this is still unresolved for you.
