### ISSUE TITLE
Unable to Print check-in Cards

### ISSUE THREAD

**Issue by Dulanic** [jeffpiazza/derbynet#222]
Hello,

I setup my install /w docker and a reverse proxy. When I click to print things in printables, it just gives me some weird debug error?

```
Debugging $_SERVER: array ( 'USER' => 'nobody', 'HOME' => '/', 'PATH_TRANSLATED' => '/var/www/html', 'ORIG_SCRIPT_FILENAME' => '/var/www/html/render-document.php/racer/CheckInCardDocument', 'HTTP_X_REAL_IP' => '192.168.2.33', 'HTTP_X_FORWARDED_PROTO' => 'https', 'HTTP_X_FORWARDED_HOST' => 'derby.redacted.com', 'HTTP_X_FORWARDED_FOR' => '192.168.2.33', 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1', 'HTTP_SEC_FETCH_USER' => '?1', 'HTTP_SEC_FETCH_SITE' => 'same-origin', 'HTTP_SEC_FETCH_MODE' => 'navigate', 'HTTP_SEC_FETCH_DEST' => 'document', 'HTTP_SEC_CH_UA_PLATFORM' => '"Windows"', 'HTTP_SEC_CH_UA_MOBILE' => '?0', 'HTTP_SEC_CH_UA' => '"Not_A Brand";v="99", "Microsoft Edge";v="109", "Chromium";v="109"', 'HTTP_REFERER' => 'https://derby.dulanic.com/print.php', 'HTTP_DNT' => '1', 'HTTP_COOKIE' => 'PHPSESSID=redacted', 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9', 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br', 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9', 'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55', 'HTTP_HOST' => 'derby.redacted.com', 'DERBYNET_DATA_DIR' => '/var/lib/derbynet', 'DERBYNET_CONFIG_DIR' => '/var/lib/derbynet', 'REDIRECT_STATUS' => '200', 'SERVER_NAME' => '_', 'SERVER_PORT' => '80', 'SERVER_ADDR' => '172.27.0.57', 'REMOTE_PORT' => '55288', 'REMOTE_ADDR' => '172.27.0.42', 'SERVER_SOFTWARE' => 'nginx/1.22.1', 'GATEWAY_INTERFACE' => 'CGI/1.1', 'REQUEST_SCHEME' => 'http', 'SERVER_PROTOCOL' => 'HTTP/1.1', 'DOCUMENT_ROOT' => '/var/www/html', 'DOCUMENT_URI' => '/render-document.php/racer/CheckInCardDocument', 'REQUEST_URI' => '/render-document.php/racer/CheckInCardDocument?options=%7B%7D&ids=10,7,5,9,12,11,2,6,1,13,4,8,3', 'SCRIPT_NAME' => '/render-document.php/racer/CheckInCardDocument', 'CONTENT_LENGTH' => '', 'CONTENT_TYPE' => '', 'REQUEST_METHOD' => 'GET', 'QUERY_STRING' => 'options=%7B%7D&ids=10,7,5,9,12,11,2,6,1,13,4,8,3', 'SCRIPT_FILENAME' => '/var/www/html/render-document.php', 'FCGI_ROLE' => 'RESPONDER', 'PHP_SELF' => '/render-document.php/racer/CheckInCardDocument', 'REQUEST_TIME_FLOAT' => 1674244534.993751, 'REQUEST_TIME' => 1674244534, )
```

**Comment by jeffpiazza** [comment]
There had been an issue like this for older docker images, but I thought it was fixed now.  Could you confirm which build you're running ("About" page)?

**Comment by Dulanic** [comment]
Fast response! :)  

```
DerbyNet Revision
This is revision 1572, built on January 4 2023.
(4a5c6e09e533fb81a7e7d365dc95a650d8b358f1)
```

Docker-compose code:
```
  derbynet:
    container_name: derbynet
    image: jeffpiazza/derbynet_server
    volumes:
      - /home/dulanic/docker/derbynet:/var/lib/derbynet 
      - /etc/localtime:/etc/localtime:ro 
      
 ```

**Comment by jeffpiazza** [comment]
Fix should be in d69b52c32ae187a95ba1d4c40315e4db397e1f53, committed on the 7th.

Could you try upgrading to the latest image?  I'm hoping that will clear it up.

**Comment by Dulanic** [comment]
> Fix should be in [d69b52c](https://github.com/jeffpiazza/derbynet/commit/d69b52c32ae187a95ba1d4c40315e4db397e1f53), committed on the 7th.
> 
> Could you try upgrading to the latest image? I'm hoping that will clear it up.

I literally just installed this afternoon, so not sure if I can do anything else since it's pulling the latest docker image. I think I'd have to build my own docker image, which while I can do, I don't have time before our race :(

**Comment by burnclouds** [comment]
I'm having the same issue with all printables. I also use docker, pulled the image this morning.

This is revision 1572, built on January 4 2023.
(4a5c6e09e533fb81a7e7d365dc95a650d8b358f1)

How should I go about upgrading the image? the one on docker hub was posted a day ago.

user@a-sus-pc:~$ date
Fri Jan 20 15:11:17 EST 2023
user@a-sus-pc:~$ sudo docker pull jeffpiazza/derbynet_server:latest
latest: Pulling from jeffpiazza/derbynet_server
Digest: sha256:c70084a1d15ddcb3ee01719519d0cdbd71b81349c4c391a97461cd155ef76bb0
Status: Image is up to date for jeffpiazza/derbynet_server:latest
docker.io/jeffpiazza/derbynet_server:latest

-------------------------------------------------------------

Debugging $_SERVER: array ( 'USER' => 'nobody', 'HOME' => '/', 'PATH_TRANSLATED' => '/var/www/html', 'ORIG_SCRIPT_FILENAME' => '/var/www/html/render-document.php/summary/ScheduleDocument', 'HTTP_COOKIE' => 'PHPSESSID=oqd7msli4b79d2f30u14fu72hd', 'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.9', 'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, br', 'HTTP_REFERER' => 'http://127.0.0.1/print.php', 'HTTP_SEC_FETCH_DEST' => 'document', 'HTTP_SEC_FETCH_USER' => '?1', 'HTTP_SEC_FETCH_MODE' => 'navigate', 'HTTP_SEC_FETCH_SITE' => 'same-origin', 'HTTP_SEC_GPC' => '1', 'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8', 'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36', 'HTTP_UPGRADE_INSECURE_REQUESTS' => '1', 'HTTP_CONNECTION' => 'keep-alive', 'HTTP_HOST' => '127.0.0.1', 'DERBYNET_DATA_DIR' => '/var/lib/derbynet', 'DERBYNET_CONFIG_DIR' => '/var/lib/derbynet', 'REDIRECT_STATUS' => '200', 'SERVER_NAME' => '_', 'SERVER_PORT' => '80', 'SERVER_ADDR' => '172.17.0.2', 'REMOTE_PORT' => '57678', 'REMOTE_ADDR' => '172.17.0.1', 'SERVER_SOFTWARE' => 'nginx/1.22.1', 'GATEWAY_INTERFACE' => 'CGI/1.1', 'REQUEST_SCHEME' => 'http', 'SERVER_PROTOCOL' => 'HTTP/1.1', 'DOCUMENT_ROOT' => '/var/www/html', 'DOCUMENT_URI' => '/render-document.php/summary/ScheduleDocument', 'REQUEST_URI' => '/render-document.php/summary/ScheduleDocument?options=%7B%7D&ids=0', 'SCRIPT_NAME' => '/render-document.php/summary/ScheduleDocument', 'CONTENT_LENGTH' => '', 'CONTENT_TYPE' => '', 'REQUEST_METHOD' => 'GET', 'QUERY_STRING' => 'options=%7B%7D&ids=0', 'SCRIPT_FILENAME' => '/var/www/html/render-document.php', 'FCGI_ROLE' => 'RESPONDER', 'PHP_SELF' => '/render-document.php/summary/ScheduleDocument', 'REQUEST_TIME_FLOAT' => 1674243700.071893, 'REQUEST_TIME' => 1674243700, )

**Comment by burnclouds** [comment]
ok. So i have it working, but kinda of a hack for my existing docker container while we wait for an updated container on dockerhub.

```
user@a-sus-pc#docker exec -it DerbyNet /bin/bash
bafaa5f2891e:/# apk add php-iconv
bafaa5f2891e:/# cd /var/www/html/
bafaa5f2891e:/# wget "https://raw.githubusercontent.com/jeffpiazza/derbynet/master/website/render-document.php"

```

**Comment by Dulanic** [comment]
> ok. So i have it working, but kinda of a hack for my existing docker container while we wait for an updated container on dockerhub.
> 
> ```
> user@a-sus-pc#docker exec -it DerbyNet /bin/bash
> bafaa5f2891e:/# apk add php-iconv
> bafaa5f2891e:/# cd /var/www/html/
> bafaa5f2891e:/# wget "https://raw.githubusercontent.com/jeffpiazza/derbynet/master/website/render-document.php"
> bafaa5f2891e:/# exit
> user@a-sus-pc#docker container restart DerbyNet
> ```

You read my mind! LOL I was literally doing the exact same thing as you posted that.

**Comment by burnclouds** [comment]
Too Funny. Good Luck with running your race. I'm about 6 weeks out and trying to figure out how i want to configure the software.

**Comment by jeffpiazza** [comment]
Maybe someone who understands docker hub better than I do can chime in. Maybe try pulling jeffpiazza/derbynet_server:amd64 (which is a docker image) instead of :latest, which is a manifest.  Maybe I outsmarted myself trying to support amd64 and arm64 together.

**Comment by burnclouds** [comment]
Just did a pull for the amd64 tag. That works, printables are confirmed to work as well.

```
This is revision 1582, built on January 19 2023.
(d982094d6650e06ceba68d7fe9ea8693761b9514)
```

**Comment by Dulanic** [comment]
Honestly, I switched to GitHub container repo myself once docker got more limited with automatic builds. But thanks for the info that the AMD64 version works.

**Comment by burnclouds** [comment]
> Honestly, I switched to GitHub container repo myself once docker got more limited with automatic builds. But thanks for the info that the AMD64 version works.

Wait what? there is a github container repo?! got documentation on that?

**Comment by Dulanic** [comment]
> > Honestly, I switched to GitHub container repo myself once docker got more limited with automatic builds. But thanks for the info that the AMD64 version works.
> 
> Wait what? there is a github container repo?! got documentation on that?

https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

I use it to build my own caddy container for my reverse proxy. I am by no means a master though!

https://github.com/Dulanic/docker-caddy
