### ISSUE TITLE
Scheduling dialog offers choices it can't support

### ISSUE THREAD

**Issue by Ronald-Diemicke** [jeffpiazza/derbynet#23]
I'm running tests before our event and I noticed something where I have a group of boys, and I'm trying to figure out roughly how long the event will be with different options, but with the same den, I scheduled a group of racers for one time on each lane. Then ran some test races where I put in times manually. Then I went in using the manual tool and removed those heats, then unscheduled the race. Now it seems to 'ignore' how many times I want each racer to race on each lane for that group.

Probably a real edge case problem that'd only come up in playing with it.

**Comment by jeffpiazza** [comment]
Could you send a database that exhibits this?  Or the export from the "about" page?

**Comment by jeffpiazza** [comment]
I'm afraid I'm unable to reproduce this without additional information.

**Comment by ScouterAndy** [comment]
We ran into this on the weekend as well.   Seemed to be somewhat random... but in fact Ronald-Diemicke's note is a sort of a-ha moment I think... it did seem to happen when we have done manual times and/or unscheduled and rescheduled a race.  The scenario is roughly the same... if we initially generate a schedule with, say, 2 runs per lane, it works... but after certain edits or tinkering, when we then re-generate a new schedule with the same 2 runs per lane, we only get 1 run per lane.  I'm not sure if I can get a database with this issue or not.

**Comment by ScouterAndy** [comment]
For instance... one case I know this happened and remember the chronology... we had registered 7 racers and gone ahead and created a schedule, with 2 runs per lane, and it correctly generated 14 heats on a six lane track.  Moments before racing began, the inevitable late car showed up... so we unscheduled, registered the car, and generated a new schedule... we asked for 2 runs per lane again but got a schedule with only 8 heats for the field of now 8 racers; therefore although we asked for 2 per lane, we got a 1-per-lane schedule instead.   2 per lane should have resulted in at least 16 heats.

**Comment by jeffpiazza** [comment]
The number of generators available varies according to the number of lanes and the number of racers.  For a 6-lane track, in many cases only a single generator is available, which means the current schedule generator can't support a 2-runs-per-lane schedule, and silently falls back to a 1-run-per-lane schedule.

In particular, there are two generators for 7 racers but only one for 8 racers:
https://github.com/jeffpiazza/derbynet/blob/bdf61311056680676b9b0cc9271082955395a8c2/website/inc/schedule_generator.inc#L179

Where too few generators exist, another way of forming a schedule with additional runs per lane has to be implemented, with a new base permutation.  Additionally, if the generator can't support all combinations, the scheduling dialog needs to reflect this and not just return something different than was requested.

**Comment by ScouterAndy** [comment]
If the generator falls back to 1-run-per-lane but the user requested 2-runs-per-lane, why not just repeat the schedule for the second set so that the user request is followed?  In other words, a generator is repeatable sequentially to produce the desired lane count.
