### ISSUE TITLE
Instructions for sharing a DB from the MAC version of GPRM

### ISSUE THREAD

**Issue by Ronald-Diemicke** [jeffpiazza/derbynet#24]
Just noticed that GPRM has a Mac version and I'm wondering if DerbyNet can share the sqlite database from that.

**Comment by jeffpiazza** [comment]
I don't know if the schema's much different; it's possible it could work.

If you have such a database, please send it.  To try connecting, use the "Advanced" button in the set-up dialog and navigate to the database file.
