### ISSUE TITLE
update jssc.jar to support windows and macOS on arm64

### ISSUE THREAD

**Issue by willnorris** [jeffpiazza/derbynet#246]
derbynet is currently using jssc 2.9.2, which wasn't able to run on my M1 mac.  It looks like support for macOS on arm64 was [added in 2.9.3](https://github.com/java-native/jssc/releases/tag/v2.9.3), and then support for Windows on arm64 was [added in 2.9.4](https://github.com/java-native/jssc/releases/tag/v2.9.4).

I'm happy to send a PR to update, but given that it's a binary blob, I thought you might want to do it yourself.

**Comment by jeffpiazza** [comment]
Thanks for this!
