### ISSUE TITLE
Running Server/Client Mode IP being displayed is localhost/127.0.0.1

### ISSUE THREAD

**Issue by majora15** [jeffpiazza/derbynet#247]
If I'm running in a server / client mode, meaning 1 machine is a server and I have multiple clients, 1 for check-in, 1 for managing races, etc... it often defaults the ip address for 127.0.0.1.  For Example, voting page, mobile check in page, about page.

**Comment by majora15** [comment]
This is running under a linux server build.

**Comment by jeffpiazza** [comment]
The IP address(es) displayed are a best-effort guess, I'm afraid.

If there's a text file named preferred-url in the config directory (normally the subdirectory named 'local' under the derbynet website directory), its contents will be taken as the preferred IP address (or host name, if that's meaningful on your network) in the places you mention.

**Comment by majora15** [comment]
So to confirm the file should be located in /var/www/html/derbynet/local/config?  It should be named preferred-url.txt?  For content it would have just the ip address or hostname?

**Comment by jeffpiazza** [comment]
The name of the file would just be 'config-url', without an extension.  So /var/www/html/derbynet/local/config-url.
