### ISSUE TITLE
UniServerZ exe not in directory

### ISSUE THREAD

**Issue by RealPilot** [jeffpiazza/derbynet#25]
Just downloaded v3.0 for win and there is no .exe in the UniServerZ folder.

**Comment by jeffpiazza** [comment]
I can confirm that DerbyNet-v3.0-672-20180115.win.zip includes UniServerZ\UniController.exe.

What build did you download?

**Comment by RealPilot** [comment]
That’s what I downloaded last night off of github.  After unpacking that
file was missing.  I’ll try it again on a different computer.

**Comment by RealPilot** [comment]
Redwnloaded and it’s there but I get this error when trying to execute.

**Comment by jeffpiazza** [comment]
What is "this error" when trying to launch UniController?

You can expect to see security alerts asking you to confirm that it's OK for this downloaded executable to access the network, but that's "as intended" behavior.

Are you seeing something else?

**Comment by RealPilot** [comment]
I attached a picture of it.  it's when opening the unicontroller.  Error in
path.  Spaces are not allowed please correct and run the application again.

**Comment by jeffpiazza** [comment]
Apparently, Uniform Server requires that the directory in which you install it, and all it's parent directories, not have any spaces in them.  I hadn't realized this was the case; I've updated the Windows install guide to reflect this.
