### ISSUE TITLE
Champ Timer continuously resets

### ISSUE THREAD

**Issue by burnclouds** [jeffpiazza/derbynet#252]
seems like the time.jar is resetting while scanning for a timer.

Command:
`java -jar ./derby-timer.jar -n /dev/ttyUSB0 -d Champ -insecure http://192.168.242.10`
```
Starting log file /home/user/timer-20230130-1324.log
/dev/ttyUSB0
    Champ   Sending HELLO

/dev/ttyUSB0
    Champ
/dev/ttyUSB0
    Champ
/dev/ttyUSB0
    Champ
/dev/ttyUSB0
    Champ
/dev/ttyUSB0
    Champ
```

Local Timer Log:
[timer-20230130-1306.log](https://github.com/jeffpiazza/derbynet/files/10538662/timer-20230130-1306.log)

DerbyNet log:
[timer-20230130-1806-03.log](https://github.com/jeffpiazza/derbynet/files/10538664/timer-20230130-1806-03.log)

**Comment by jeffpiazza** [comment]
Is this a particularly old or particularly new timer?  All the other Champ timer's I've seen respond to a "v" query with a "eTekGadget SmartLine Timer" string.

**Comment by burnclouds** [comment]
Just received it this week. I'm contacting besttrack to see if they have
started their own production line for this timer or something.

Looking at the command set for the etekgadget smart line (link below) the
time takes multiple characters in a string followed by <cr>  (return). This
timer doesn't seem to take that. the v character gives the version. the C
(capitol) gives the gate status. A,D,F  give some response that isn't '?'
So my timer doesn't look like it matches the command set Maybe stuck in DTX
mode?)

https://etekgadget.com/public/pdfs/SmartLine_Command.pdf

**Comment by burnclouds** [comment]
`~/DerbyNet$ java -jar ./derby-timer.jar -n /dev/ttyUSB0 -d Champ -insecure http://192.168.242.100`
```
Starting log file /home/user/DerbyNet/timer-20230131-1813.log
/dev/ttyUSB0
    Champ   Sending HELLO

*** Identified as a(n) Champ
Timer-Server connection established.
   Sending IDENTIFIED
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
MARK >--ABORT_HEAT_RECEIVED--> IDLE
IDLE >--PREPARE_HEAT_RECEIVED--> MARK

```
[timer-20230131-1813.log](https://github.com/jeffpiazza/derbynet/files/10551818/timer-20230131-1813.log)
[timer-20230131-2313-33.log](https://github.com/jeffpiazza/derbynet/files/10551819/timer-20230131-2313-33.log)

**Comment by burnclouds** [comment]
It connects fine. acknowledges the device "locks on".

I don't get any results, other that those showing in the log file. And the long set of "?" responses leads me to believe the device doesn't understand the commands given. Also the results display show and clears in just a few seconds or less.

**Comment by burnclouds** [comment]
`~/DerbyNet$ java -jar ./derby-timer.b.jar -n /dev/ttyUSB0 -d Champ -insecure http://192.168.242.100`
```
Starting log file /home/user/DerbyNet/timer-20230201-1651.log
/dev/ttyUSB0
    Champ   Sending HELLO

/dev/ttyUSB0
    Champ
*** Identified as a(n) Champ
Timer-Server connection established.
   Sending IDENTIFIED
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
MARK >--ABORT_HEAT_RECEIVED--> IDLE
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
```

[timer-20230201-1651.log](https://github.com/jeffpiazza/derbynet/files/10561922/timer-20230201-1651.log)
[timer-20230201-2151-37.log](https://github.com/jeffpiazza/derbynet/files/10561924/timer-20230201-2151-37.log)

**Comment by burnclouds** [comment]
`~/DerbyNet$ java -jar ./derby-timer.jar -n /dev/ttyUSB0 -d Champ -insecure http://192.168.242.100`
```
Starting log file /home/user/DerbyNet/timer-20230201-1742.log
/dev/ttyUSB0
    Champ   Sending HELLO

/dev/ttyUSB0
    Champ
*** Identified as a(n) Champ
Timer-Server connection established.
   Sending IDENTIFIED
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
MARK >--ABORT_HEAT_RECEIVED--> IDLE
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
MARK >--ABORT_HEAT_RECEIVED--> IDLE
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
```
The Second MARK showed as i switched from timer test to race mode.
[timer-20230201-1742.log](https://github.com/jeffpiazza/derbynet/files/10562446/timer-20230201-1742.log)
[timer-20230201-2242-31.log](https://github.com/jeffpiazza/derbynet/files/10562449/timer-20230201-2242-31.log)

**Comment by burnclouds** [comment]
**derby-timer-dtx.jar** 

`~/DerbyNet$ java -jar ./derby-timer-dtx.jar -n /dev/ttyUSB0 -d Champ -insecure http://192.168.242.100`
```
Starting log file /home/user
/DerbyNet/timer-20230202-0750.log
/dev/ttyUSB0
    Champ   Sending HELLO

*** Identified as a(n) Champ
Timer-Server connection established.
   Sending IDENTIFIED
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
MARK >--ABORT_HEAT_RECEIVED--> IDLE
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
```
[timer-20230202-0750.log](https://github.com/jeffpiazza/derbynet/files/10569132/timer-20230202-0750.log)
[timer-20230202-1250-36.log](https://github.com/jeffpiazza/derbynet/files/10569134/timer-20230202-1250-36.log)



**derby-timer-dtx.jar**
`~/DerbyNet$ java -jar ./derby-timer-minimal.jar -n /dev/ttyUSB0 -d Champ -insecure http://192.168.242.100`
```
Starting log file /home/user/DerbyNet/timer-20230202-0754.log
/dev/ttyUSB0
    Champ   Sending HELLO

*** Identified as a(n) Champ
Timer-Server connection established.
   Sending IDENTIFIED
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
MARK >--ABORT_HEAT_RECEIVED--> IDLE
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
MARK >--ABORT_HEAT_RECEIVED--> IDLE
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
```
[timer-20230202-0754.log](https://github.com/jeffpiazza/derbynet/files/10569182/timer-20230202-0754.log)
[timer-20230202-1254-41.log](https://github.com/jeffpiazza/derbynet/files/10569185/timer-20230202-1254-41.log)

**Comment by jeffpiazza** [comment]
Could I get you to re-run the -minimal version without force-choosing Champ?  That version provides a different experimental profile for this timer.

**Comment by jeffpiazza** [comment]
Thank you!

One more request: could you try the -minimal jar with -d ChampSRM command line arg?

**Comment by burnclouds** [comment]
`~/DerbyNet$ java -jar ./derby-timer-minimal.jar -d ChampSRM -n /dev/ttyUSB0 -insecure http://192.168.242.100`
```
Starting log file /home/user/DerbyNet/timer-20230203-0727.log
   Sending HELLO
/dev/ttyUSB0
    ChampSRM
*** Identified as a(n) ChampSRM
Timer-Server connection established.
   Sending IDENTIFIED
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
MARK >--ABORT_HEAT_RECEIVED--> IDLE

```

[timer-20230203-0727.log](https://github.com/jeffpiazza/derbynet/files/10578875/timer-20230203-0727.log)


Appears the only command the SRM Champ responds to are:
```
+07:27:53.417S		--> v
+07:27:53.560S		<-- Rev H Copyright SRM Enterprises
+07:27:53.920S		--> A
+07:27:54.121S		--> C
+07:27:54.195S		<-- 1
+07:27:54.223S		--> D
+07:27:54.424S		--> F
+07:27:55.632S		--> R
```

v return version
C returns gate state
The Timer gives an S to indicate the start of a run.
I haven't figured out what A, D,F,R, do yet.
I have noticed that if the time isn't in an active race mode any command causes the display to clear.

**Comment by burnclouds** [comment]
~/DerbyNet$ java -jar ./derby-timer-srm.jar                
Error: Could not find or load main class org.jeffpiazza.derby.TimerMain
Caused by: java.lang.ClassNotFoundException: org.jeffpiazza.derby.TimerMain

**Comment by burnclouds** [comment]
Success! Interestingly (i;ve not done any investigation) the DerbyNet timer test logs used to go to /var/lib/derbynet/[database-name]/logs, today it started going to /tmp/

`~/DerbyNet$ java -jar ./derby-timer-srm.jar -n /dev/ttyUSB0 -insecure http://192.168.242.100`
```
Starting log file /home/user/DerbyNet/timer-20230204-0928.log
   Sending HELLO
/dev/ttyUSB0
    Champ
    ChampSRM
*** Identified as a(n) ChampSRM
Timer-Server connection established.
   Sending IDENTIFIED
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
MARK >--RACE_FINISHED--> IDLE
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
MARK >--ABORT_HEAT_RECEIVED--> IDLE
IDLE >--PREPARE_HEAT_RECEIVED--> MARK
MARK >--RACE_FINISHED--> IDLE
IDLE >--PREPARE_HEAT_RECEIVED--> MAR
```
[timer-20230204-0928.log](https://github.com/jeffpiazza/derbynet/files/10608868/timer-20230204-0928.log)
[timer-20230204-1428-15.log](https://github.com/jeffpiazza/derbynet/files/10608884/timer-20230204-1428-15.log)

**Comment by jeffpiazza** [comment]
66b49dcdfaffaaffda225f94dda4dff9ec55ca4f includes at least initial support for this new "Champ" firmware, which behaves completely unlike previous versions.

**Comment by burnclouds** [comment]
Curious as to why line 28         .gate_state_is_knowable(false)
When 'C' returns the gate state. Just because this is initial capabilities?

**Comment by jeffpiazza** [comment]
This seemed like a viable first draft, without having to do further testing to be confident that the "C" response is reliable, and trying to figure out what the other commands might do.  The difference is mainly whether the timer reports that the race is "staging" for the next racing, which isn't that informative in practice.

Since we're on the subject: If a "C" returns 1, does that indicate the gate is open, or closed?  Does the other state return 0?

**Comment by burnclouds** [comment]
Normally Closed Switch is pressed when the gate is UP (so switch open)
Staging: Gate Up (each lane place indicator 7 segment displays "u")
-->C
<--0

Normally Closed Switch is released when the gate is down (so switch closed)
Racing: Gate Down (each lane place indicator 7 segment displays "r")
-->C
<--1
