### ISSUE TITLE
Import Button missing on Win 3.0

### ISSUE THREAD

**Issue by RealPilot** [jeffpiazza/derbynet#26]
There is no import button on the roster or awards pages.  You can shoose a file, drag headers, but nothing else.

**Comment by jeffpiazza** [comment]
The import button appears when all the required (thick border) headers are in place.  The instruction at the top of the page says, "Assign field labels to enable file import."

I'll update to show a dimmed import button that becomes active when labels are placed.

**Comment by RealPilot** [comment]
These are the thick border boxes:

First & Last Name
First Name
Last Name
Den

Thin border:
Car Name
Car Number
SubGroup

I don't have a First & Last name box but to test I dragged it onto a header
and it still doesn't show and import button after dragging all 4 thick
border boxes.

**Comment by jeffpiazza** [comment]
What browser are you using?  Edge seems not to handle drag-and-drop labels correctly, but I don't know why.  I just confirmed the import page seems to work correctly with Chrome on Win10.

**Comment by RealPilot** [comment]
Chrome on windows 7.  Version 2 works fine with the drag and drop.

**Comment by jeffpiazza** [comment]
I can't seem to reproduce the behavior you describe.

Could you open a JavaScript console (under "More Tools" -> "Developer Tools") and reproduce, and then save the console (right-click "Save As") and send or attach?  

(BTW, "First & Last Name" is an alternative to "First Name" and "Last Name".  Applying either "First Name" or "Last Name" removes "First & Last Name", while, alternatively, applying "First & Last Name" removes both the "First Name" and "Last Name" labels.  As that's not what you're experiencing, I suspect some kind of javascript execution problem.)

**Comment by jeffpiazza** [comment]
My best hypothesis for this is that there was a javascript error of some kind, and so the script that activates the import button didn't get to run.  As I said, though, I'm not able to recreate this issue.

Absent a way to reproduce this, I'm closing for now, but will re-open if new information comes to light.
