### ISSUE TITLE
"Import Results" only works for "Racing by Den"

### ISSUE THREAD

**Issue by jpetrykanyn** [jeffpiazza/derbynet#262]
When importing roster (or other race data), the fields are not imported as shown in the preveiw.
See the screenshots and xlsx file used attached.
[derbynet-2023-02-25-Pack639.xlsx](https://github.com/jeffpiazza/derbynet/files/10834741/derbynet-2023-02-25-Pack639.xlsx)
![PreviewCapture](https://user-images.githubusercontent.com/52001001/221437330-068f505f-5e94-4226-bbaa-6f87d33f962d.JPG)
![PostCapture](https://user-images.githubusercontent.com/52001001/221437343-ea690591-39fc-4853-ae9d-a21b391be9e9.JPG)
![SetupGroupsCapture](https://user-images.githubusercontent.com/52001001/221437365-748330aa-904e-4fd2-8777-0671b8619e5b.JPG)
![GroupsCapture](https://user-images.githubusercontent.com/52001001/221437371-fbdb3072-91a4-4d89-b004-056498dc095c.JPG)
![RosterCapture](https://user-images.githubusercontent.com/52001001/221437382-d87ba4b2-5aeb-4973-989d-f7515bd3fd02.JPG)

**Comment by jeffpiazza** [comment]
I guess "Import Results" needs some more clarity -- it's expecting to import the "Results" tab from the exported workbook:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/13140826/221441155-0fb6f511-51a9-4f8c-8989-e2583c40d279.png">

The idea is to recreate, as near as possible, the full database from the exported heat results.  

If you're just trying to import the roster, the original "Import Roster" page is the right place for that.  For this particular spreadsheet, I see that there are separate group and subgroup ("Den") columns, and it's not completely clear what column labels should be used.  (In this case: from an empty database, visit the "Racing Groups" page and choose "Race as one big group," then import this roster with the "Den" label on the "Den" column, leaving the "Group" column unlabeled.)

**Comment by jpetrykanyn** [comment]
Thanks Jeff,

 

After initializing, If I import the roster using the steps mentioned, then I end up with duplicates of the racers when I import the results.

 

If initialize again, set groups to race as one group and I only import the results tab the roster rebuilds correctly but I end up with All Racers as a subgroup of All Racers with no dens.

 

Also, importing any den results from that point adds duplicates in the roster.

 

Any suggestions on the groups and den results? Is there another function I should be running to generate the results from the heat results?

 

-John

**Comment by jeffpiazza** [comment]
Looking more closely, I see that there are some bugs in the "Import Results" behavior that are probably benign for the common "Racing by Den" case but would prevent successful import for other racing group structures.
