### ISSUE TITLE
Fast Track K2 - Repeated LR command

### ISSUE THREAD

**Issue by bcottrill** [jeffpiazza/derbynet#264]
I'm seeing a repeated LR command on a FastTrack K2.
Timer works when sending basic commands via Serial Tools as follows 

  COPYRIGHT (c) MICRO WIZARD 2002 
  K2 Version 1.05a  Serial Number 12923
  LLRR
  *
  A=4.082$ B=4.009# C=3.945” D=3.817! E=0.000  F=0.000  

This suggests to me the timer hardware is fine.  When I connect using DerbyNet (either through derby-timer.jar or chrome I see LR ad infinitum as shown below.  Is this a derbynet behavior or instead something atypical about my serial port configuration?

+36.860 HELLO
   version=v8.0-1609, February 28 2023
   platform=MacIntel
   vendor=Google Inc.
   userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
   page loaded=0.032s ago
   scan started=Not yet
+42.623* INT Probing for "The Champ" (SmartLine/BestTrack) on port 0 USB x0557/x2008
+42.631S --> 
+42.847S <-* 
+44.753S --> v
+44.974S <-* v
+45.312* INT Probing for "The Champ" (SRM) on port 0 USB x0557/x2008
+45.321S --> 
+45.547S <-* 
+47.469S --> v
+47.681S <-* v
+48.002* INT Probing for FastTrack K- or Q-series on port 0 USB x0557/x2008
+48.010S --> RV
+48.016S <-- RV
+48.051S <-- COPYRIGHT (c) MICRO WIZARD 2002
+48.091S <-- K2 Version 1.05a  Serial Number 12923
+48.115* INT IDENTIFIED FastTrack K- or Q-series
+48.125S --> RE
+48.131S <-- RE
+48.134S <-- *
+48.235S --> N1
+48.240S <-- N1
+48.243S <-- *
+48.339S --> N2
+48.345S <-- N2
+48.348S <-- X
+48.451S --> RF
+48.457S <-- RF
+48.468S <-- 1111 1111
+48.472S <-- *
+48.812S --> RG
+48.818S <-- RG
+48.821S <-- X
+49.145H <-- Prepare heat 1,1,13,4,1,Fake Lions
+49.147* INT IDLE >--PREPARE_HEAT_RECEIVED--> MARK
+49.260S --> MG
+49.266S <-- MG
+49.324S --> LR
+49.331S <-- ACLR
+49.333S <-- *
+49.365S --> MB
+49.371S <-- MB
+49.374S <-- *
+49.478S --> ME
+49.484S <-- ME
+49.487S <-- *
+49.580S --> LR
+49.583S --> MF
+49.586S <-- LR
+49.589S <-- *
+49.593S <-- MF
+49.596S <-- *
+49.836S --> LR
+49.842S <-- LR
+49.845S <-- *
+50.091S --> LR
+50.098S <-- LR
+50.101S <-- *
+50.349S --> LR
+50.355S <-- LR
+50.358S <-- *
+50.605S --> LR
+50.612S <-- LR
+50.614S <-- *
 ...goes on forever

**Comment by bcottrill** [comment]
Operational issue.  We only have a laser, no microswitch.   RG returns X
rather than 0 or 1.

Behavior of our track (No derbynet, simple serial console, OR no computer
at all):
- mechanical gate opened by operator
- car crosses laser gate,
- laser stays off and serial remains silent
- cars cross finish and K2 reports time on track finish line
- K2 reports times and finishing order via serial

Behavior when derbynet connected:
- mechanical gate opened by operator
- car crosses laser gate,
- LR keeps coming, and laser stays ON despite breaking beam
- cars cross finish, no results observed on K2 (because it was reset
several times per second the whole run)
- serial console continues to spew LR

My assumption is that since RG returns X rather than 0 or 1 that g
ate_state_is_knowable should be false, and per comments
  // If the gate state is not knowable, then GATE_OPENED and GATE_CLOSED
events
  // are not expected, and the state machine effectively alternates between
IDLE
  // and MARK states.  GIVING_UP event doesn't happen, either, because it
  // can arise only from a RESULTS_OVERDUE state.

Thanks in advance for any insight.

**Comment by jeffpiazza** [comment]
As an interim work-around, if you turn on the option for fasttrack-automatic-gate-release (Race Dashboard > (Timer) Test page > Timer Settings), it should stop the LR commands.  Timer settings are not preserved, unfortunately; you have to re-apply each time you reconnect the timer.

Alternatively, I think you could click on the P-series option instead of allowing the K-series to be discovered, but I'm not sure lane masking would be available in that case.

**Comment by bcottrill** [comment]
Jeff - Workaround works well enough (masking works, need to manually press
the laser reset button each heat), so I am going to pause further debugging
for now.  The farthest I got using a lot of LogWriter.serial statements is
that the K2 is not being recognized as a FastTrackLegacy.  Still haven't
puzzled that out, but it's a starting point.
I appreciate the quick help.
Thanks,
Ben

**Comment by jeffpiazza** [comment]
I think should be fixed with ae9e30f0d89febb2637ba8829f93f369f140d56c, which is incorporated into v9.0, without having to apply any workarounds.  Please re-open if you experience this again.
