### ISSUE TITLE
Late Arrivals

### ISSUE THREAD

**Issue by Chipper2** [jeffpiazza/derbynet#268]
I may be in charge of doing a derby at an upcoming spring campout.  Lots of scouts and lots of cars, but not all at once.  They will be going from place to place throughout the day.  So I will have one pack at say 10, then another at 11 and so on.

I was hoping that I could run the same database all day as to keep everyone together, but with not everyone there all at once.  Is there a way to check in a few, run the heats with whoever we have, then the next hour when the new sets of scouts come in, we run the heats with those cars?

Playing around and running simulated races, I see that I check in some cars, run those heats.  Then I go back to check-in and if I check in more cars, it says "Late" next to their names.  But I don't see a way to run those "late" cars.

I see a button that says add new rounds, but there isn't an option to add those late cars.

Thanks for the help.

Chip

**Comment by jeffpiazza** [comment]
It's pretty common for medium to large organizations to be racing one group while the next group is still checking in; that presents no problem.  Building a racing schedule for a racing group is what closes the door to late check-ins for that racing group.

For the situation you're describing, you'd want to have each pack be one or more separate racing groups.  So your racing groups would be, say Pack1 and Pack2, or perhaps Pack1 Lions, Pack1 Tigers, ..., Pack2 Lions, Pack2 Tigers, etc.  In the latter case, you might also want to define aggregate groups for Pack1 (comprising Pack1 Lions, Pack1 Tigers, etc.) and Pack2 if you plan to recognize fastest in each pack.

**Comment by jeffpiazza** [comment]
Incidentally, for next season I have a new feature to accommodate late arrivals for a currently-racing racing group.  This involves modifying the schedule to insert the late racer into heats not yet raced, while keeping the results from the already-completed heats.  The modified schedule still races each racer the same number of times in each lane, but each racer may face slightly fewer distinct head to head opponents than they would have in the original schedule.

Separate racing groups would still be the solution to the problem you're describing here, though.
