### ISSUE TITLE
Feature Request:Exclude Grand Finals Winners from Den Trophy

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#27]
In order to avoid someone from earning multiple trophies, we typically have 3 overall (1st, 2nd, 3rd) trophies for speed and 2 in each den.  If a scout wins the overall they can't get a den trophy and the next two fastest get 1st/2nd in the den.  It would be nice to have an option to do this automatically in the software.  I know you can manually override this by setting speed trophies to zero for the den and manually creating awards for the den level awards but this is a bit of work and would be nice to have this feature built into DerbyNet.

**Comment by heatvent** [comment]
Not sure if this is under consideration but I am using subgroups for Dens and there isn't an option to schedule a "Grand Finals" round when adding races (probably because there is only one "Group").  So maybe this is allow 1 trophy per racer or something like that.

**Comment by mwaldropdatastax** [comment]
I would upvote this feature.  Our pack also excludes pack winners from the den level awards.  We do probably the same structure - we have 3 race classes (scouts, adults, siblings) and then subgroups for dens.  We want top overall for each race class, and speed awards for dens - but don't want the scout race class winners to get den winner prizes.

**Comment by heatvent** [comment]
If I can, I am going to revote for this enhancement again after going through this process at the end of our races yesterday.  The idea of not allowing this is to spread the trophies out a bit and not let one scout take home multiple speed trophies. Although, I see the logic in do that as well because they basically earned the den and top speed trophy.  

However, if you do want to implement this rule, without the ability to do this in the software, assigning speed awards becomes a manual and tedious process rather than being automated and ready to go straight out of the software.

**Comment by jeffpiazza** [comment]
I agree, plenty of groups do this.  It's pretty high on my list of new features.

**Comment by jeffpiazza** [comment]
I think this got fixed a while ago, I just never closed the issue.
78adf4ac40eb11f48d814ed66ca83aadf9632b94
