### ISSUE TITLE
Issue with Replay Kiosk not showing video when set to replay kiosk.

### ISSUE THREAD

**Issue by dlohin** [jeffpiazza/derbynet#275]
Are there any tips for troubleshooting the instant replays not triggering.  This was working last year without any issues but isn't working this year.  I did run an apt-get update on the Raspberry PI thinking that I would get all the latest code.  I am using HTTPS with the self-signed certificate.  When I go to the replay kiosk I can see video fine and then when I proceed I make it a "Now Racing" screen.  I can see the FPS showing up in the bottom right.  When the timer is triggered the places and times come up but I never get an instant replay.  I was using a MacBook Pro with an M2 Max and get the same results in .  Thinking it was something with the M2 Max I switched to my old Intel based model and it didn't help.  I have now tried Safari, Chrome and Firefox.  Is there anything I can do to troubleshoot this issue?  The console shows this below, I am not sure if it means anything to you.

* Replay message: HELLO
replay.php:144 Viewer id is viewer-0ltqanb73v95
circular-frame-buffer.js:115 g_recorder value has changed, so stopping 13:06:54 recorder.
circular-frame-buffer.js:133 stop_recording for 13:06:54
 Forcing a reload, because page (kiosks/now-racing.kiosk) != current kiosk_page (kiosks/identify.kiosk)
replay.php:216 * on_replay
replay.php:218 ** root= undefined , g_video_name_root= 
circular-frame-buffer.js:133 stop_recording for 13:07:13
circular-frame-buffer.js:59 13:07:13 not recording in recording_callback
circular-frame-buffer.js:185 Playback from 13:07:13: repeat=2, playback_rate=0.5
circular-frame-buffer.js:187 last_recorded_frame_index = 34
circular-frame-buffer.js:188 Last frame time = 141410.218
circular-frame-buffer.js:189 Start goal = 137410.218
circular-frame-buffer.js:200 start_index = 162
circular-frame-buffer.js:253 Playback from 13:07:13 done (once)
replay.php:195 Uploading video undefined.mkv
replay.php:205 video upload success:
replay.php:206 Object
circular-frame-buffer.js:253 Playback from 13:07:13 done (once)
circular-frame-buffer.js:267 Playback from 13:07:13 fully complete (2 time(s))

<img width="1680" alt="Screenshot 2023-12-03 at 1 28 13 PM" src="https://github.com/jeffpiazza/derbynet/assets/20578548/832ce207-29e1-4472-a885-93c566ddf716">

**Comment by BigDawgDave** [comment]
I'm running into a similar issue with a fake roster, fake timer setup. Derbynet Server is on a Raspberry pi 4 8GB and the replay kiosk is a Microsoft surface, using the local camera.  The races are running fine in the simulation, I have the FPS in the lower right corner of the replay kiosk window on the surface but the replay is never kicking off. Local Asus router dedicated only to the derbynet environment.

**Comment by dlohin** [comment]
I was also using the fake roster functionality if that helps.  I updated to the version of software that was pushed yesterday to apt-get, I haven't had a chance to test it out though.

**Comment by jeffpiazza** [comment]
Sorry for this!  I've tracked it to 6bada5b6559fc97c089a9837f0087e0aafedf8d3 (from Nov 19), which (I swear!) I did test, but apparently I missed something.  I'll have a fix up later tonight.

**Comment by dlohin** [comment]
All good!  I have worked with paid "enterprise" support that wasn't as responsive as this.  When the code makes it to the apt repo let me know and I will test for you.  Our derby is in January and the replays were so exciting to the cub scouts!  I can't wait.

**Comment by jeffpiazza** [comment]
This should be fixed in the latest build, available for download.

**Comment by BigDawgDave** [comment]
Just verified, working well now with the latest build.  Thanks so much for all the effort.
