### ISSUE TITLE
Latest Docker Build Crashing: /bin/bash: line 1: php-fpm81: command not found

### ISSUE THREAD

**Issue by icyspace** [jeffpiazza/derbynet#276]
I had version 9 up and running using the docker build on docker hub.  I updated recently to the latest version that was release 3 days ago and now the container crashes with this error message 

/bin/bash: line 1: php-fpm81: command not found

I have tried installing on a local server and then also on azure both are producing the same error.

**Comment by jeffpiazza** [comment]
It looks like the Alpine Linux image updated to PHP 8.2 from 8.1.  There isn't a generic php-fpm command to pick the current one, although maybe something more clever could be done in the start-up command.

**Comment by jeffpiazza** [comment]
Sorry, this'll take another few minutes to resolve.

**Comment by jeffpiazza** [comment]
Should be good now.  Please let me know if you continue to have trouble.

**Comment by icyspace** [comment]
> Should be good now. Please let me know if you continue to have trouble.

Yes looks good.  Thank you for addressing so quick.
