### ISSUE TITLE
Mobile Barcode

### ISSUE THREAD

**Issue by sokgt500** [jeffpiazza/derbynet#277]
Can there be a way to create the barcodes for mobile check-in, so race leaders or parents can pick up a barcode, scan it, fill out their name, rank, and optional picture of car

**Comment by jeffpiazza** [comment]
I'm not sure what you're asking for here exactly.  It sounds like maybe you're suggesting having barcodes for racers that haven't registered in advance?  If that's the request, I'm not sure how that's different from just clicking the "New Racer" button on the check-in page.  (The "fill out their name" part, at least, suggests the need for a keyboard, as opposed to some kind of headless set-up.)

Alternatively, maybe you're thinking of a QR code that gets projected (or emailed) to the whole room, and allows parents/racers to self-register?

**Comment by sokgt500** [comment]
Hello Jeff,

Thank you for taking the time to reach out to me. Here is what I wanted to
do and where I am coming from. I am open to suggestions or a change in the
process.

We use GPRM with our Best Tracks track. I wanted to take the derbynet and
change our check-in process. My goal was to use the check-in and car photos
as part of the derbynet running on a remote docker container and using a
published web URL to a landing page for the parents to do the voting only.
We are using the names and card numbers from the derbynet to make the GPRM
roster and race brackets.

Since we do a a few different races, one for our unit, one for our district
then we also go out to another district and host one for a low-income
district. That last one is the hardest as we do a clinic 1 day then the
following day we do a race. So we buy them a car, take tools out to cut
them then we race them the following day for that group.

Since I am having an issue finding where it is pulling the IP address with
in the derbynet or be able to make a static address for access to the
software and all of its different parts. It makes it hard to use the remote
link for all aspects of this. So What I would like to do, is make like 200
barcodes, so then it can be scanned in by the parents, they can enter the
Scout's name and rank, and Take pictures of the car from their camera. Then
when they are ready to turn over the car, one of the unit/event leaders and
take that barcode, scan it in for the check-in.

We then use the award voting area with all of the pictures from the
check-in to use as the different votes that all of the event staff can
access via the Cloudflare tunnel back to the docker container I have
created as that seems to only work with the 1 https IP address

If this helps or if you have questions or suggestions then please let me
know.
