### ISSUE TITLE
Mac Install - Apache could not be started

### ISSUE THREAD

**Issue by klooney84** [jeffpiazza/derbynet#278]
I followed the install instructions (including running the auto configurator) and when starting the server via MAMP I get an error stating "Apache could not be started". If I select NGINX it runs perfectly fine but it loads the MAMP webpage and not the derby net main server page.

I'm running Ventura 13.6.3 on a 2017 15in MacBook Pro.

**Comment by jeffpiazza** [comment]
In the /Applications/MAMP folder there's a logs folder that should contain the apache logs.  Hopefully that'll offer some hints what's happening.  Please upload, if you can.

Also it might be helpful to upload httpd.conf from the /Applications/MAMP/conf/apache folder.  (The DerbyNet installer tries to update this config file to locate the document root, and there might have been a MAMP update that makes this fail.)

**Comment by klooney84** [comment]
I sorted the apache issue (had to delete all apache processes and restart MAMP). I believe the https.conf is not being updated by the autoupdate but not sure what to look for. File attached (converted to .txt to upload).
[httpd.txt](https://github.com/jeffpiazza/derbynet/files/13800259/httpd.txt)

**Comment by jeffpiazza** [comment]
The httpd.conf you attached looks as expected, except for the DocumentRoot value.  In the MAMP preferences, under "Server", there's a place to set the document root; it's possible that this somehow caused the httpd.conf value to be overwritten.

If you stop and quit MAMP, re-run the little "Configure MAMP for DerbyNet" application (in /Applications/DerbyNet) and then re-launch MAMP, do things get better?

Where you said "I sorted the apache issue", does that mean you have a working installation now?

**Comment by klooney84** [comment]
The MAMP document root points to Applications ▹ MAMP ▹ htdocs, is this correct? It's the same location before and after running the "Configure MAMP for DerbyNet" script. 

It's running correctly (I think) except I can't figure out how to open the main page of derby net. In MAMP when I click on WebStart it opens up the MAMP overview page.

**Comment by jeffpiazza** [comment]
Set the Document Root to /Library/WebServer/Documents/derbynet.

I'm not sure how you got yourself into this state, but I'm going to tentatively close this as being something specific to your installation.
