### ISSUE TITLE
Unable to set SlideShow Slides 

### ISSUE THREAD

**Issue by sokgt500** [jeffpiazza/derbynet#281]
I cannot get the Kiosk to show pictures of the racer's cars or any other pictures than the default image. I have tried manually moving pictures into the data/event/slides directory with no change. 

I have also moved out of a docker container and tried doing a fresh install on a Raspberry Pi with the same results. 

![Kiosk](https://github.com/jeffpiazza/derbynet/assets/130488451/5ac2ed8d-bd88-40fa-a383-c48f44ad890f)

**Comment by sokgt500** [comment]
So I have cleared that dir and created moved the files back into it. and its the same thing with the Car Phots that I am trying to get as a car slideshow on the Kiosk under Slideshow for a remote system that will be connected to projectors.

![image](https://github.com/jeffpiazza/derbynet/assets/130488451/f1657622-52c5-4a29-9e97-edbf86b5fab3)


in the /var/log/nginx/error.log file I am getting the following repeating.

2024/01/11 15:08:34 [error] 582#582: *4917 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function str_starts_with() in /var/www/html/derbynet/inc/path-info.inc:103
Stack trace:
#0 /var/www/html/derbynet/inc/path-info.inc(119): enumerate_non_title_slides()
#1 /var/www/html/derbynet/ajax/query.slide.next.inc(46): next_slides()
#2 /var/www/html/derbynet/action.php(86): include('/var/www/html/d...')
#3 {main}
  thrown in /var/www/html/derbynet/inc/path-info.inc on line 103" while reading response header from upstream, client: ::1, server: _, request: "GET /derbynet/action.php?mode=slide&file=&query=slide.next&_=1704997087608 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "localhost", referrer: "http://localhost/derbynet/kiosk.php?address=40f31942"

2024/01/11 15:08:44 [error] 582#582: *4917 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function str_starts_with() in /var/www/html/derbynet/inc/path-info.inc:103
Stack trace:
#0 /var/www/html/derbynet/inc/path-info.inc(119): enumerate_non_title_slides()
#1 /var/www/html/derbynet/ajax/query.slide.next.inc(46): next_slides()
#2 /var/www/html/derbynet/action.php(86): include('/var/www/html/d...')
#3 {main}
  thrown in /var/www/html/derbynet/inc/path-info.inc on line 103" while reading response header from upstream, client: ::1, server: _, request: "GET /derbynet/action.php?mode=slide&file=&query=slide.next&_=1704997087611 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "localhost", referrer: "http://localhost/derbynet/kiosk.php?address=40f31942"

2024/01/11 15:08:54 [error] 582#582: *4917 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function str_starts_with() in /var/www/html/derbynet/inc/path-info.inc:103
Stack trace:
#0 /var/www/html/derbynet/inc/path-info.inc(119): enumerate_non_title_slides()
#1 /var/www/html/derbynet/ajax/query.slide.next.inc(46): next_slides()
#2 /var/www/html/derbynet/action.php(86): include('/var/www/html/d...')
#3 {main}
  thrown in /var/www/html/derbynet/inc/path-info.inc on line 103" while reading response header from upstream, client: ::1, server: _, request: "GET /derbynet/action.php?mode=slide&file=&query=slide.next&_=1704997087614 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "localhost", referrer: "http://localhost/derbynet/kiosk.php?address=40f31942"

2024/01/11 15:09:04 [error] 582#582: *4917 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function str_starts_with() in /var/www/html/derbynet/inc/path-info.inc:103
Stack trace:
#0 /var/www/html/derbynet/inc/path-info.inc(119): enumerate_non_title_slides()
#1 /var/www/html/derbynet/ajax/query.slide.next.inc(46): next_slides()
#2 /var/www/html/derbynet/action.php(86): include('/var/www/html/d...')
#3 {main}
  thrown in /var/www/html/derbynet/inc/path-info.inc on line 103" while reading response header from upstream, client: ::1, server: _, request: "GET /derbynet/action.php?mode=slide&file=&query=slide.next&_=1704997087617 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "localhost", referrer: "http://localhost/derbynet/kiosk.php?address=40f31942"

2024/01/11 15:09:14 [error] 582#582: *4992 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function str_starts_with() in /var/www/html/derbynet/inc/path-info.inc:103
Stack trace:
#0 /var/www/html/derbynet/inc/path-info.inc(119): enumerate_non_title_slides()
#1 /var/www/html/derbynet/ajax/query.slide.next.inc(46): next_slides()
#2 /var/www/html/derbynet/action.php(86): include('/var/www/html/d...')
#3 {main}
  thrown in /var/www/html/derbynet/inc/path-info.inc on line 103" while reading response header from upstream, client: ::1, server: _, request: "GET /derbynet/action.php?mode=slide&file=&query=slide.next&_=1704997087620 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "localhost", referrer: "http://localhost/derbynet/kiosk.php?address=40f31942"

**Comment by jeffpiazza** [comment]
str_starts_with was introduced in PHP 8.  That it's undefined implies you're running PHP 7.x or earlier.

The Debian installer for DerbyNet probably should enforce the use of PHP 8 or later.

The docker image at https://hub.docker.com/r/jeffpiazza/derbynet_server is definitely built with PHP 8, so you could try that to confirm the issue quickly.

**Comment by sokgt500** [comment]
So right now this is on a raspberry pi. Will spin up a docker container later today or tomorrow. Ideally I should be able to just update the php to 8 on the pi

**Comment by sokgt500** [comment]
So I did a PHP update to 8.2 on the PI and now it does cycle through the photos, however, it still gives that default car at the end/beginning. 

Is there a way to remove that default car image as seen with the opening issue?

**Comment by jeffpiazza** [comment]
A custom slide named 'title' (possibly with an extension, e.g., title.jpg or title.png) will replace the default title slide.

Bear in mind that the browser may cache an image like this, and continue to show the old slide for a long-ish time after changing to a new one.  Try a different browser (or maybe "stealth mode") if this is suspected.

**Comment by sokgt500** [comment]
I have tested in 2 different browsers and its the same results. I am looking for for the title.jpg/title.png as we speak. Here is also the tails of the logs from the nginx/error.log

tail -f /var/log/nginx/error.log
#3 {main}
  thrown in /var/www/html/derbynet/inc/path-info.inc on line 103" while reading response header from upstream, client: ::1, server: _, request: "GET /derbynet/action.php?mode=slide&file=&query=slide.next&_=1704997103682 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "localhost", referrer: "http://localhost/derbynet/kiosk.php?address=40f31942"
2024/01/12 06:01:44 [error] 582#582: *21341 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function str_starts_with() in /var/www/html/derbynet/inc/path-info.inc:103
Stack trace:
#0 /var/www/html/derbynet/inc/path-info.inc(119): enumerate_non_title_slides()
#1 /var/www/html/derbynet/ajax/query.slide.next.inc(46): next_slides()
#2 /var/www/html/derbynet/action.php(86): include('/var/www/html/d...')
#3 {main}
  thrown in /var/www/html/derbynet/inc/path-info.inc on line 103" while reading response header from upstream, client: ::1, server: _, request: "GET /derbynet/action.php?mode=slide&file=&query=slide.next&_=1704997103685 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "localhost", referrer: "http://localhost/derbynet/kiosk.php?address=40f31942"

2024/01/12 07:51:52 [error] 583#583: *1965 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key -134 in /var/www/html/derbynet/inc/kiosks.inc on line 91; PHP message: PHP Warning:  Undefined array key -59 in /var/www/html/derbynet/inc/kiosks.inc on line 91" while reading response header from upstream, client: 192.168.0.26, server: _, request: "GET /derbynet/kiosk.php?id=%251hjuv31ct HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "192.168.0.175", referrer: "http://192.168.0.175/derbynet/kiosk-dashboard.php"

**Comment by sokgt500** [comment]
I have also listed out the /var/lib/derbynet/event/ folder with its contents to be seen.

/var/lib/derbynet/2024/Pack 226 $ ls -R
.:
cars  derbynet.sqlite3  imagery  logs  racers  slides  videos

./cars:
slide  -Speedy.jpg  -Steve_1.jpg  -Steve.jpg

./cars/slide:

./imagery:

./logs:

./racers:
0-work  200x200

./racers/0-work:

./racers/200x200:

./slides:
Aiden.jpg  Nick.jpg

./videos:

**Comment by jeffpiazza** [comment]
You probably understood this, but just to be sure: /var/lib/derbynet/2024/(something)/slides/title.jpg (or .png, etc.) is the custom title slide we're talking about.

The error message from 2024/01/12 06:01:44 is presumably from before the upgrade to PHP 8; it's the same "undefined function str_starts_with()" we saw earlier.

The one from 2024/01/12 07:51:52 is just a warning, from the code that tries to generate memorable names for kiosks.

**Comment by sokgt500** [comment]
> You probably understood this, but just to be sure: /var/lib/derbynet/2024/(something)/slides/title.jpg (or .png, etc.) is the custom title slide we're talking about.
> 
> The error message from 2024/01/12 06:01:44 is presumably from before the upgrade to PHP 8; it's the same "undefined function str_starts_with()" we saw earlier.
> 
> The one from 2024/01/12 07:51:52 is just a warning, from the code that tries to generate memorable names for kiosks.

That is correct. However, I do not see that png file listed in the directory here. I can reboot the PI again to see if it rebuilds this file, however I doubt it will based on what I can tell. This means that it seems to be pulling this image from a different location as a placeholder or something.

**Comment by jeffpiazza** [comment]
The custom title slide (./slides/title.jpg or the like) would be provided by you.  You could, for example, download https://en.wikipedia.org/wiki/Cub_Scouting_%28Boy_Scouts_of_America%29#/media/File:Cub_Scouting_(Boy_Scouts_of_America).svg and rename to ./slides/title.svg

As I re-read https://github.com/jeffpiazza/derbynet/issues/281#issuecomment-1889273120, I guess you're asking for removal of the title slide altogether.  I'm afraid there isn't (presently) support for that.

**Comment by sokgt500** [comment]
Gotcha, Correct, I was wanting that slide image removed from the slide show all together so only the "cars" would show in the slideshow.

Currently I have 3 cars in the slide show but 4 images, that would be the 3 I provided and the default image.

**Comment by sokgt500** [comment]
@jeffpiazza -- I want to say thank you for your help. I  found where it is pulling the default placeholder image and replaced it with our Pack Logo image. Now when it ends/starts the cycle of the cars it starts with our unit logo. 

File Location is "/var/www/html/derbynet/Images/Cub\ Scouts/slides/title.png" should anyone else what to do the same. 

Again thank you for all of your support on this. This project is awesome and I know that I have made some changes unique to my unit and request.  Out of this issue, the only request that I would like to see added is in the Settings menu that would give users to add a png image for their tile and regardless of the upload name, as part of the update it would rename it to "title".png
