### ISSUE TITLE
NewBold Turbo Timer - Unfinished Heat issue - Win 11

### ISSUE THREAD

**Issue by majora15** [jeffpiazza/derbynet#286]
Doing some testing to prepare for our pinewood derby in 2 weeks.  We have the NewBold Turbo Timer, communication is over usb.  When I run through a race that has a "car not finished" the timer doesn't  reset.  When looking at the timer logs it looks like there is an issue.  The log I'm providing has a successful race, and then a race that Lane 4 never completes.

Is there an additional setting or a setting I need to remove from the start up to fix this issue?

start java -jar derby-timer.jar -n COM5 -d NewBold -delay-reset-after-race 10 -newline-expected-ms 10 pack442.xxxxxxxxxxxxxx/derbynet

[timer-20240115-0936.log](https://github.com/jeffpiazza/derbynet/files/13940687/timer-20240115-0936.log)

**Comment by jeffpiazza** [comment]
It looks like the Turbo timer is prone to reporting a "lane 0" result, and it's not being handled very gracefully by derby-timer.jar.  I'll have a fix up shortly.

**Comment by majora15** [comment]
[timer-20240115-0953.log](https://github.com/jeffpiazza/derbynet/files/13942185/timer-20240115-0953.log)
[timer-20240115-1002.log](https://github.com/jeffpiazza/derbynet/files/13942186/timer-20240115-1002.log)
Here are two more log files if you need additional.

**Comment by jeffpiazza** [comment]
Try downloading the latest .jar from https://derbynet.org/download/derby-timer.jar and see if that doesn't work better for you.

**Comment by majora15** [comment]
I'll check it out now.

**Comment by majora15** [comment]
It looks like it is doing the same thing, I downloaded from the above url.

[timer-20240115-1350.log](https://github.com/jeffpiazza/derbynet/files/13942628/timer-20240115-1350.log)

**Comment by majora15** [comment]
Something else I tested, and the results were as I expected.  If you have 2 cars jump the track and don't finish, lets say lane 1 and 4 complete.  It will have the scores for lanes 1 and 4, then two 0 lanes with 0.000 time.  

Let's also say that the worst thing happens, only 1 lane completes, the same thing happens, only lane 1 has results and there are 3 lane 0s.  Now in that unlucky of even I would probably record the time of lane 1 on paper, rerun the race, then go back and modify lane 1's time.  This would totally be a fluke thing, but definitely will happen.  

Now you do have the other worst case that all 4 don't finish... maybe there was a big pile up on the I-4. :D  You would have 4 - 0s with 0.0000 times.  Very unlikely, and most likely would redo that run.  However, it looks like the java timer app "crashes" and receive anything until you restart it.  Easy solution there is to just restart the timer, but maybe some people won't think of it.  

I know nothing about coding in java or I could help with the solution but count me in as a tester for this timer.  I know the "manual" process to get this working again, so if you don't get around to fixing it before our derby race no worries.  

Thank you for all the work you do to support everyone!

**Comment by majora15** [comment]
Attaching all 3 scenarios as stated above from the logs:

[timer-20240115-1912-two-cars-don't-finish.log](https://github.com/jeffpiazza/derbynet/files/13944296/timer-20240115-1912-two-cars-don.t-finish.log)
[timer-20240115-1915-three-cars-don't-finish.log](https://github.com/jeffpiazza/derbynet/files/13944297/timer-20240115-1915-three-cars-don.t-finish.log)
[timer-20240115-1925-four-cars-don't-finish.log](https://github.com/jeffpiazza/derbynet/files/13944298/timer-20240115-1925-four-cars-don.t-finish.log)

**Comment by lordscarlet** [comment]
We just ran our event this weekend. We had one car that consistently DNF. After 10s DerbyNet would call the race done, and give the DNF a time of 10s. 

I _believe_ that is set in the settings, under _Previous heat linger time (sec.) for "Now Racing"_.

**Comment by majora15** [comment]
What timer are you using?  From the logs I have attached the java timer is crashing because of how the results are being sent.  I already have that setting set.

**Comment by lordscarlet** [comment]
I am _far_ from an expert, so I could easily be wrong.

I don't know what our timer is, and I don't have it in my possession to check, unfortunately.

**Comment by majora15** [comment]
I understand, at least I have a workaround for the time being.

**Comment by majora15** [comment]
@jeffpiazza wondering if the download of the java timer I downloaded had the fix it in since I am still able to reproduce the issue.

**Comment by jeffpiazza** [comment]
You may have gotten an older version if you used the https://derbynet.org/download/derby-timer.jar link previously.  (The link has been fixed now, and should reliably be the latest version.)

`java -jar derby-timer.jar -v`

will tell you the jar version.  The (hoped) fix is present in any of the v9.0 series, but not earlier versions.
