### ISSUE TITLE
Unable to delete racing groups

### ISSUE THREAD

**Issue by aliasjmac** [jeffpiazza/derbynet#287]
I have been trying out different racing group configurations to determine what would be optimal for our event.  However, I am unable to delete any racing groups as the button has no effect.  When viewing the developer console there is an error related to the "length" attribute, and then after clicking the "Delete Group" button another error is thrown for "toLowerCase".  Both errors do not provide any indication to the user that something went wrong, simply nothing happens after the button is clicked other than the modal dialog closing.  See screenshot of the console attached.

Unfortunately this forces me to have to reinitialize the database after each round of testing.

<img width="1767" alt="Screenshot 2024-01-15 at 6 33 24 PM" src="https://github.com/jeffpiazza/derbynet/assets/5931506/24b4035f-1edd-41b8-b885-0d7b4da60ce6">

**Comment by jeffpiazza** [comment]
Sorry for this!  Should work for you now.

**Comment by jeffpiazza** [comment]
(You may need to "force reload" the page -- hold "shift" key and reload the page.

**Comment by aliasjmac** [comment]
That worked.  Thanks for the quick assist!
