### ISSUE TITLE
derby-timer download link bad

### ISSUE THREAD

**Issue by Dulanic** [jeffpiazza/derbynet#296]
Hello,

The link to download to derby-timer is not available. Can this be corrected? As a backup could this be added to the github also? We ran a pinewood derby yesterday and thats when I found the link was no good, so we had to fall back to manual.

Unfortunately, dummy me didn't realize it was also in the windows download.

https://derbynet.org/download/derby-timer.jar

**Comment by jeffpiazza** [comment]
Thanks for pointing this out!

Fixed now.
