### ISSUE TITLE
Feature Request: Ability to delete photos for racers

### ISSUE THREAD

**Issue by Jchuchla** [jeffpiazza/derbynet#298]
You can delete the actual files, but then it just gives a broken link.  I would like the see the ability to delete the files as well as the reference to them.  Restoring the default images in the process.

We've run into a few cases where a parent decides they don't want the kid's picture shown after we've already taken the photo during the checkin.

**Comment by jeffpiazza** [comment]
Visit the "Racer Photos" page, find the racer, drag the photo from the racer back to the pool of unassigned photos.

(I guess it's not completely obvious how to do this.)
