### ISSUE TITLE
Racer photos path truncated at default GPRM location

### ISSUE THREAD

**Issue by jasonmuzzy** [jeffpiazza/derbynet#3]
The default location for racer photos for Grand Prix Race Manager is %userprofile%\Documents\Lisano Enterprises\GrandPrix Race Manager\Images.  Specifying this path in racemgr setup results in it being truncated:
![image](https://cloud.githubusercontent.com/assets/15488120/10865077/97cb7fa8-7fbd-11e5-9708-1756986a3b7e.png)

After submitting and coming back:
![image](https://cloud.githubusercontent.com/assets/15488120/10865082/bb686e8a-7fbd-11e5-8f21-5b45f959939d.png)

**Comment by jeffpiazza** [comment]
I think this gets resolved if you visit setup.php page and upgrade schema, which will allow longer strings to be stored in the database.

/JEP

**Comment by jeffpiazza** [comment]
Storing longer directory strings needs a schema upgrade, as the default GPRM database schema allows only 50 characters for RaceInfo entries.

DerbyNet settings now tests for truncation.  When detected, truncation now produces an error message that includes suggestion to upgrade schema.

Fix available in build 359 and later.

**Comment by jasonmuzzy** [comment]
Perfect, upgrading the schema worked.  I had avoided updating the schema because I wasn't sure what it did and didn't want to mess up integration with GPRM.

On Nov 8, 2015, at 5:13 AM, jeffpiazza <notifications@github.com<mailto:notifications@github.com>> wrote:


Storing longer directory strings needs a schema upgrade, as the default GPRM database schema allows only 50 characters for RaceInfo entries.

DerbyNet settings now tests for truncation. When detected, truncation now produces an error message that includes suggestion to upgrade schema.

Fix available in build 359 and later.

-
