### ISSUE TITLE
ODBC with GPRM database not updating "On Deck" kiosk screen

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#30]
If I use the GPRM database with DerbyNet the now racing screen seems to work fine but the on deck schedule only shows the name of the group being raced and the current heat number but does not show the schedule.  Not sure if this is an issue/bug or if it is the lack of a feature but if you are integrating DerbyNet with GPRM one great featured would be the ability to have a screen for the car wranglers showing the schedule and current cars on deck.

**Comment by jeffpiazza** [comment]
This used to work, with at least older versions of GPRM.  (In fact, an on-deck display for the wranglers was the original reason for doing any of this.)

Could you email me your GPRM database?

**Comment by heatvent** [comment]
My pack uses GPRM v13.  I am just using the program at home in demo mode
with the sample database (attached).

**Comment by jeffpiazza** [comment]
Fixed in build 680

**Comment by heatvent** [comment]
Thanks Jeff ... seems to be working great!
