### ISSUE TITLE
slideshow not working on Pi based kiosk

### ISSUE THREAD

**Issue by Jchuchla** [jeffpiazza/derbynet#302]
The kiosk slideshow is not working on at least two kiosks running on Raspberry Pi 3B with the Chromium browser.  It displays the default yellow car image, but never advances to show actual scout and car photos.
The slideshow does work properly in the edge browser on windows.

**Comment by nirvdrum** [comment]
@Jchuchla When did you install the _derbynet-server_ package? I ran into an issue with the slideshow on my Pi and tracked it down #281. I manually upgraded to PHP8 about 5 min. before our derby (not advised) and that fixed the problem for me. There are new .deb files published in the last few weeks that set PHP8 as an installation dependency and, as such, should get you a working system.

If you're still seeing problems after the upgrade, please add the error message from _/var/log/nginx/error.log_.

Unfortunately, I was still seeing a sporadic 500 error from a kiosk after the PHP upgrade. But, it went from not working at all to working almost all of the time. In the remaining failure cases I found the log didn't have much useful in it. I'll probably have to start modifying code to see if I can debug the issue.

**Comment by Jchuchla** [comment]
I updated it about a week before my derby. So somewhere around 1/14. I updated the whole pi os on the server. I’ll have to look into the php version. Not sure what it’s on. 
I wasn’t getting web server errors. It was just that slideshow kiosk that never advanced from the stock image of the yellow car. The slideshow kiosk does work reliably from my laptop in the edge browser. So I suspect it’s probably not a server side issue. Probably something related to the chromium browser on the Pi. But that’s just my suspicion.

**Comment by jeffpiazza** [comment]
I assume you have at least one checked-in racer, i.e., something to see besides the title slide?  A recent change (#291) is to show only check-in racers, not just arbitrary racers with pictures.

Check the browser console for javascript complaints.

**Comment by jeffpiazza** [comment]
I'm going to assume this was a PHP version issue, as suggested.  Feel free to re-open if that's not the case.
