### ISSUE TITLE
Micro Wizard Fast Track not being offered a "start race" button in UI

### ISSUE THREAD

**Issue by JeffHoogland** [jeffpiazza/derbynet#313]
I'm using a Micro Wizard fast track and the racing UI is not offering a "start race" button as detailed in the docs. 

When I press the toggle to say "racing" it triggers the remote start though. For now I'm just toggling race mode off / on to get the desired results.

Screenshot of the UI I'm seeing:

![image](https://github.com/jeffpiazza/derbynet/assets/3093360/a4147d85-fc7c-400d-a798-7a63dfee6562)

If I recall correctly this button displayed properly with my same track last year when I used the latest version of derby net.

**Comment by jeffpiazza** [comment]
Are you sure you're setting --fasttrack-automatic-gate-release?  If not, that would explain both observations (no start button, and gate releases immediately on setting racing).

Are you using the in-browser interface or the java jar?

Do you have any timer logs you can share?

**Comment by JeffHoogland** [comment]
The -fasttrack-automatic-gate-release launch argument was what I needed - sorry about that. I really need to write my own docs for the track so I don't forget about it in the year between races.

At any rate, thanks for the fast response and the fantastic software.
