### ISSUE TITLE
Clone Settings

### ISSUE THREAD

**Issue by nirvdrum** [jeffpiazza/derbynet#315]
We run our derby annually and I like to keep each year's database separate from one another. While the roster/registration list changes year-to-year, the rest of the configuration is essentially the same. To get started, I have to keep switching back and forth between the current and previous year to make sure I've carried settings forward (e.g., track configuration and heat setup).

It would be really handy if I could either export and import settings or clone a DB (with new picture & video directories) and clear out the registration info. It'd be a nice convenience. I don't mind taking manual steps, but I fret over possibly not having copied all of the necessary settings forward.

It'd be nice if that could extend to racing groups and awards as well. There isn't a whole lot of variation in how we run the derby year-to-year.

**Comment by jeffpiazza** [comment]
The "About" page lets you export your current settings, including racing groups and awards, as a preferences file.  On the settings page there's a field to upload the preferences.

This is a new feature this year, so I'm not 100% certain that "preferences" means the same thing to all users.  The preferences file is editable text, but the only description of the content is the block comment in website/inc/preferences.inc.

Feedback welcome!

**Comment by jeffpiazza** [comment]
Feedback still welcome on exporting and re-using a preferences file, but I'm going to mark this issue resolved for now,
