### ISSUE TITLE
Slideshow not working in latest build

### ISSUE THREAD

**Issue by chunter2** [jeffpiazza/derbynet#319]
I'm running build 1706 and can't get the slideshow to work.  It's worked all other years.  I get a 500 Ajax error that shows up on the screen.  Any help?  I just finished a derby tonight and have one in the morning.  The rest of the kiosks I used seem to work fine including now racing and awards presentation.  

Thanks

**Comment by jeffpiazza** [comment]
Check the error log on the server (e.g., /var/log/nginx/error.log on Linux, or (I think) UniServerZ\core\apache2\logs on Windows) to get more detail on the 500.  

If you're using any custom slides or imagery, check their permissions and types, and maybe try removing individually.?

**Comment by jeffpiazza** [comment]
If you're using a replay kiosk with remote camera, and that happens to be the slideshow kiosk you're talking about, try force-reloading both the camera page and replay page.  The 1706 build specifically has some javascript changes affecting these page, and a browser may be caching an older version of the javascript.

**Comment by chunter2** [comment]
Thanks for the info. I'll check the logs first thing in the morning. I left the hardware all set up. I was using the replay kiosk with a remote camera but only force reloaded the relay kiosk. I did open another kiosk on another machine but couldn't get the slides to go there either. That one was just a regular kiosk. I'll see what I can find. I did notice the replay seemed to be delayed and quite grainy compared to other years. I was using wireless so I'll try wired tomorrow.

**Comment by chunter2** [comment]
Here's what's in the nginx error log.  
```
Stack trace:
#0 /var/www/html/derbynet/inc/path-info.inc(119): enumerate_non_title_slides()
#1 /var/www/html/derbynet/ajax/query.slide.next.inc(46): next_slides()
#2 /var/www/html/derbynet/action.php(86): include('/var/www/html/d...')
#3 {main}
  thrown in /var/www/html/derbynet/inc/path-info.inc on line 103" while reading response header from upstream, client: 192.168.2.64, server: _, request: "GET /derbynet/action.php?mode=slide&file=&query=slide.next&_=1708175811609 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "192.168.2.2", referrer: "https://192.168.2.2/derbynet/kiosk.php?id=%251hmq9aef2"
2024/02/17 08:20:14 [error] 1005#1005: *552925 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function str_starts_with() in /var/www/html/derbynet/inc/path-info.inc:103
Stack trace:
#0 /var/www/html/derbynet/inc/path-info.inc(119): enumerate_non_title_slides()
#1 /var/www/html/derbynet/ajax/query.slide.next.inc(46): next_slides()
#2 /var/www/html/derbynet/action.php(86): include('/var/www/html/d...')
#3 {main}
  thrown in /var/www/html/derbynet/inc/path-info.inc on line 103" while reading response header from upstream, client: 192.168.2.163, server: _, request: "GET /derbynet/action.php?mode=slide&file=&query=slide.next&_=1708175764788 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm.sock:", host: "192.168.2.2", referrer: "https://192.168.2.2/derbynet/kiosk.php"
```

**Comment by jeffpiazza** [comment]
That's a sign that you're still running PHP 7.

**Comment by chunter2** [comment]
I'm on Ubuntu 20.04.  I don't see it in the regular repos.

**Comment by jeffpiazza** [comment]
If you want to monkey-patch inc/path-info.inc for today, replace the 'enumerate_non_title_slides' definition with this one:

```// Search for files in the $dir directory that alphabetically follow $current_slide
function enumerate_non_title_slides($dir, $current_slide) {
  $results = array();
  if (is_dir($dir) && is_readable($dir)) {
    $files = scandir($dir);  // Sorted by default
    foreach ($files as $file) {
      if ($file > $current_slide && $file[0] != '.' &&
          substr($file, 0, 6) != 'title.') {
        $results[] = $file;
      }
    }
  }
  return $results;
}
```

**Comment by chunter2** [comment]
Seems to be working.  Thanks.  I'll update Ubuntu to 22.04 after today's meet.

**Comment by chunter2** [comment]
Just to update, the meets went great. Thanks again for your great software and for the quick help.  I just undated to Ubuntu 22.04 and put the code change back and the slideshow still works now that php8.1 is installed.  Should that maybe be a dependency for your derbynet-server package in your ppa?  
Couple other things I noticed.  On the last heat of a Den the Pause icon comes up before the results of the last heat are displayed and then goes away for the 10 second delay and then comes back again.  Nothing major, just something I noticed.  
I was also able to use the Reschedule option a couple times and it worked great.  Not sure if there's a way to indicate that it's running with some sort of waiting wheel?  I clicked the button a couple times before noticing it was actually running.  
We abandoned the replay this year since even though I hard wired it, it was still grainy and slow.  It only showed the cars coming halfway down the track.  I'm going to spend some time looking into this now that I've upgraded Ubuntu.  

Thanks again.

**Comment by chunter2** [comment]
Just an update on my ppa comment.  I had forgotten you had the following in your documentation.  
```
wget -q -O- https://derbynet.org/debian/derbynet.gpg | \
sudo apt-key add -
echo "deb [arch=all] https://derbynet.org/debian stable main" | \
sudo tee /etc/apt/sources.list.d/derbynet.list > /dev/null
sudo apt-get update
```
Seems apt-key add is deprecated in Ubuntu 22.04.  I think your first line should look something like this now based on the documentation.    
```
wget -q -O- https://derbynet.org/debian/derbynet.gpg | \
sudo tee /etc/apt/trusted.gpg.d/derbynet.gpg > /dev/null
```
Thanks

**Comment by jeffpiazza** [comment]
Thanks for the thought.  The docs were updated as you suggest a while ago.  (d3b10dfd02693b0b16ea568aad351fc586eedd4d)

**Comment by chunter2** [comment]
Strange, https://derbynet.org/builds/Installation-%20Debian.pdf still shows the apt-key add part.

**Comment by jeffpiazza** [comment]
The call to str_starts_with was removed in 50a790f767dacac1292ef8716a80c8545f8ac984
