### ISSUE TITLE
Timer Status Unconfirmed

### ISSUE THREAD

**Issue by mrdangran** [jeffpiazza/derbynet#320]
HI loving the software !  Only issue is my timer goes from green to yellow sometimes. We have a New Bold Turbo timer. 

When I scan and click NewBold, I get this in the logs: 
+18.853* INT Probing for NewBold DT, TURBO, or DerbyStick on port 0 (built-in port)
+20.855* INT IDENTIFIED NewBold DT, TURBO, or DerbyStick

Then the status goes to 
Timer Status Unconfirmed.

After awhile maybe something else I do, it sometimes goes to green sometimes it just gets stuck on Unconfirmed. 

Is this a timer issue or anything else I can try?
Thank you!!!
Simon

**Comment by jeffpiazza** [comment]
The NewBold devices, like the older (P-Series) FastTrack timers, are "compatible" but not discoverable as many of the other supported timers are.  Here's the footnote in https://derbynet.org/builds/docs/Timer%20Operation.pdf about this:

> Because these timers don’t respond to probes from the host computer, the identity of the timer can’t be confirmed until some recognizable communication from the timer occurs (e.g., a heat result is transmitted from the timer).  The status of the timer will show as “UNCONFIRMED” until that happens.

The status should turn green if you run a test heat, and it shouldn't change back to yellow unless the timer gets disconnected.

**Comment by mrdangran** [comment]
ah ok that makes sense. that's probaby why it seemed to randomly turn green was because I ran a test heat.

**Comment by mrdangran** [comment]
Ok ran a test heat and I see the timer go off and displays the run time.  But what I'm seeing in the logs is "Prepare heat 1,13,1,1,1 Fake Lions" (using the fake roster) but it doesn't seem to take in the data from the timer because it's still disconnected?

**Comment by jeffpiazza** [comment]
Just after a heat completes, if there's another heat scheduled to follow it, a "prepare heat" will be sent for the new heat.  That's likely what you're describing.

I'm going to close this for now.  Feel free to re-open or start a new issue if there's something that's really not working for you.
