### ISSUE TITLE
Timer times out if a car fails to reach end of track

### ISSUE THREAD

**Issue by romipetrelis** [jeffpiazza/derbynet#33]
First off - thank you for this software. It is terrific!

We were running some test cars down the track tonight to make sure everything works before our derby tomorrow. It's a 4 lane track. These test cars are real clunkers, so they were slow. In fact, one of them could not make it to the end of the track. In that case, we found that the timer app was timing out and *not* recording times even for the 3 cars that did make it across the line. We were able to consistently re-create the problem.

We've got a workaround: we'll have somebody standing by to wave their hand across the finish line in the event that a car fails to make it to the end, but I figured I'd open an issue to see if there's a setting I'm missing, a better workaround, etc.

Thanks again for this system!

**Comment by jeffpiazza** [comment]
What kind of timer are you using?

Could you please send some timer log files from your experiments?

**Comment by romipetrelis** [comment]
We're using The Champ.

[timer-4166296025014722514.log.zip](https://github.com/jeffpiazza/derbynet/files/1669763/timer-4166296025014722514.log.zip)

The attached timer log has a few instances of the "Race timed out" message.

**Comment by jeffpiazza** [comment]
This is fixed in the 682 build.  (Upon timing out, the app sends a "force end of race", but now actually waits more than a millisecond for a response!)
