### ISSUE TITLE
One person enters multiple cars

### ISSUE THREAD

**Issue by PorkChopExpress86** [jeffpiazza/derbynet#334]
We have used this software at events, and it has worked great. However, at our last event we had people enter multiple cars and when you enter a car with a duplicate name in the same "den" or race group, it will not create another car. There will be a second car with the same car ID and car name even though you enter a different car ID and car name. Our work around was to add a number to the first or last name to get the car entry to work.

**Comment by jeffpiazza** [comment]
Do you have a database that shows this?  Or detailed steps to reproduce?

The code for recording a new racer (whether by import or through the check-in page) is indifferent to duplicate names, more or less intentionally.  There's always room for bugs, but the behavior as described is a surprise.  It also doesn't match what I observe in some casual testing just now.

**Comment by PorkChopExpress86** [comment]
We do a manual check in using the racer check in. If you enter the same first and last name twice, then the second car will be entered with the same car id as the first car and the same car name. 
![Car 1](https://github.com/jeffpiazza/derbynet/assets/29725019/759c3e2c-e9e3-4808-98ab-387adabba377)
![Car 2](https://github.com/jeffpiazza/derbynet/assets/29725019/d0b67e1d-4f38-4e67-89d8-938c15eb6bb8)
![Checkin](https://github.com/jeffpiazza/derbynet/assets/29725019/96524c51-a43f-47cf-8f75-10397a16ba4a)
