### ISSUE TITLE
Subgroups not showing on Racer Check-In page

### ISSUE THREAD

**Issue by anwright** [jeffpiazza/derbynet#335]
First, thanks for all the effort you put into this, it's excellent!

I'm trying to play around with subgroups and aggregate groups, just to figure out how they work and see what options exist.  While doing this, I discovered that--when `Custom racing groups` and `Use Subgroups` are selected on `racing-groups.php`--no changes made to group names show up on `checkin.php`.  Subgroups never show up in the dropdown list for racers, and renaming groups (or subgroups) has no effect anywhere on that page.

Reproduced using a docker build that I pulled down today, on fully up to date Debian 12.  [Barebones database attached that exhibits the problem.](https://github.com/jeffpiazza/derbynet/files/14767058/derbynet.sqlite3.gz)

**Comment by jeffpiazza** [comment]
Thanks for the database -- that really helps.

The Check-In page is offering "Group 1" and "Group 2", which were the original names of the two subgroups, before they were renamed "Sub Group 1" and "Sub Group 2", respectively.  The single racing group also bears the name "Group 1", just to add extra confusion.  (There's only one racing group, though, so there's no "Group 2" racing group.)

The issue isn't so much that the Check-In page doesn't show subgroups, it's that the subgroups didn't get fully renamed as they should have.

**Comment by anwright** [comment]
Oddly, if you rename groups on the racer check-in page, that also seems to have no effect on the group management page; new groups created from racer check-in don't show up in group management, and renamed groups aren't reflected there either.
