### ISSUE TITLE
Questions about late arrivals.

### ISSUE THREAD

**Issue by Chipper2** [jeffpiazza/derbynet#336]
When checking in late arrivals.  Does the system always run them by themselves?

<img width="578" alt="Screenshot 2024-03-30 at 5 54 01 PM" src="https://github.com/jeffpiazza/derbynet/assets/86256338/d861a0da-40fa-43b5-b547-007aa6a8b677">

<img width="674" alt="Screenshot 2024-03-30 at 5 54 26 PM" src="https://github.com/jeffpiazza/derbynet/assets/86256338/f4a5d6f2-905e-4614-a3c3-c7256834ca86">

I late checked in these two.

<img width="1188" alt="Screenshot 2024-03-30 at 5 55 39 PM" src="https://github.com/jeffpiazza/derbynet/assets/86256338/850dd343-e05f-43f3-96aa-97f637088851">

Press Adjust Schedule

<img width="441" alt="Screenshot 2024-03-30 at 5 56 09 PM" src="https://github.com/jeffpiazza/derbynet/assets/86256338/f74e2dcd-e8ab-4a04-87aa-849c9b1b9e07">

Heats jump to 9 of 13.

<img width="742" alt="Screenshot 2024-03-30 at 5 57 46 PM" src="https://github.com/jeffpiazza/derbynet/assets/86256338/f4040f45-e1f8-4d86-a52b-801ba67b70eb">

And then races them separately.

<img width="645" alt="Screenshot 2024-03-30 at 5 58 09 PM" src="https://github.com/jeffpiazza/derbynet/assets/86256338/bff09cc6-d0ef-43e0-aec2-de2fd1d9949a">

Now, I think I figured something out.  If you late check in one racer. Then click Adjust Schedule. It will add to heats.  Then go back in and add more racers, it will schedule additional heats with two racers like normal.  So just a odd thing.

I also noticed that if you choose the Abbreviated single-run-per-car schedule option, it only holds for the first scheduled racers, If you reschedule, the reverts back to racer ones down each track.

**Comment by jeffpiazza** [comment]
It largely depends on where you are in the round when the new racer shows up.  If there's only one heat left to run in the original schedule, there's going to be N-1 single-racer heats added, where N is the number of lanes on the track.  

If the racer gets added with most of the round yet to run, then chances are the adjuster can work out a change that adds only one heat, and no one races alone.
