### ISSUE TITLE
Kiosk Identify Auto-generated names do not match Kiosk Dashboard

### ISSUE THREAD

**Issue by jpetrykanyn** [jeffpiazza/derbynet#337]
While setting up the weeks race, I noticed the Kiosk names shown on the identify page did not match the ones listed in the Kiosk Dashboard. I was able to work around this by testing a change to each but think this need to be checked.
Example from a test today:
Kiosk - loose beggar
Kiosk Dashboard - narrow scale
I am running in a cloud instance setup by Jeff for Cisco March of Dimes with Pi Zero 2W running V9 on Buster as Kiosks.
Is there anything I can collect to help troubleshoot?

**Comment by jeffpiazza** [comment]
This happened to me, too, recently, and was also reported by another user.

The identifier is based in part on the port used by the browser to contact the server.  That port isn't reliably constant, hence the problem.
