### ISSUE TITLE
Specific lanes

### ISSUE THREAD

**Issue by ScouterAndy** [jeffpiazza/derbynet#34]
Could there be a way to specify using only certain lanes of the track (ie. Use only lanes 1, 3 and 5 of a six-lane track due to clearance issues, sensor problems, etc.) When making a schedule?  Is this possible?

**Comment by jeffpiazza** [comment]
I've thought about this a little, but wanted to hear a little more about the use case(s).  Do you have clearance or sensor issues?  Do you expect to use the same lane pattern every year?

**Comment by ScouterAndy** [comment]
The sensor issue we have had on occasion and there were cases where we needed to drop a lane for that reason.

The more common reason is when we race Scout 18 Wheelers which have wider allowable dimensions than cars... and that means we have to use alternating lanes since trucks in adjacent lanes wouldn't fit.  This we do all the time and every year... and so we'd use lanes 1, 3 and 5... only when we race that class (trucks) but not all the classes of regular cars where we can use all 6 lanes.

**Comment by ScouterAndy** [comment]
We ran into the lane issue today with the trucks... it means we have to use GPRM for that class since I can't find a way to handle it in DerbyNet.

**Comment by jeffpiazza** [comment]
This feature will be part of v4.0

**Comment by ScouterAndy** [comment]
Downloaded the latest source and merged in the changes... tested with the simulated timer and it worked very well.  We'll test at this weekend's races and confirm any issues.  Thanks for the quick response!
