### ISSUE TITLE
MIcrowizard K3 Timer Eror/LASr issue

### ISSUE THREAD

**Issue by srozga** [jeffpiazza/derbynet#341]
We are running Derbynet against a new Microwizard K3 timer. The timer works fine standalone. Derbynet detects the timer and seems to work, but when the cars cross the finish line I get errors on the timer "Eror, LASr, Eror, Lasr" in the 4 lanes. I contacted Microwizard and they said the following:

The software is sending a reset laser command and your timer has no laser gate.  You can send a command LA0 to the timer to disable the laser gate check (Timers are sent with this setting off, the software must have enabled it by sending the command LA1).

I looked in timer settings but didn't see an option that may be relevant. Any documentation on how to accomplish this?
Thanks
-Szymon

**Comment by jeffpiazza** [comment]
I'm assuming you're running a reasonably recent derbynet timer interface?

During the initial timer discovery, there should be a "RF" command sent.  If the third bit in the response is zero (e.g., 1101 1111), an internal flag gets set to record that there's no laser gate, and the laser reset (LR) commands should not be sent.  If you can find that snippet of the logs, I'd be interest in seeing what the timer is reporting here.

Of more immediate help for you:

Turning on fasttrack_automatic_gate_release will stop the laser reset.  It will also offer a button in the UI to open the gate, but that button won't work unless you actually have an automatic gate release.

Turning on no_gate_watcher should also stop the laser reset.  With this flag on, the UI won't be able to tell when a heat has started, but will still recognize a reported heat finish.

**Comment by srozga** [comment]
Hi, yes. I am running on a windows laptop. The java interface is not working, not sure why. However, the chrome timer interface works. Your workaround using fasttrack_automatic_gate_release works, thank you. 

The log is below. The timer is reporting 1111.

```
+57.070* INT Probing for FastTrack K- or Q-series on port 0 USB x067b/x23a3
+57.210S --> RV
+57.218S <-- RV
+57.248S <-- Copyright Micro Wizard 2021
+57.269S <-- Model: Q1 v0.07.12
+57.292S <-- Serial Number: 29845
+57.295S <-- *
+57.322* INT IDENTIFIED FastTrack K- or Q-series
+57.335S --> RE
+57.343S <-- RE
+57.343S <-- *
+57.444S --> N1
+57.451S <-- N1
+57.454S <-- *
+57.548S --> N2
+57.556S <-- N2
+57.559S <-- *
+57.652S --> RF
+57.660S <-- RF
+57.671S <-- 1111 1111
+57.674S <-- *
+58.021S --> RG
+58.028S <-- RG1
+58.031S <-- *
+58.280S --> RG
+58.287S <-- RG1
+58.297S <-- *
+58.539S --> RG
```

**Comment by jeffpiazza** [comment]
If you can find it, I'd also like to see the timer's response to the LR command itself.

**Comment by srozga** [comment]
@jeffpiazza  I've tried this numerous times, but I cannot get this error to show up again. I disabled the fasttrack_automatic_gate_release flag and the timer is behaving correctly now. ¯\_(ツ)_/¯

**Comment by jeffpiazza** [comment]
For next release, adding a fasttrack-disable-laser-reset option to avoid having to use workarounds.
