### ISSUE TITLE
Some heats are skipped with all times set to 10sec

### ISSUE THREAD

**Issue by fastjames** [jeffpiazza/derbynet#35]
First, thanks very much for putting together this great piece of software. We had our pack derby today and it went very well, with most of the problems being record-keeping (some paper is still involved). However, I did notice one unusual behavior that I wanted to report. In two instances, after a heat was completed the next heat was very quickly marked as complete, with all participants getting a heat time of 10 seconds. 

I was able to remedy the problem by doing the following from the race dashboard:
1. Click "Previous Heat"
2. Click "Manual Results"
3. Click "Discard Results"

This reset the heat so we could rerun it, but it also exposed a follow-on problem. I was using another raspberry pi as a kiosk for the main venue display(s) and it was displaying the "now-racing" kiosk page. When I dropped the incorrect heat times, they remained on the kiosk screen. The kiosk did eventually update once the race continued on. I'll log this in a separate issue but I wanted to note it here as well.

I haven't made any changes to the derbynet server, so any log files on there should still be available. We are using a "The Champ" timer plugged into a Serial <-> USB adapter, plugged into my laptop because I couldn't get the pi to recognize it last night. After the first instance I tried to keep a close eye on the activity of the race crew, and when the second skip happened I did not see any crew members manipulating the start gate (which was my first suspicion).

Any ideas on where to start with troubleshooting? I'm happy to dig out any log or config files that might point the way.

**Comment by fastjames** [comment]
I looked at the output of the timer applet, and I do see this activity (first IDLE is for the heat before the skip):
> IDLE >--PREPARE_HEAT_RECEIVED--> MARK
> MARK >--GATE_CLOSED--> SET
> SET >--GATE_OPENED--> RUNNING
> RUNNING >--RESULTS_RECEIVED--> IDLE
> IDLE >--PREPARE_HEAT_RECEIVED--> MARK
> MARK >--GATE_CLOSED--> SET
> SET >--GATE_OPENED--> RUNNING
> 2018-02-24_11:36:45: ****** Race timed out *******
> RESULTS_OVERDUE >--RESULTS_RECEIVED--> IDLE
> IDLE >--PREPARE_HEAT_RECEIVED--> MARK
> MARK >--GATE_CLOSED--> SET
> SET >--ABORT_HEAT_RECEIVED--> IDLE
> IDLE >--PREPARE_HEAT_RECEIVED--> MARK
> MARK >--GATE_CLOSED--> SET
> SET >--GATE_OPENED--> RUNNING
> RUNNING >--RESULTS_RECEIVED--> IDLE

From that activity, it really looks like the gate was accidentally tripped and then reset. What's strange is that I see two more instances of that "Race timed out" log message, but no other instances of the "ABORT_HEAT_RECEIVED" message even though I followed the same procedure both times.

**Comment by jeffpiazza** [comment]
Could you please attach the timer app log file(s) (cleverly named timer-<date-time>.log)?

**Comment by fastjames** [comment]
[timer-20180224-0802.log.gz](https://github.com/jeffpiazza/derbynet/files/1763014/timer-20180224-0802.log.gz)

**Comment by fastjames** [comment]
There's the log. In my notes I wrote that scouts heat 24 was the first time it happened, and there does appear to be some timeout-related activity around heat 24 (line 82572). It looks like someone might have closed the gate at 11:36:33 and bumped it back open at 11:36:34. However, I don't see a gate closed message until until after the timeout and I don't remember seeing it open the entire time (I think they were placing cars on the track during that interval).

**Comment by jeffpiazza** [comment]
The timer reported the gate closed at 11:36:33.848 and then open again by 11:36:34.071; in other words the gate was perceived to be closed for no more than 0.22 seconds.  (As I understand it, that's longer than mechanical switch bounce, which would be on the order of 10 milliseconds, but I can easily imagine that the process of latching the gate closed could create brief open and closed states.)

Once the app perceived that the gate had closed and then opened, it assumed a race had started, and stopped polling the gate state.  10 seconds later, it forced a result from the timer; the timer gave all 9.999 values.  (Almost certainly, the gate actually closed again right after it was reported open, while the race crew staged the cars.)

I think the right way to address this is to have the app ignore any sufficiently-brief gate state changes.  (Obviously, as good as I'm sure your race crew is, the couldn't have staged cars in 0.22 seconds!)

**Comment by fastjames** [comment]
Indeed, your comment is especially funny because our cubmaster is _incredibly_ meticulous about placing cars (I know he wants all scouts to have a fair start). Another possibility -- the gate switch is dirty and maybe breaking / making contact intermittently during the close? I plan to use some contact cleaner on it prior to our upcoming race next weekend.
