### ISSUE TITLE
Restarting a heat does not update now-racing kiosk screens

### ISSUE THREAD

**Issue by fastjames** [jeffpiazza/derbynet#36]
During our recent derby, we encountered a case (https://github.com/jeffpiazza/derbynet/issues/35) where we needed to rerun a heat. Using the procedure described in the linked issue, I was able to rerun the heat successfully. However, I noted that when I prepared to rerun the heat, the now-racing kiosk (which was displayed on our large screens) still displayed the erroneous times from the previous run of the same heat.

I think I was able to clear the times by switching kiosk displays a few times, but it would be much more helpful if discarding a heat's times also triggered an update on the kiosks.

**Comment by fastjames** [comment]
Are you sure the change that closed this is the right one? It seems to be a change to the photostand.sh script.

**Comment by jeffpiazza** [comment]
Sorry, fixing the wrong commit now.

**Comment by fastjames** [comment]
Thanks, very grateful for this quick fix!
