### ISSUE TITLE
Updating .deb files results in HTTP 403 on all derbynet pages

### ISSUE THREAD

**Issue by fastjames** [jeffpiazza/derbynet#37]
I'm prepping for a race, so I wanted to update to the latest derbynet release. I started with my server instance (bad idea) and updated the deb the easy way:

> wget https://jeffpiazza.org/derbynet/builds/derbynet-server_v3.0-690-20180219.deb
> sudo dpkg -i derbynet-server_v3.0-690-20180219.deb

The install completed, but when I tried to reload the About page I got this response:
"You have chosen to open about.php which is: Binary file (5.9kb) ..."

I tried to reload the derbynet home page and got the response
> 403 Forbidden

The first thing I tried was removing and reinstalling the derbynet-* debs. I saw no change in results, so I dug in a little bit deeper.

It seemed like nginx was not handling the derbynet PHP files properly, so I looked at `/etc/nginx/sites-available/default` and noted that the file didn't have any lines including `derbynet/location.snippet`. I tried adding it in the `location / {` block, which fixed the home page but not the about page. Strangely, after a shutdown (not reboot) and restart, the About page is working as well. I'm going to be working on it today so hopefully I'll uncover any other problems today as well.

I wanted to report this in case another user who's not familiar with nginx config files runs into the same problem. Was my mistake just not removing the debs before installing on the first run? I know the instructions are clear on removing the v2 (derbynet) debs before installing v3, but I didn't see anything about doing that for v3 upgrades.

**Comment by fastjames** [comment]
I should also mention that I made one other change to `/etc/nginx/sites-available/default`: the `index` directive didn't include index.php and I added it. Now I suspect that wasn't necessary since the derbynet.snippet should cover all derbynet files, but I didn't want to leave it out of my problem description.

**Comment by jeffpiazza** [comment]
I don't really know what happened here, but I'm going to close this issue unless there's reason to believe it's reproducible.

**Comment by fastjames** [comment]
I'm not sure how easy it will be, but I ran into the same problem when I uninstalled the v3 debs and installed v4.0 via `apt`. I was in a hurry (and glad that I documented this) so I didn't have a chance to collect much data, but it was the same problem I had last time.
