### ISSUE TITLE
Interleave Heats vs Interleave Racers

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#46]
Hi, it looks like the "Interleave heats from different dens" basically runs only a single den in each heat and just sets it up so that you don't do 6 tiger heats in a row, you to Tiger, Wolf, Webelos 1, etc.

Is it possible to interleave the racers? I.e. run a master schedule that puts each racer down each lane once but mixes up the various dens in each heat.  Results are of course tracked by den so that best in den awards can be given out.  The advantages are similar to interleaved heats such that it has each racer racing through out the event vs just when it's den is racing.  However, if you interleave the racers or disregard den in setting the schedule, you end up with the overall race taking less time because you are using all lanes as much as possible.  There is a bigger difference if you have small dens (say 2 in a particular den) and multiple lanes (like 6).

Maybe I am missing how this works but the race schedule seems to be den focused.

**Comment by jeffpiazza** [comment]
What you're describing is "subgroups": go to Set-Up -> Settings and update like so:
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/13140826/45255990-dfa0fc00-b35d-11e8-81ef-a34efbe01d3a.png">

You'll need to re-import your racers, using the den name as the subgroup.

**Comment by heatvent** [comment]
Thanks Jeff.  On the standings page you have the columns/titles as follows:

Place | Car Number | Name | Group | In Group | In Subgroup | Heats | Average | Best | Worst

If I use the above settings, I can see just the Pack and not the Den the racer is in.  Would it be possible to add another column identifying the Subgroup (if subgroups are used) or to swapout subgroup instead of group to address this..

Place | Car Number | Name | Group | In Group | Subgroup | In Subgroup | Heats | Average | Best | Worst

Thanks

**Comment by jeffpiazza** [comment]
Note that this update is NOT in the v3 release branch, but will be incorporated in the v4 release
