### ISSUE TITLE
Feature Request: Guest Pages

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#47]
Just a suggestion.  It may be nice to have a public page or pages that the parents could log in to where they could see and click through standings, current race, on deck without a password by just joining the network and going to a "guest" page.

**Comment by jeffpiazza** [comment]
When accessed without credentials, the main page offers on-deck and results-by-racer views, for exactly this use case.  Standings is a little more controversial, as it may make an award ceremony anti-climactic.

If there's some other specific view you're looking for, re-open and we'll discuss further.
