### ISSUE TITLE
Feature request: Derbynet works with public cloud providers.

### ISSUE THREAD

**Issue by jemessecar** [jeffpiazza/derbynet#49]
As a system administrator, I want to be able to install and run derbynet with a public cloud provider, so I can utilize the software in any environment that is available.

**Comment by jeffpiazza** [comment]
I'm not sure what you're asking for here.  It's a simple matter to create a VM (Linux or Windows, install derbynet on it, and then point a browser (or multiple browsers) at the VM.  (You need something onsite to connect the track timer to -- I'm not aware of any timers that can make an internet connection directly.)

Is there something else you're looking for?

**Comment by jeffpiazza** [comment]
Absent any clarification after a month, I'm going to close this.
