### ISSUE TITLE
Feature request: Derbynet works GrandPrix Race manager while storing data in the public cloud

### ISSUE THREAD

**Issue by jemessecar** [jeffpiazza/derbynet#50]
As a system administrator, I would like to be able to store my data securely in the public cloud, but utilize derbynet to display race results created by GrandPrix Race Manager running on a computer connected to the race timer.

**Comment by jeffpiazza** [comment]
Maybe things have changed, but, to my knowledge, GPRM keeps a database on the machine it's running on.

You can connect derbynet to that same database and point browsers to derbynet to display results.

Generally speaking, GPRM plus derbynet still only create minimal load on a machine.
