### ISSUE TITLE
Feature Request / Question: Late Racer Checkin

### ISSUE THREAD

**Issue by skusa108** [jeffpiazza/derbynet#52]
Apologies if this has been addressed before, but is there a way to handle racers who check in late (after the race has been scheduled and started)? I have been looking at website/ajax/action.schedule.reschedule and the associated code in js/coordinator.js but I haven't grasped how its functioning yet. Thanks!

**Comment by jeffpiazza** [comment]
It's still an aspirational goal, but I never got this to a working state.  

There's an argument to made for removing action.schedule.reschedule, given that it's non-functional.  I guess I keep hoping to find some time to work on it.

**Comment by skusa108** [comment]
Understood, thanks. I'll see if our pack has enough coding capability to contribute to this functionality.
