### ISSUE TITLE
Car Tags Including Lion Den Icon Only

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#54]
Jeff, when printing the car tags there is an option to "Draw Icon for Rank." I have my Roster setup with the appropriate Den levels (Tiger, Wolf, etc.).  The car tags show only the Lion Den icon on all car tags regardless of the den. Is there something else to designate "Rank."  BTW, the list of scouts on the printables page (http://localhost/print.php) has an empty box to the right of each name.  Perhaps this is supposed to be the rank.

**Comment by heatvent** [comment]
I setup a new file and somehow it is working now.  Not sure what is making this happen. I did 2 test files and one was showing Lion den tags on everything, the other was showing Tiger Cub tags on everything.  Now it seems to be working correctly on my third file and I can't figure out what caused it on the other 2 tests.

**Comment by heatvent** [comment]
Jeff, I tried the new build and the numbers above work correctly.  One thing I noted was DerbyNet was assigning numbers automatically upon import and for some reason it is one rank off (lions were 100-200, tigers 200-300, and so on).  I am using the Pack as the group and Den subgroups so that I can interleave all ranks in the schedule.

**Comment by jeffpiazza** [comment]
If a new racer doesn't have a car number, one gets assigned by default, with the first group or subgroup defined getting numbers in the 1xx range, second group or subgroup in 2xx, etc.  You're right that this scheme doesn't match up very well with car tag numbering if the groups start with Lions; I may have to rethink this a little.  

In the meantime, you probably want to take more positive control of car numbering.
