### ISSUE TITLE
Suggestion: Move Settings prior to Roster Import in Set-Up

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#56]
The setup instructions order tell the user to consider the organization structure before the impart of the roster.  I am using sub-groups and have played around with the software a bit so I know to go into settings and to change the group to Pack and Sub-Group to Den before I import the roster so I am sure to align the correct import column headings.  Seems to me it may be logical to either have settings prior to import roster in order on the setup page, or to have a separate button to configure organization.  IMHO, this would improve the setup flow a bit especially for someone new and the setup page and setup instructions would be in the same order.  Just a suggestion.  For me, I know to go to settings first but it took some trial and error before figuring this out.

Thanks again for all the hard work on this program!

**Comment by jeffpiazza** [comment]
I think this is moot now, with the introduction of partitions.  (That was part of the point of partitions, in fact: changing the race structure shouldn't require re-importing the racer data.)
