### ISSUE TITLE
Speed Trophies Use of Pack and Den vs Group and Subgroup on Settings Page

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#57]
Should the trophy settings on the settings page say per "Super-Group" and "Group" rather than Pack or Den.  If the user is using the Pack as the Group and Dens as sub-groups, this wording becomes confusing.

![image](https://user-images.githubusercontent.com/19480678/50709276-e0f0e580-102c-11e9-9ab8-e367026159e1.png)

**Comment by jeffpiazza** [comment]
The word choices are made when the page is generated, but not dynamically updated in response to uncommitted changes to the label names.  I agree that's confusing, and should be changed.

**Comment by heatvent** [comment]
Thanks Jeff!
