### ISSUE TITLE
GPRM Uses SQLite databases ... can you share with DerbyNet

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#61]
So I was going to try to share a database with GPRM but your instructions seem to cover .mdb databases and GPRM 18 seems to save only in sqlite format.  Is it still possible to share?

**Comment by jeffpiazza** [comment]
Sharing should still work, but some testing is probably in order.  If you can figure out where the sqlite file is, the "Sharing a Database on MacOS" section of the "Sharing a Database With GPRM" document describes how to point DerbyNet at it.

**Comment by heatvent** [comment]
Thanks will give it a try when I get home.

**Comment by heatvent** [comment]
Using the sqlite connection seems to work fine!

**Comment by heatvent** [comment]
Closing issue.
