### ISSUE TITLE
Missing Kiosks table doesn't get healed

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#62]
So I setup a dedicated pi as a kiosk.  Installed derbynet-extras.  There was not derbynet.conf in /boot so I copied it from /etc/derbynet.conf and edited in nano for my server address.  When the pi boot it seems to connect to the server but gives the following error:

exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: Kiosks' in C:\Users\Matt\Desktop\DerbyNet\UniServerZ\www\inc\kiosks.inc:65 Stack trace: #0 C:\Users\Matt\Desktop\DerbyNet\UniServerZ\www\inc\kiosks.inc(65): PDO->prepare('SELECT page, na...') #1 C:\Users\Matt\Desktop\DerbyNet\UniServerZ\www\kiosk.php(16): kiosk_page('RaspberryPi') #2 {main}

I am using the latest build. I also tried a fresh download / setup and get the same error.  Any ideas on why this isn't working.  Windows firewall has an exception so I don't think it's that.  I can also directly access the derbynet server from the pi with no issues.

Thanks

**Comment by jeffpiazza** [comment]
I presume you're using a GPRM sqlite database here?

DerbyNet adds a database table called Kiosks.  If that table isn't present, it's supposed to try to create it on the fly, but apparently that's not working.

You should be able to work around this by creating the table by hand.    Create the table with this SQL command:

CREATE TABLE Kiosks ( address VARCHAR(50), name VARCHAR(200), page VARCHAR(200), last_contact INTEGER NOT NULL); 

You may need to download the SQLite command line tools from https://sqlite.org/download.html.

**Comment by heatvent** [comment]
Yes I was using a GPRM sqlite database.  It took a couple of tries, apparently if your database name has spaces in it you need to put in quotes (i.e. sqlite3 "c:\My GPRM Database.sqlite").  I then was able to create the table and the kiosks stopped complaining :).

Thanks for the help.

**Comment by heatvent** [comment]
Closing issue.

**Comment by jeffpiazza** [comment]
I'm reopening this, because the kiosks table is supposed to be created automatically if it's discovered to be missing.  Not sure why that didn't happen in this case.

**Comment by B3DTech** [comment]
This is still an issue with the latest versions of everything.  Derbynet doesn't create the table in GPRM SQLite DB.  I verified that the DB file permissions are full RW for Owner, Group and Other.  Even closed the GPMR software in case it had a strange file lock on it.  Manually creating it works fine though.

**Comment by jeffpiazza** [comment]
Any chance you have the php error log?

**Comment by B3DTech** [comment]
Sure.   I recreated the GPRM database a couple of times testing things out here.  

https://gist.github.com/B3DTech/78e0032a3d341db2a183e4b935aa97f1

**Comment by jeffpiazza** [comment]
I think this may be about not detecting the specific SQL error when using SQLite databases.  I'm hoping 9679dba fixes this; I'd appreciate evidence for or against.

**Comment by B3DTech** [comment]
Getting an exception when loading the kiosk page now:

[09-Jan-2020 12:41:54 America/New_York] PHP Notice:  Undefined variable: e in /Library/WebServer/Documents/derbynet/inc/data.inc on line 261
[09-Jan-2020 12:41:54 America/New_York] PHP Fatal error:  Uncaught Error: Call to a member function getMessage() on null in /Library/WebServer/Documents/derbynet/inc/data.inc:261
Stack trace:
#0 /Library/WebServer/Documents/derbynet/inc/kiosks.inc(85): is_no_such_table_exception(Object(PDOException))
#1 /Library/WebServer/Documents/derbynet/kiosk.php(16): kiosk_page('10.85.146.113+5...')
#2 {main}
  thrown in /Library/WebServer/Documents/derbynet/inc/data.inc on line 261
[09-Jan-2020 12:42:05 America/New_York] PHP Notice:  Undefined variable: e in /Library/WebServer/Documents/derbynet/inc/data.inc on line 261
[09-Jan-2020 12:42:05 America/New_York] PHP Fatal error:  Uncaught Error: Call to a member function getMessage() on null in /Library/WebServer/Documents/derbynet/inc/data.inc:261
Stack trace:
#0 /Library/WebServer/Documents/derbynet/inc/kiosks.inc(85): is_no_such_table_exception(Object(PDOException))
#1 /Library/WebServer/Documents/derbynet/kiosk.php(16): kiosk_page('10.85.146.113+5...')
#2 {main}
  thrown in /Library/WebServer/Documents/derbynet/inc/data.inc on line 261
[09-Jan-2020 12:42:16 America/New_York] PHP Notice:  Undefined variable: standigs_state in /Library/WebServer/Documents/derbynet/kiosk-dashboard.php on line 39
[09-Jan-2020 12:42:16 America/New_York] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /Library/WebServer/Documents/derbynet/kiosk-dashboard.php on line 39
[09-Jan-2020 12:42:16 America/New_York] PHP Notice:  Undefined offset: 1 in /Library/WebServer/Documents/derbynet/kiosk-dashboard.php on line 42

**Comment by jeffpiazza** [comment]
Yup, I noticed this myself this morning, but obviously not early enough.  Should be fixed in 40485284a0f815de9278541c9940b1a1f669d56b.

**Comment by jeffpiazza** [comment]
I think this is fixed now.  Any evidence it's still an issue?

**Comment by B3DTech** [comment]
Nope - works fine now.  Thanks.
