### ISSUE TITLE
Times are cleared from the physical timer almost immediately

### ISSUE THREAD

**Issue by romipetrelis** [jeffpiazza/derbynet#63]
We were doing some test runs tonight and noticed that the times on the physical timer (
we're using The Champ) are being cleared within a fraction of a second of a heat's completion. For example, if there are 4 heats, as soon as heat 1 is finished, the times flash on the physical board and then disappear and the software is waiting for heat 2 to begin. Spectators don't have a chance to see the race results on the physical timer. 

FWIW, At the end of heat 4, the results stay up on the digital timer. Also, when we disconnect the computer from the track, the digital timer keeps showing the results until the physical reset button is pressed. So, we think that `derby-timer` is doing something like sending a "reset for next heat" really fast.

To be clear, the data IS being captured correctly and the web page is immediately ready for the next heat, which is great. But we know that people in the audience are going to be frustrated at not seeing digital timer results. Is there an option I'm overlooking on `derby-timer` to get the software to wait some number of seconds before resetting for the next heat?

[timer-6776888095287695848.log.zip](https://github.com/jeffpiazza/derbynet/files/2777309/timer-6776888095287695848.log.zip)

Thanks in advance!

**Comment by jeffpiazza** [comment]
It looks like clearing the lane mask, which happens as soon as the next heat is teed up, resets the Champ display.  Adding a user-controllable delay should address your concern.

**Comment by heatvent** [comment]
FYI, I noticed the exact same behavior and was starting to look at the timer help to see if there was a way to set a delay.  Glad I saw this come in my email.  If there could be a default delay, maybe 10 seconds would be great.
