### ISSUE TITLE
Java app not working with MicroWizard K2

### ISSUE THREAD

**Issue by everetteallen** [jeffpiazza/derbynet#67]

**Comment by everetteallen** [comment]
I have a MicroWizard K2 version 1 and Cables to Go USB Serial(PL2303 drivers) attached to iMac with .  When I scan the K2 the numbers go dark and no connection is made.  Am I doing something wrong or is this timer not supported?

**Comment by jeffpiazza** [comment]
Per offline discussion: Everette had a faulty timer.
