### ISSUE TITLE
Need HTTPS to capture images at checkin on mobile devices

### ISSUE THREAD

**Issue by mashcraft** [jeffpiazza/derbynet#71]
When using an Android or Apple mobile device to collect images at checkin, the HTTPS protocol is required to enable the camera.

Add a setting for cases where the setup allows for HTTPS (self signed certificate) for these links.

**Comment by jeffpiazza** [comment]
Are you asking for a setting that redirects HTTP requests to HTTPS, or for something else?

https://jeffpiazza.org/derbynet/builds/docs/Webcams%20and%20Secure%20Contexts.pdf describes the creation and use of self-signed certificates; maybe this needs to be more prominently positioned.

**Comment by mashcraft** [comment]
While I did not see that document, I did nearly exactly what it directs to setup a self signed certificate on Debian using nginx and got it working.  

Even with this, the user could easily connect via http by default and still have the camera not work.  Changing the browser URL to https when you see the error about camera support requiring https also leads to confusion as the browser caches the content and you have to force a reload via https. 

To make this more user friendly in the case where a self signed cert is enabled, it would be helpful if there were a derbynet setting that would cause https to be used for the links to load the photo capture.
