### ISSUE TITLE
Best Timer weirdness with Java App and 6 tracks

### ISSUE THREAD

**Issue by cwhittl** [jeffpiazza/derbynet#72]
We just had our derby last weekend and the software seemed to be good until night of setup.  Once it was hooked to the timer we got extremely random timer issues.

For a while it would work ok, then it would go down to 4 lanes but 4 random lanes.

We unhooked everything and tested again and again and it would just keep doing different things.

We finally had to give up and move back to the old software.

I unfortunately am not with the pack anymore (son just crossed over Tuesday) so I don't have access to the computer it ran on but thought you would want to know.

Thanks for all your hard work!!

**Comment by jeffpiazza** [comment]
Thanks for the note!

Any chance you could put me in touch with the person who does have the computer?  The timer log files would be really helpful.

**Comment by jeffpiazza** [comment]
Absent more information about what happened, I'm going to chalk this up to some weirdness with the particular device, and close the issue.
