### ISSUE TITLE
Race never ends with The Judge

### ISSUE THREAD

**Issue by AerialBreakSoftware** [jeffpiazza/derbynet#73]
We have DerbyNet connected to The Judge and everything works fine except that a race won't end unless someone resets the finish bridge by pushing the button on top of the bridge. While this will be OK for our Derby, it is prone to error in that if someone locks-in the results by pressing the button before the 10 second max, those racers that didn't actually finish get credited for the shorter time thereby causing an imbalance in the standings or making us go back and adjust the race results.

I'm attaching the timing log from a number of test runs tonight. It would be really nice if the software could force the timing system to end the race after 10 seconds (or maybe 12) so we don't have to worry about it. Alternately, a button on the race management page would also work allowing the timer to end the race from the management dashboard.

It would also be nice if the software would recognize the DNF status for a lane and automatically assign the max time so if the race is prematurely ended, the racer still gets the 10 sec penalty time for a DNF.

[timer-20190228-1855.log](https://github.com/jeffpiazza/derbynet/files/2917544/timer-20190228-1855.log)

**Comment by jeffpiazza** [comment]
Am I correct in thinking this is about DNFs only?  If each lane is triggered, I'm pretty sure the heat ends normally.

I don't have access to a The Judge, so to make further progress, I'm going to need to find someone who can help try out test versions of the timer app.  Volunteers welcome!

**Comment by AerialBreakSoftware** [comment]
You are correct that the main problem is DNFs but that is symptomatic of a bigger problem. DerbyNet and The Judge end up working mostly correct but The Judge requires a reset/end race trigger at the end of the race and DerbyNet lacks the ability to send that signal. The result is that The Judge must be manually reset after every heat and in the case of DNFs, this can cause errors in the results.

A race heat goes like this: DerbyNet is connected to The Judge and is waiting for the race to start. A race official triggers The Judge to start the race. The Judge does a little countdown on a light stack then triggers the release gate. It starts an internal clock timing the race. (I don't think The Judge sends any notice to DerbyNet that the race has started.) As cars pass through the finish gate, The Judge transmits the lane and the time back to DerbyNet. 

The software tracks the results properly but there is a subtle flaw in the interactions here... The Judge leaves the race open until it receives a reset either via the software or by pressing the reset button on the finish gate. At the time of the reset, The Judge sends the last lane time and I'm assuming some additional information. Or maybe it just sends the final termination character. What I know from looking at the DerbyNet log is that the last time (or times in the case of DNFs) only arrive at the point the hardware was reset. This is actually the case regardless of whether all the cars finished or there was a DNF/empty lane. Since DerbyNet has no facility to send that reset command, races _MUST_ be finished by manually pressing the reset button. (You can actually see this happen during the event because the lane times post to the results board as they happen except for the last lane or any DNF lanes. When the reset button is pressed the last lane time will finally post and DerbyNet considers the heat complete.)

For a regular race where all lanes finish, the Scout at the end of the track can press the reset button immediately after the race because all lanes have valid times. For a race with a DNF/empty lane, the Scout must wait for at least 15 seconds after the race start to ensure that The Judge sends DerbyNet times that are greater than the 10 second max race time to ensure the car is assigned the 10 sec DNF time. I originally submitted this because the issue I was having was that Scouts were pushing the reset button when it became obvious that a lane would DNF but that could potentially be just 6 or 7 seconds after the race start. Because The Judge sends the accumulated lane time for DNFs when the reset button is pressed, DerbyNet can't determine that a 6 or 7 second time reported by The Judge is actually a DNF in those cases. So I had to train the Scouts to wait 15 seconds on a DNF/empty lane to ensure the time reported is large enough that DerbyNet assigns the DNF time. Otherwise, DNFs were getting an artificially low DNF time skewing event results. Ultimately I would like to get away from relying on Scouts to finish the race and would prefer that be in the hands of the race operator.

So that is a long explanation to say that I think the simplest way to address this problem is to add a button on screen which allows the DerbyNet operator to send a track reset command to The Judge. If it is in the operator's hands, then the reset can be sent at the appropriate time based on race results eliminating the Scout needing to manually reset the track at the end of a race. It would be great if it could be automatic but I don't think that is possible because of how and when the data is returned.

I have The Judge, obviously, and am very willing to test. I can pull from a branch and test a fix on the real hardware. Our race this year is in mid-Feb so I'm motivated to get this feature added! I can also get a raw serial trace from The Judge for a race if that would help.

If it is OK, I'll drop you a line at the e-mail you have on your Github account to coordinate testing.

**Comment by jeffpiazza** [comment]
Do please email me, and I'm sure we can get this working to where we'd all like.
