### ISSUE TITLE
Ability to do a Semi Grand Final

### ISSUE THREAD

**Issue by ScouterAndy** [jeffpiazza/derbynet#75]
Here's a use case we can't seem to handle.  We have multiple groups for different classes, but sometimes multiple groups for the same class to accomodate things like late registrants (so for example we'll run part A of the class first, and part B of the class last, and put all the late racers in B).     But then our only option to do a combined final is to do ONE grand final round based on the A and B groups... and if these are big groups and we run a lot of racers, what we'd like to do is whittle the list down with a Semi Final, then draw the top n from that to a Final.   But DerbyNet only seems to allow one Grand.

A related use case would be this:   if we split more than one of our classes into an A and B group, we could only combine one of the A/B sets into a Grand Final... and can't do a final for the other A/B split.

Different classes (ie. cars, 18 wheelers, parents, Open class) never race against each other, only within their own class.   So any time we have more than one class split into groups, we can't do a Final for some of them.

**Comment by jeffpiazza** [comment]
I could make guesses, but what does "semi grand final" mean to you?

**Comment by ScouterAndy** [comment]
Sorry, was still editing the note.   See above.

**Comment by ScouterAndy** [comment]
So a Semi Grand Final would be an intermediate round, drawn from more than one group, that could itself still be selected into a Grand Final.

**Comment by ScouterAndy** [comment]
Like this:

CARS A  +   
CARS B  ----  SEMI 1

CARS C  +
CARS D  ---- SEMI 2

PARENTS A  +
PARENTS B  -----  SEMI P (last race, declares winners for Parents)

OPEN A  +
OPEN B   -----  SEMI O (last race, declares winners for Open)


Then take SEMI 1 and SEM2 into a Grand Final (declares overall winners for Cars)
