### ISSUE TITLE
Unexpected results with drop lowest heat and race by points

### ISSUE THREAD

**Issue by jeepin95** [jeffpiazza/derbynet#77]
This is all fake data, names were generated using a random name generator. I ran races by manually, semi-randomly placing each lane with a manual timer site I setup so we could try using this for our rain gutter regatta. Since there isn't an automatic timer, and times are so varied in these races we decided to go on place (points) rather than times. 

In the first method with drop lowest enabled notice that car 10 ties for 5th place, however their total points comes out as 10 when everyone else tied for 5th only has 9 points. On the 2nd table that shows the results with drop lowest disabled car 10 ties for 3rd place rather than 5th, still with 10 points and the now 6th place ties all with 9 points.

This doesn't make sense to me, as based on the points car 10 should have tied for 3rd in both scenarios. In the results, the only other thing that seems to change between modes is that when car 10 is put to 3rd, the next tie is moved to 6th instead of 5th, which does make sense.

How does the drop lowest work, is this only working on time rather than worst ranking? Why was car 10 not placed into the 3rd place tie when their points put them into 3rd place? I'm sorry, I haven't had enough time to dig into how all of that works but from an end-user perspective there seems to be an issue with the ranking in drop lowest mode.

My manual timer site reports times and places, could that be throwing something off? Should I only report places if that is how we want to score?

I've attached the .sqlite database if that helps.

# Results with Drop Lowest enabled

Place | Car Number | Name | Den | In Den | In Pack | Heats | Total Points (1st = 4) | Best | Worst
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
T1 | 23 | Wm Alexis | Wolf |   | T1 | 4 | 13 | 1st | 3rd
T1 | 1 | Deon Cedeno | Lion |   | T1 | 4 | 13 | 1st | 3rd
T3 | 20 | Charlotte Barren | Webelos |   | T3 | 4 | 10 | 1st | 4th
T3 | 8 | Omega Current | Wolf |   | T3 | 4 | 10 | 1st | 4th
T5 | 18 | Kaley Feldt | Wolf |   | T5 | 4 | 9 | 1st | 4th
**T5** | **10** | **Pok Heeren** | **Webelos** |   | T5 | 4 | **10** | 2nd | 3rd
T5 | 30 | Colene Mabe | Webelos |   | T5 | 4 | 9 | 1st | 4th
T5 | 29 | Naomi Mcknight | Bear |   | T5 | 4 | 9 | 1st | 4th
T5 | 15 | Lin Ramero | Webelos |   | T5 | 4 | 9 | 1st | 4th
10 | 2 | Cassey Coop | Tiger |   | 10 | 4 | 8 | 2nd | 4th

# Results with drop lowest disabled

Place | Car Number | Name | Den | In Den | In Pack | Heats | Total Points (1st = 4) | Best | Worst
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
T1 | 23 | Wm Alexis | Wolf |   | T1 | 4 | 13 | 1st | 3rd
T1 | 1 | Deon Cedeno | Lion |   | T1 | 4 | 13 | 1st | 3rd
T3 | 20 | Charlotte Barren | Webelos |   | T3 | 4 | 10 | 1st | 4th
T3 | 8 | Omega Current | Wolf |   | T3 | 4 | 10 | 1st | 4th
**T3** | **10** | **Pok Heeren** | **Webelos** |   | **T3** | 4 | **10** | 2nd | 3rd
T6 | 18 | Kaley Feldt | Wolf |   | T6 | 4 | 9 | 1st | 4th
T6 | 30 | Colene Mabe | Webelos |   | T6 | 4 | 9 | 1st | 4th
T6 | 29 | Naomi Mcknight | Bear |   | T6 | 4 | 9 | 1st | 4th
T6 | 15 | Lin Ramero | Webelos |   | T6 | 4 | 9 | 1st | 4th
10 | 2 | Cassey Coop | Tiger |   | 10 | 4 | 8 | 2nd | 4th

[derbynet.zip](https://github.com/jeffpiazza/derbynet/files/3465426/derbynet.zip)

**Comment by jeffpiazza** [comment]
Thanks for this detailed bug report!

The issue here is that, with "drop each racer's slowest heat," the standing is based on a score computed by dropping a heat, but the displayed "total points" includes all the heats.  

Pok, Kaley, Colene, Naomi, and Lin each have a score of 8 points when their slowest heat is discarded.

Showing the raw total point score is clearly inappropriate when computing standings based on a different score.

**Comment by jeepin95** [comment]
Thanks for the prompt reply, I estimated it was something along those lines. For now I know if we do go with the drop lowest option the rankings are accurate and we just ignore the scores.

Thank you for all the work on this software, we used it last year at our PWD and will be using it in 2 weeks for our RR and it has been great.
