### ISSUE TITLE
Import Roster not working on IE11/Win7

### ISSUE THREAD

**Issue by jeffpiazza** [jeffpiazza/derbynet#78]
willemvl points out that the Import Roster page (and presumably other imports) don't work in Internet Explorer 11 on Windows 7.  Specifically, drag and drop doesn't work, and, even if an importable file is opened via file dialog, the result is just a blinking cursor.

At least part of the issue is likely that the SheetJS shim is not included in DerbyNet.  As IE11 only supports ECMAScript 5 and SheetJS assumes ES6, failure should not be surprising.

**Comment by joncamp** [comment]
Worth noting that Win7 is no longer supported. As noted on https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer, IE11 is there for backward compatibility only.

As such, it may not be worth it to fix this issue. Workaround is to either install a supported OS and browser (ie: Win 10 with Edge, with modern edge based on Chromium), or to install a different browser (Chrome or Firefox)

**Comment by jeffpiazza** [comment]
I think I'm going to pass on fixing this as just not worth the effort.
