### ISSUE TITLE
Fullscreen kiosk URL missing hostname

### ISSUE THREAD

**Issue by jasonmuzzy** [jeffpiazza/derbynet#8]
The URL for the to run in fullscreen kiosk mode is missing the hostname:
![image](https://cloud.githubusercontent.com/assets/15488120/11226396/7269ef40-8d34-11e5-94de-5f977868fb17.png)

Reference issue #5 where protocol was missing (but host was present).  Now protocol is present but host is missing.

**Comment by jeffpiazza** [comment]
Would you send me the output from:

http://localhost/derbynet/kiosk.php?page=kiosks/identify.kiosk

(There’s got to be a host name in there somewhere…)

Thanks!
/JEP

**Comment by jasonmuzzy** [comment]
Here you go:

Kiosk identifier:
::1+64170
1349 x 1753

Array
(
    [PROCESSOR_ARCHITEW6432] => AMD64
    [_FCGI_X_PIPE_] => \\.\pipe\IISFCGI-6b87c312-3d84-4075-bef1-41d877740dac
    [PHP_FCGI_MAX_REQUESTS] => 10000
    [PHPRC] => C:\Program Files (x86)\PHP\v5.3
    [ALLUSERSPROFILE] => C:\ProgramData
    [APPDATA] => C:\WINDOWS\system32\config\systemprofile\AppData\Roaming
    [APP_POOL_CONFIG] => C:\inetpub\temp\apppools\DefaultAppPool\DefaultAppPool.config
    [APP_POOL_ID] => DefaultAppPool
    [CommonProgramFiles] => C:\Program Files (x86)\Common Files
    [CommonProgramFiles(x86)] => C:\Program Files (x86)\Common Files
    [CommonProgramW6432] => C:\Program Files\Common Files
    [COMPUTERNAME] => LAPTOP-PC
    [ComSpec] => C:\WINDOWS\system32\cmd.exe
    [LOCALAPPDATA] => C:\WINDOWS\system32\config\systemprofile\AppData\Local
    [NUMBER_OF_PROCESSORS] => 4
    [OS] => Windows_NT
    [Path] => C:\Program Files\PHP\v5.3;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\jason\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;
    [PATHEXT] => .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
    [PROCESSOR_ARCHITECTURE] => x86
    [PROCESSOR_IDENTIFIER] => Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
    [PROCESSOR_LEVEL] => 6
    [PROCESSOR_REVISION] => 2a07
    [ProgramData] => C:\ProgramData
    [ProgramFiles] => C:\Program Files (x86)
    [ProgramFiles(x86)] => C:\Program Files (x86)
    [ProgramW6432] => C:\Program Files
    [PSModulePath] => C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
    [PUBLIC] => C:\Users\Public
    [SystemDrive] => C:
    [SystemRoot] => C:\WINDOWS
    [TEMP] => C:\WINDOWS\TEMP
    [TMP] => C:\WINDOWS\TEMP
    [USERDOMAIN] => WORKGROUP
    [USERNAME] => LAPTOP-PC$
    [USERPROFILE] => C:\WINDOWS\system32\config\systemprofile
    [VS140COMNTOOLS] => C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
    [windir] => C:\WINDOWS
    [FCGI_ROLE] => RESPONDER
    [HTTP_CONNECTION] => keep-alive
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, sdch
    [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.8
    [HTTP_HOST] => localhost
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [APPL_MD_PATH] => /LM/W3SVC/1/ROOT
    [APPL_PHYSICAL_PATH] => C:\inetpub\wwwroot\
    [AUTH_TYPE] => 
    [AUTH_PASSWORD] => 
    [AUTH_USER] => 
    [CERT_COOKIE] => 
    [CERT_FLAGS] => 
    [CERT_ISSUER] => 
    [CERT_SERIALNUMBER] => 
    [CERT_SUBJECT] => 
    [CONTENT_LENGTH] => 0
    [CONTENT_TYPE] => 
    [DOCUMENT_ROOT] => C:\inetpub\wwwroot
    [GATEWAY_INTERFACE] => CGI/1.1
    [HTTPS] => off
    [HTTPS_KEYSIZE] => 
    [HTTPS_SECRETKEYSIZE] => 
    [HTTPS_SERVER_ISSUER] => 
    [HTTPS_SERVER_SUBJECT] => 
    [INSTANCE_ID] => 1
    [INSTANCE_NAME] => DEFAULT WEB SITE
    [INSTANCE_META_PATH] => /LM/W3SVC/1
    [LOCAL_ADDR] => ::1
    [LOGON_USER] => 
    [PATH_TRANSLATED] => C:\inetpub\wwwroot\racemgr\kiosk.php
    [QUERY_STRING] => page=kiosks/identify.kiosk
    [REMOTE_ADDR] => ::1
    [REMOTE_HOST] => ::1
    [REMOTE_PORT] => 64170
    [REMOTE_USER] => 
    [REQUEST_METHOD] => GET
    [REQUEST_URI] => /derbynet/kiosk.php?page=kiosks/identify.kiosk
    [SCRIPT_FILENAME] => C:\inetpub\wwwroot\racemgr\kiosk.php
    [SCRIPT_NAME] => /derbynet/kiosk.php
    [SERVER_NAME] => localhost
    [SERVER_PORT] => 80
    [SERVER_PORT_SECURE] => 0
    [SERVER_PROTOCOL] => HTTP/1.1
    [SERVER_SOFTWARE] => Microsoft-IIS/10.0
    [URL] => /derbynet/kiosk.php
    [ORIG_PATH_INFO] => /derbynet/kiosk.php
    [PHP_SELF] => /derbynet/kiosk.php
    [REQUEST_TIME] => 1447809937
)

**Comment by jeffpiazza** [comment]
I misunderstood $_SERVER['REQUEST_URI'] to include the server name.
29cfcb6 should fix this.
