### ISSUE TITLE
DerbyStick Timer support

### ISSUE THREAD

**Issue by mwaldropdatastax** [jeffpiazza/derbynet#80]
I'm hoping to get drivers and try our DerbyStick timer with this awesome software.  The docs seem to indicate that it has not been tested, so I don't know if you have any other info.  I really hope to be able to use the timer on a Pi.  I'm actually hoping to run everything on a couple of Pi's and only use browser devices to manage everything.

One other question is storage.  Do you have any way to quantify the amount of data generated in a race ?  I plan to do video replay, driver images, and probably have around 200 heats or so.  I can do my own testing to figure it out, but if you have any sort of guidance on how much storage I'll need for the DB, that would be great.

**Comment by jeffpiazza** [comment]
I can confirm that DerbyNet works well with a DerbyStick timer -- a user even loaned me one for testing last year.  The DerbyStick is not a "discoverable" timer; that is, you'll need to choose NewBoldDevice explicitly as the device type, most likely from the command line, along with the serial port.

Storage requirements are generally minimal.  Most database files are a megabyte or two.  Each replay video runs about 250K (at least in my experience, when captured by Chrome), so your 200 heats would take up something like 50Mb.  Racer photos depends on your camera; 10-12M/photo is what I see from a T3i.  For our local district race, 85 racers, takes up something like 950M, including resizings.
