### ISSUE TITLE
Video Replay info

### ISSUE THREAD

**Issue by mwaldropdatastax** [jeffpiazza/derbynet#82]
I'm setting up and testing everything and I'm trying to come up with a good way to test / validate / demo the video playback capabilities.  I'm not exactly sure how to go about this.  I'm hoping to run the timer software and a webcam for the replay on a Raspberry Pi.  I will eventually have to set up a "full up" test with all the components, but I'm hoping to do some initial validation before getting everything set up.

Any advice for how to validate that the webcam is connected, working, and communicating with the derbynet server ?  I can go into command line in Debian and see that the webcam is connected and able to capture an image, but beyond that I'm not sure how to test it out.

Thanks - I'm loving this setup.  You really put together a very thoughtful architecture.

**Comment by jeffpiazza** [comment]
There's a "Test Replay" button on the Race Dashboard that exercises the replay behavior after a heat finishes (minus the upload).  It sounds like that's what you're looking for.

Feel free to email directly with questions like this: jeff@jeffpiazza.org
