### ISSUE TITLE
Formatting issues with setup page in Chrome

### ISSUE THREAD

**Issue by heatvent** [jeffpiazza/derbynet#83]
The setup page works fine in Edge, but in Chrome, the new link to the documentation somehow gets wrapped over the setup database button.  Pressing anywhere at this height on the screen will open up the documentation and you can't get to the database setup at all.  Tried refreshing, closing, reopening, etc. and issue seems to persist.

![image](https://user-images.githubusercontent.com/19480678/71544852-91947b00-2949-11ea-9e91-683e071af39e.png)

**Comment by jeffpiazza** [comment]
Which version of Chrome, and on what host (I'm guessing Windows)?

79.0.3945.88 (Official Build) (64-bit) on Mac doesn't seem to exhibit this issue.

**Comment by heatvent** [comment]
Sorry, should of thought of putting that in the issue.  It is the latest
version on windows 10 64-bit..

Version 79.0.3945.88 (Official Build) (64-bit)

**Comment by jeffpiazza** [comment]
I can't seem to reproduce this.  I'm using the same version of Chrome, on Windows 10.

Maybe try flushing the cache (ctrl-shift-delete):
<img width="484" alt="image" src="https://user-images.githubusercontent.com/13140826/71546582-6704eb00-2966-11ea-8fcd-231c969334e3.png">

**Comment by heatvent** [comment]
Jeff, that seemed to work.  Not sure why it was giving me the issue in the
first place but seems OK now.  Thanks for the help.

**Comment by heatvent** [comment]
Seemed to be an issue with cache.
