### ISSUE TITLE
Cannot switch between cameras on multi-camera devices

### ISSUE THREAD

**Issue by nsxfreddy** [jeffpiazza/derbynet#86]
The "Switch Camera" button does not switch between multiple cameras. Tested on iOS Safari and Windows 10 Chrome, on both the car capture and head capture. Possibly related, the camera seems to remain in use until you navigate away from the page, even if you Cancel the capture.

**Comment by jeffpiazza** [comment]
Yikes, sorry about that -- should have done more hand testing before pushing.
