### ISSUE TITLE
Present Awards Not Showing Speed Awards

### ISSUE THREAD

**Issue by jryd2000** [jeffpiazza/derbynet#87]
I used this software last year for our PWD.    I am running through a test race to make sure everything is working correctly.  After I manually entered bogus race times for the 2 races in one of our dens and the race was complete I wanted to simulate the awards presentation.  When I to the Present Awards module I can see all of the design awards but I don't see the speed awards for the first and second place for the den race I just simulated.  I have the LOV at the top set to All Awards and the only option in the second LOV is All.

**Comment by jeffpiazza** [comment]
Thanks for reporting this.  This appears to have been introduced in fcd99f29d86c27088a5847ef0faafce8afd1f576, which means it likely affects all builds of v5.0 up until build 975.

**Comment by jryd2000** [comment]
Thank you for fixing it so quickly.  We have our derby in 2 weeks.
