### ISSUE TITLE
Timer not reporting times for all lanes, causes confusion and errors

### ISSUE THREAD

**Issue by joncamp** [jeffpiazza/derbynet#89]
We have a FastTrack K3 timer that we have been testing for our upcoming derby. I set the timer applet to use the FastTrack setting and initially it seemed OK. However, running the timer resulted in heats that would finish but not properly update the status bar. Further investigation showed that derbynet was picking up that the race was over, but was not getting all the lane times. Switching to the 'old p series' setting seems to make it work better.

Two issues:
- something is off with the FastTrack newer setting perhaps
- when a race is completed, there is no way to quickly see the prior heat results on the race coordinator screen

While the first is annoying, the second is more troubling since it hides the first issue. Would highly suggest something on the race coordinator screen to show previous heat as well as current heat...or changing the status bar to a different widget that better indicates whether the heats completed successfully.

Happy to pull logs if that would help, especially on the timer applet

**Comment by jeffpiazza** [comment]
Yes, logs from the timer, please.

**Comment by joncamp** [comment]
[timer-20200105-1842.log](https://github.com/jeffpiazza/derbynet/files/4024515/timer-20200105-1842.log)

**Comment by jeffpiazza** [comment]
It looks to me like the timer doesn't understand some of the commands sent to it, and the error responses cause problems parsing the finish message.

At least for a K1 timer, and I suspect K2 and K3 as well, the "X" responses from the timer indicate a disabled option -- apparently microwizard used to, and maybe still does, sell timers with different features enabled.  I'd suggest getting in touch with MicroWizard.com to see about getting lane masking features enabled.

(The misspelling of "Copyrigh" [sic] being reported from the timer jumps out at me, too, but I don't really know what to conclude from that.)

derby-timer.jar should be more robust in the face of these issues, and stop trying to send commands that the timer rejects.  I'll have an update for you to try in the next few days.

derby-timer.jar should at least handle the error responses more gracefully, and not lose

**Comment by joncamp** [comment]
I have an active conversation going with the Micro Wizard folks. In general, looking at the logs there seems to be a few issues as noted below. I think on the DerbyNet side, i think the main thing to consider is whether it is ok to silently log a heat as being "completed" even though not all lanes that were expecting results actually got results.

- The device appears to be sending back some errant '@>' characters 

+18:42:36.990S --> RG
+18:42:36.997S <-- RG0​
+18:42:37.494S --> RG​
+18:42:37.501S <-- @>RG0​
+18:42:38.502S INT ** Unable to determine starting gate state​
+18:42:38.553S --> RG​
+18:42:38.560S <-- RG0

- As noted, the timer is returning "X" when trying to do lane masking. 

+18:43:07.625S --> MG
+18:43:07.625S --> MC​
+18:43:07.631S <-- MG​
+18:43:07.634S <-- X​
+18:43:07.638S <-- MC​
+18:43:07.641S <-- X​
+18:43:07.675S --> MD​
+18:43:07.681S <-- MD​
+18:43:07.684S <-- X​
+18:43:07.725S --> ME​
+18:43:07.732S <-- ME​
+18:43:07.735S <-- X​
+18:43:07.777S --> MF​
+18:43:07.783S <-- MF​
+18:43:07.786S <-- X

- There are some interleaved results as well, with two response messages colliding:

+18:43:43.954S --> RG
+18:43:43.962S <-- R**A**G0​
+18:43:44.024S <-- =0.7511! B=1.0408" C=1.2075# D=1.4278$ E=0.0000  F=0.0000

+18:43:50.803S --> RG
+18:43:50.810S <-- A=0.7919! B=0.9926" C=1.1297# D=1**.RG0​**
+18:43:50.838S <-- 2796$ E=0.0000  F=0.0000

**Comment by TheGlobalMind** [comment]
>     * when a race is completed, there is no way to quickly see the prior heat results on the race coordinator screen

Jon, are you seeing that the data on the coordinator screen comes up and then goes away quickly (more so than you can observe it) or that it doesn't appear at all?  I think the first race test I did it showed up, then afterward I don't see any data at all and it moves to the next heat. 

However, on the kiosks I see it records the time. As I am testing I am using that as a way to know I got data from all lanes. I know we had a little delay in there before it moved to the next race in our old software, which helped with that data validation.

Ours is one of the older P-Series timers.

**Comment by joncamp** [comment]
On the race coordinator screen it goes from heat 3 to heat 4, for example. the bottom blue bar may or may not move forward. it seems like if any lanes that report then it moves forward, but if no lanes report then the blue bar doesn't change.

Yes, using a kiosk to monitor the previous race is an option. However, it seemed weird to me that the race coordinator display (which should be mission control) is not showing this critical info. You can certainly move forward/back in the heats, but that sets racing to off...which can cause issues because you can run a race that doesn't get recorded then.

Ours is a K3 timer. We were able to get Micro Wizard to unlock the lane mask features, so that should help a bit.
