### ISSUE TITLE
E-mail address given in About page undeliverable

### ISSUE THREAD

**Issue by jasonmuzzy** [jeffpiazza/derbynet#9]
The e-mail address given on the "About" page for reporting bugs is bugs@jeffpiazza.org:
![image](https://cloud.githubusercontent.com/assets/15488120/11226515/54fc562c-8d35-11e5-8d6d-5e9763cb42d5.png)

However mail sent to that e-mail address was undeliverable:
![image](https://cloud.githubusercontent.com/assets/15488120/11226490/32fa0eac-8d35-11e5-80b6-889e5025f917.png)

**Comment by jeffpiazza** [comment]
Fixed mail forwarder settings, so working now.
