### ISSUE TITLE
Feature Request: Serial monitor in derby-timer.jar UI

### ISSUE THREAD

**Issue by joncamp** [jeffpiazza/derbynet#91]
Looking at the logs is great, but it would be nice to have a window that showed a live view of the serial communication with the timer.

Also, a button to open the log file in a text editor (or at least tell you where it is being dumped) would be very useful if the timer is opened by double clicking the jar file.

**Comment by jeffpiazza** [comment]
To the second point: as of build 978, there's a "Show Log File" command under the in-window "File" menu that shows the folder containing the log file.

**Comment by joncamp** [comment]
One option that worked well for me was to use powershell to monitor the file:
`Get-Content .\timer-20200116-1808.log -Wait -Tail 15`

Probably a reasonable compromise in the short term. Linux has equivalent behavior using 'tail -f'
