### ISSUE TITLE
Apache not starting with syntax error and missing ssl cert file

### ISSUE THREAD

**Issue by B3DTech** [jeffpiazza/derbynet#92]
OS X 10.15.3

Installed DerbyNet and the website didn't start.  Checking apachectl, receiving the following:

>apachectl
AH00526: Syntax error on line 14 of /private/etc/apache2/derbynet/derbynet.conf:
SSLCertificateFile: file '/private/etc/apache2/derbynet/derbynet.crt' does not exist or is empty

Indeed, the crt file is missing.

ls /private/etc/apache2/derbynet/
derbynet.conf    derbynet.key     derbynet.key.pub

**Comment by jeffpiazza** [comment]
Which build of DerbyNet are you using?  Did it seem to install OK?

What files do you see in /private/etc/apache2/derbynet ?

The installer is supposed to create a certificate during the installation.  There's nothing very complicated about the control flow, so I'm surprised if it didn't just work as expected:
https://github.com/jeffpiazza/derbynet/blob/master/installer/mac/scripts/webserver/create-apache-derbynet-directory.sh

**Comment by jeffpiazza** [comment]
It looks like somehow you have a derbynet.key lying there, perhaps from a previous install.  Could you do an "ls -l /private/etc/apache2/derbynet/" ?  Do remember installing and/or uninstalling earlier versions of DerbyNet?  Did this recent install seem to go OK?

Creation of the certificate is conditioned on the absence of a derbynet.key file; the control logic here should perhaps be more nuanced.
https://github.com/jeffpiazza/derbynet/blob/master/installer/mac/scripts/webserver/create-apache-derbynet-directory.sh

As a workaround/fix, you should be able to execute the commands from the script by hand.  Alternatively, you could delete the /private/etc/apache2/derbynet directory and install again.

**Comment by B3DTech** [comment]
The install went flawlessly, and I have never installed DerbyNet before.  I deleted the files and manually recreated them using your script, but it didn't work with the following error when generating the CSR.  It appears that the private key generated using ssh-keygen is in the incorrect format for openssl to use when building the CSR.

unable to load Private Key
4592877164:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.11.1/libressl-2.8/crypto/pem/pem_lib.c:684:Expecting: ANY PRIVATE KEY


I created the private key using this method and it worked fine:
>sudo openssl genrsa -des3 -passout pass:x -out derbynet.pass.key 2048
>sudo openssl rsa -passin pass:x -in derbynet.pass.key -out derbynet.key
>rm derbynet.pass.key

Then went back to the install script to create the CSR and CRT:
>openssl req -new -subj "/C=US/ST=-/O=-/localityName=-/CN=$SERVERNAME/"\
            -key "$DSTVOLUME/private/etc/apache2/derbynet/derbynet.key" \
            -out "$DSTVOLUME/private/etc/apache2/derbynet/derbynet.csr"

>openssl x509 -req -days 800 \
            -in "$DSTVOLUME/private/etc/apache2/derbynet/derbynet.csr" \
            -signkey "$DSTVOLUME/private/etc/apache2/derbynet/derbynet.key" \
            -out "$DSTVOLUME/private/etc/apache2/derbynet/derbynet.crt"

**Comment by B3DTech** [comment]
Once I created the self-signed cert, it worked fine.  It also doesn't redirect automatically to the derbynet VirtualHost, but that's not a big deal.

I'm evaluating using DerbyNet as a front end for GrandPrix since that's what we're using for the actual race software.  I'd much prefer using a browser based UI for our main presentation screen because I can run that on a Pi connected to the projector and leave the main laptop over by the track for the solenoid release.

**Comment by jeffpiazza** [comment]
Should be fixed with e7861d5117089ec96f419277d8b4f74705c5436d
