### ISSUE TITLE
Lane bias analysis reports not enough data available

### ISSUE THREAD

**Issue by ajspeck** [jeffpiazza/derbynet#97]
Despite having many runs recorded, the lane bias analysis analysis allows shows:

Lane Bias Analysis
There isn't enough evidence to assess lane bias.

Looking at the logs I see two errors which suggest there is some missing code:
PHP Notice:  Undefined variable: ssbetween in /var/www/html/derbynet/inc/lane-bias.inc on line 58"
PHP Notice:  Undefined variable: sswithin in /var/www/html/derbynet/inc/lane-bias.inc on line 59"

**Comment by jeffpiazza** [comment]
Wow, thanks for finding this.

I did confirm that this worked originally, but somehow what I checked in initially was missing a small but important code paragraph.  And since I hadn't bothered to write a test for the lane bias analysis, the failure went undetected until now.

How embarrassing.
