### ISSUE TITLE
Undefined variable: standigs_state

### ISSUE THREAD

**Issue by ajspeck** [jeffpiazza/derbynet#98]
There appears to be a spelling error here which results in an undefined variable error:
https://github.com/jeffpiazza/derbynet/blob/8b5548b335d3244e4e7a9236e7a457bee1f255ad/website/kiosk-dashboard.php#L39

**Comment by jeffpiazza** [comment]
As you've no doubt seen, the typo is harmless, aside from the warning message, as the if block it guards is empty.

I noticed this myself a few days ago, and had started on a fix, but haven't yet finished it.
