### ISSUE TITLE
Button alignment issue in Firefox

### ISSUE THREAD

**Issue by chunter2** [jeffpiazza/derbynet#99]
The "Purge Data" button in the Set-Up page is miss aligned in Firefox.  It seems to be fine in Chrome.  

![firefox derbynet1](https://user-images.githubusercontent.com/531129/72271438-e5af8880-35f4-11ea-9938-600d0d38feca.jpg)
![firefox derbynet2](https://user-images.githubusercontent.com/531129/72271447-e8aa7900-35f4-11ea-95dc-29e832b63814.jpg)

**Comment by joncamp** [comment]
The offset seems to be 300px. Inserting margin-left: -300px will fix it in firefox, but messes up chrome
